import { NextRequest, NextResponse } from "next/server";
import { parseAdminSession } from "@/lib/auth/types";
import { TICKET_STATUSES, type SupportTicketDetail, type SupportTicketList, type SupportTicketSummary, type TicketPriority, type TicketSlaState, type TicketStatus } from "@/lib/support/types";
import { parseAdminSupportPath } from "@/lib/support/validation";

interface UpstreamError { code?: string; message?: string; errors?: Array<{ field: string; message: string }> }
class UpstreamHttpError extends Error { constructor(readonly status: number, readonly body: UpstreamError = {}) { super(body.message || `Admin support upstream returned ${status}`); } }
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const string = (value: unknown, fallback = "") => typeof value === "string" ? value : fallback; const number = (value: unknown, fallback = 0) => typeof value === "number" && Number.isFinite(value) ? value : fallback; const array = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const date = (value: unknown) => { const raw = string(value); return raw && !Number.isNaN(Date.parse(raw)) ? raw : new Date().toISOString(); }; const nullableDate = (value: unknown) => { const raw = string(value); return raw && !Number.isNaN(Date.parse(raw)) ? raw : null; }; const nullableString = (value: unknown) => typeof value === "string" && value.trim() ? value : null;
const STATUSES = new Set<SupportTicketSummary["status"]>(TICKET_STATUSES); const PRIORITIES = new Set<TicketPriority>(["NORMAL", "IMPORTANT", "URGENT"]); const SLA_STATES = new Set<TicketSlaState>(["ON_TRACK", "AT_RISK", "OVERDUE", "PAUSED", "COMPLETE"]);
function responseError(code: string, message: string, status: number, errors: Array<{ field: string; message: string }> = []) { return NextResponse.json({ code, message, errors, requestId: `BFF-ADMIN-SUPPORT-${code}` }, { status }); }
function baseUrl() { return (process.env.ADMIN_API_UPSTREAM_URL ?? "http://127.0.0.1:4030/api/v1").replace(/\/$/u, ""); } function mockProfile() { return process.env.NODE_ENV === "production" ? "" : process.env.ADMIN_MOCK_PROFILE ?? process.env.ADMIN_MOCK_ROLE ?? "SALES_MANAGER"; }
function headers(request: NextRequest) { const result = new Headers({ Accept: "application/json" }); const authorization = request.headers.get("authorization"); if (authorization) result.set("Authorization", authorization); const profile = mockProfile(); if (profile) result.set("X-Admin-Profile", profile); return result; }
async function upstream(request: NextRequest, path: string) { const response = await fetch(`${baseUrl()}/${path}`, { headers: headers(request), cache: "no-store", redirect: "manual" }); const payload: unknown = (response.headers.get("content-type") ?? "").includes("application/json") ? await response.json() : {}; if (!response.ok) throw new UpstreamHttpError(response.status, record(payload) ? payload : {}); return record(payload) ? payload : {}; }
async function session(request: NextRequest) { const response = await fetch(`${baseUrl()}/admin/session`, { headers: headers(request), cache: "no-store", redirect: "manual" }); if (!response.ok) throw new UpstreamHttpError(response.status, { code: "ADMIN_SESSION_REQUIRED", message: "Phiên nhân viên không hợp lệ." }); const parsed = parseAdminSession(await response.json()); if (!parsed) throw new UpstreamHttpError(502, { code: "ADMIN_SESSION_INVALID", message: "Projection quyền nhân viên không hợp lệ." }); return parsed; }
function status(value: unknown): TicketStatus { const result = string(value) as TicketStatus; return STATUSES.has(result) ? result : "NEW"; } function priority(value: unknown): TicketPriority { const result = string(value) as TicketPriority; return PRIORITIES.has(result) ? result : "NORMAL"; } function slaState(value: unknown): TicketSlaState { const result = string(value) as TicketSlaState; return SLA_STATES.has(result) ? result : "ON_TRACK"; }
function sla(value: unknown) { const item = record(value) ? value : {}; return { state: slaState(item.state), stateLabel: string(item.stateLabel), dueAt: nullableDate(item.dueAt) }; }
function mapSummary(value: unknown): SupportTicketSummary { const item = record(value) ? value : {}; return { ticketId: string(item.ticketId), ticketNumber: string(item.ticketNumber), subjectCode: string(item.subjectCode), subjectLabel: string(item.subjectLabel), title: string(item.title), customerLabel: string(item.customerLabel), customerMode: item.customerMode === "GUEST" ? "GUEST" : "REGISTERED", channelCode: string(item.channelCode), channelLabel: string(item.channelLabel), status: status(item.status), statusLabel: string(item.statusLabel), priority: priority(item.priority), priorityLabel: string(item.priorityLabel), queueLabel: string(item.queueLabel), assigneeLabel: nullableString(item.assigneeLabel), firstResponseSla: sla(item.firstResponseSla), resolutionSla: sla(item.resolutionSla), linkedReferenceCount: Math.max(0, number(item.linkedReferenceCount)), unreadCount: Math.max(0, number(item.unreadCount)), lastMessageAt: date(item.lastMessageAt), updatedAt: date(item.updatedAt), revision: Math.max(1, number(item.revision, 1)) }; }
function mapList(payload: Record<string, unknown>): SupportTicketList { const items = array(payload.items).map(mapSummary).filter((item) => item.ticketId); const statusCounts = array(payload.statusCounts).map((value) => { const item = record(value) ? value : {}; const raw = string(item.status) as "ALL" | TicketStatus; return { status: raw === "ALL" || STATUSES.has(raw as TicketStatus) ? raw : "ALL", label: string(item.label), count: Math.max(0, number(item.count)) }; }); if (!statusCounts.some((item) => item.status === "ALL")) statusCounts.unshift({ status: "ALL", label: "Tất cả", count: items.length }); const options = (value: unknown) => array(value).map((row) => { const item = record(row) ? row : {}; return { code: string(item.code), label: string(item.label) }; }).filter((item) => item.code); return { items, statusCounts, subjects: options(payload.subjects), channels: options(payload.channels), calculatedAt: date(payload.calculatedAt) }; }
function mapDetail(payload: Record<string, unknown>, conversationAllowed: boolean, notesAllowed: boolean, contextAllowed: boolean): SupportTicketDetail { const customer = record(payload.customer) ? payload.customer : {}; const context = record(payload.context) ? payload.context : null; const messages = conversationAllowed ? array(payload.messages).flatMap((value) => { const item = record(value) ? value : {}; const kind = item.kind === "INTERNAL_NOTE" ? "INTERNAL_NOTE" as const : "PUBLIC" as const; if (kind === "INTERNAL_NOTE" && !notesAllowed) return []; return [{ messageId: string(item.messageId), kind, senderRole: string(item.senderRole), senderLabel: string(item.senderLabel), channelLabel: string(item.channelLabel), deliveryStateLabel: string(item.deliveryStateLabel), content: string(item.content), sentAt: date(item.sentAt) }]; }).filter((item) => item.messageId) : []; const contextItem = (value: unknown, withReference: boolean) => { const item = record(value) ? value : null; return item ? { ...(withReference ? { reference: string(item.reference) } : {}), statusLabel: string(item.statusLabel) } : null; }; return { ...mapSummary(payload), createdAt: date(payload.createdAt), customer: { displayName: string(customer.displayName), contactDisplay: string(customer.contactDisplay, "Đã ẩn"), profileLabel: string(customer.profileLabel), masked: customer.masked === true }, messages, conversationMasked: !conversationAllowed, context: contextAllowed && context ? { order: contextItem(context.order, true) as SupportTicketDetail["context"] extends infer C ? C extends { order: infer O } ? O : never : never, payment: contextItem(context.payment, false) as { statusLabel: string } | null, shipment: contextItem(context.shipment, false) as { statusLabel: string } | null, returnCase: contextItem(context.returnCase, true) as { reference: string; statusLabel: string } | null, sourcesUpdatedAt: date(context.sourcesUpdatedAt) } : null, contextMasked: !contextAllowed, history: array(payload.history).map((value) => { const item = record(value) ? value : {}; return { eventId: string(item.eventId), label: string(item.label), actorLabel: string(item.actorLabel), occurredAt: date(item.occurredAt), detail: nullableString(item.detail) }; }).filter((item) => item.eventId) }; }

export async function handleAdminSupport(request: NextRequest, path: string[]) { const route = parseAdminSupportPath(path); if (route.kind === "invalid") return responseError("NOT_FOUND", "Admin support route không tồn tại.", 404); if (request.method !== "GET") return responseError("METHOD_NOT_ALLOWED", "Method không được hỗ trợ.", 405); try { const currentSession = await session(request); if (!currentSession.permissions.includes("TICKET_QUEUE_VIEW")) return responseError("PERMISSION_FORBIDDEN", "Nhân viên không có quyền xem hàng đợi Ticket.", 403); if (route.kind === "ticket-list") return NextResponse.json(mapList(await upstream(request, "admin/support/tickets"))); return NextResponse.json(mapDetail(await upstream(request, `admin/support/tickets/${encodeURIComponent(route.ticketId)}`), currentSession.permissions.includes("TICKET_CONVERSATION_VIEW"), currentSession.permissions.includes("TICKET_INTERNAL_NOTE_VIEW"), currentSession.permissions.includes("TICKET_CONTEXT_VIEW"))); } catch (cause) { if (cause instanceof UpstreamHttpError) return responseError(cause.body.code || "ADMIN_SUPPORT_ERROR", cause.body.message || "Không thể xử lý yêu cầu quản lý Ticket.", cause.status >= 400 && cause.status <= 599 ? cause.status : 500, cause.body.errors ?? []); return responseError("ADMIN_SUPPORT_UPSTREAM_UNAVAILABLE", "Không thể kết nối dịch vụ hỗ trợ nội bộ.", 503); } }
