// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: profile/v1/profile.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Address } from "../../common/v1/types";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.profile.v1";

/** Yêu cầu lấy hồ sơ khách hàng */
export interface GetCustomerProfileRequest {
  customerId: string;
}

/** Thông tin hồ sơ khách hàng */
export interface CustomerProfileDetail {
  customerId: string;
  fullName: string;
  phoneNumber: string;
  email?:
    | string
    | undefined;
  /** Hạng thành viên thân thiết (Ví dụ: "BRONZE", "SILVER", "GOLD", "VIP_OCOP") */
  loyaltyTier: string;
  /** Số điểm tích lũy hiện có */
  loyaltyPoints: number;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

/** Phản hồi hồ sơ khách hàng */
export interface GetCustomerProfileResponse {
  profile?: CustomerProfileDetail | undefined;
  error?: ErrorDetail | undefined;
}

/** Yêu cầu lấy chi tiết một địa chỉ nhận hàng */
export interface GetDeliveryAddressRequest {
  /** Mã định danh bản ghi địa chỉ trong sổ địa chỉ */
  addressId: string;
  /** Mã khách hàng sở hữu (Bắt buộc để kiểm tra phân quyền sở hữu địa chỉ) */
  customerId: string;
}

/** Phản hồi chi tiết địa chỉ nhận hàng */
export interface GetDeliveryAddressResponse {
  addressId: string;
  address?: Address | undefined;
  isDefault: boolean;
  /** Ví dụ: "Nhà riêng", "Cơ quan", "Gửi tặng người thân" */
  label: string;
  error?: ErrorDetail | undefined;
}

/** Yêu cầu danh sách sổ địa chỉ */
export interface ListDeliveryAddressesRequest {
  customerId: string;
}

/** Bản ghi địa chỉ trong danh sách */
export interface DeliveryAddressEntry {
  addressId: string;
  address?: Address | undefined;
  isDefault: boolean;
  label: string;
}

/** Phản hồi danh sách sổ địa chỉ */
export interface ListDeliveryAddressesResponse {
  addresses: DeliveryAddressEntry[];
}

function createBaseGetCustomerProfileRequest(): GetCustomerProfileRequest {
  return { customerId: "" };
}

export const GetCustomerProfileRequest = {
  encode(message: GetCustomerProfileRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.customerId !== "") {
      writer.uint32(10).string(message.customerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetCustomerProfileRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCustomerProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.customerId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCustomerProfileRequest {
    return { customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "" };
  },

  toJSON(message: GetCustomerProfileRequest): unknown {
    const obj: any = {};
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCustomerProfileRequest>, I>>(base?: I): GetCustomerProfileRequest {
    return GetCustomerProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCustomerProfileRequest>, I>>(object: I): GetCustomerProfileRequest {
    const message = createBaseGetCustomerProfileRequest();
    message.customerId = object.customerId ?? "";
    return message;
  },
};

function createBaseCustomerProfileDetail(): CustomerProfileDetail {
  return {
    customerId: "",
    fullName: "",
    phoneNumber: "",
    email: undefined,
    loyaltyTier: "",
    loyaltyPoints: 0,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const CustomerProfileDetail = {
  encode(message: CustomerProfileDetail, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.customerId !== "") {
      writer.uint32(10).string(message.customerId);
    }
    if (message.fullName !== "") {
      writer.uint32(18).string(message.fullName);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(26).string(message.phoneNumber);
    }
    if (message.email !== undefined) {
      writer.uint32(34).string(message.email);
    }
    if (message.loyaltyTier !== "") {
      writer.uint32(42).string(message.loyaltyTier);
    }
    if (message.loyaltyPoints !== 0) {
      writer.uint32(48).int32(message.loyaltyPoints);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(58).fork()).ldelim();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CustomerProfileDetail {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomerProfileDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.customerId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.fullName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.loyaltyTier = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.loyaltyPoints = reader.int32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomerProfileDetail {
    return {
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
      fullName: isSet(object.fullName) ? globalThis.String(object.fullName) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      loyaltyTier: isSet(object.loyaltyTier) ? globalThis.String(object.loyaltyTier) : "",
      loyaltyPoints: isSet(object.loyaltyPoints) ? globalThis.Number(object.loyaltyPoints) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: CustomerProfileDetail): unknown {
    const obj: any = {};
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.loyaltyTier !== "") {
      obj.loyaltyTier = message.loyaltyTier;
    }
    if (message.loyaltyPoints !== 0) {
      obj.loyaltyPoints = Math.round(message.loyaltyPoints);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomerProfileDetail>, I>>(base?: I): CustomerProfileDetail {
    return CustomerProfileDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomerProfileDetail>, I>>(object: I): CustomerProfileDetail {
    const message = createBaseCustomerProfileDetail();
    message.customerId = object.customerId ?? "";
    message.fullName = object.fullName ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? undefined;
    message.loyaltyTier = object.loyaltyTier ?? "";
    message.loyaltyPoints = object.loyaltyPoints ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseGetCustomerProfileResponse(): GetCustomerProfileResponse {
  return { profile: undefined, error: undefined };
}

export const GetCustomerProfileResponse = {
  encode(message: GetCustomerProfileResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.profile !== undefined) {
      CustomerProfileDetail.encode(message.profile, writer.uint32(10).fork()).ldelim();
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetCustomerProfileResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCustomerProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.profile = CustomerProfileDetail.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCustomerProfileResponse {
    return {
      profile: isSet(object.profile) ? CustomerProfileDetail.fromJSON(object.profile) : undefined,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GetCustomerProfileResponse): unknown {
    const obj: any = {};
    if (message.profile !== undefined) {
      obj.profile = CustomerProfileDetail.toJSON(message.profile);
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCustomerProfileResponse>, I>>(base?: I): GetCustomerProfileResponse {
    return GetCustomerProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCustomerProfileResponse>, I>>(object: I): GetCustomerProfileResponse {
    const message = createBaseGetCustomerProfileResponse();
    message.profile = (object.profile !== undefined && object.profile !== null)
      ? CustomerProfileDetail.fromPartial(object.profile)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGetDeliveryAddressRequest(): GetDeliveryAddressRequest {
  return { addressId: "", customerId: "" };
}

export const GetDeliveryAddressRequest = {
  encode(message: GetDeliveryAddressRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.addressId !== "") {
      writer.uint32(10).string(message.addressId);
    }
    if (message.customerId !== "") {
      writer.uint32(18).string(message.customerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetDeliveryAddressRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeliveryAddressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.addressId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.customerId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDeliveryAddressRequest {
    return {
      addressId: isSet(object.addressId) ? globalThis.String(object.addressId) : "",
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
    };
  },

  toJSON(message: GetDeliveryAddressRequest): unknown {
    const obj: any = {};
    if (message.addressId !== "") {
      obj.addressId = message.addressId;
    }
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDeliveryAddressRequest>, I>>(base?: I): GetDeliveryAddressRequest {
    return GetDeliveryAddressRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDeliveryAddressRequest>, I>>(object: I): GetDeliveryAddressRequest {
    const message = createBaseGetDeliveryAddressRequest();
    message.addressId = object.addressId ?? "";
    message.customerId = object.customerId ?? "";
    return message;
  },
};

function createBaseGetDeliveryAddressResponse(): GetDeliveryAddressResponse {
  return { addressId: "", address: undefined, isDefault: false, label: "", error: undefined };
}

export const GetDeliveryAddressResponse = {
  encode(message: GetDeliveryAddressResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.addressId !== "") {
      writer.uint32(10).string(message.addressId);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(18).fork()).ldelim();
    }
    if (message.isDefault !== false) {
      writer.uint32(24).bool(message.isDefault);
    }
    if (message.label !== "") {
      writer.uint32(34).string(message.label);
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetDeliveryAddressResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeliveryAddressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.addressId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isDefault = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.label = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDeliveryAddressResponse {
    return {
      addressId: isSet(object.addressId) ? globalThis.String(object.addressId) : "",
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      isDefault: isSet(object.isDefault) ? globalThis.Boolean(object.isDefault) : false,
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GetDeliveryAddressResponse): unknown {
    const obj: any = {};
    if (message.addressId !== "") {
      obj.addressId = message.addressId;
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.isDefault !== false) {
      obj.isDefault = message.isDefault;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDeliveryAddressResponse>, I>>(base?: I): GetDeliveryAddressResponse {
    return GetDeliveryAddressResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDeliveryAddressResponse>, I>>(object: I): GetDeliveryAddressResponse {
    const message = createBaseGetDeliveryAddressResponse();
    message.addressId = object.addressId ?? "";
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.isDefault = object.isDefault ?? false;
    message.label = object.label ?? "";
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseListDeliveryAddressesRequest(): ListDeliveryAddressesRequest {
  return { customerId: "" };
}

export const ListDeliveryAddressesRequest = {
  encode(message: ListDeliveryAddressesRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.customerId !== "") {
      writer.uint32(10).string(message.customerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListDeliveryAddressesRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDeliveryAddressesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.customerId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDeliveryAddressesRequest {
    return { customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "" };
  },

  toJSON(message: ListDeliveryAddressesRequest): unknown {
    const obj: any = {};
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDeliveryAddressesRequest>, I>>(base?: I): ListDeliveryAddressesRequest {
    return ListDeliveryAddressesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDeliveryAddressesRequest>, I>>(object: I): ListDeliveryAddressesRequest {
    const message = createBaseListDeliveryAddressesRequest();
    message.customerId = object.customerId ?? "";
    return message;
  },
};

function createBaseDeliveryAddressEntry(): DeliveryAddressEntry {
  return { addressId: "", address: undefined, isDefault: false, label: "" };
}

export const DeliveryAddressEntry = {
  encode(message: DeliveryAddressEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.addressId !== "") {
      writer.uint32(10).string(message.addressId);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(18).fork()).ldelim();
    }
    if (message.isDefault !== false) {
      writer.uint32(24).bool(message.isDefault);
    }
    if (message.label !== "") {
      writer.uint32(34).string(message.label);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeliveryAddressEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeliveryAddressEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.addressId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isDefault = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.label = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeliveryAddressEntry {
    return {
      addressId: isSet(object.addressId) ? globalThis.String(object.addressId) : "",
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      isDefault: isSet(object.isDefault) ? globalThis.Boolean(object.isDefault) : false,
      label: isSet(object.label) ? globalThis.String(object.label) : "",
    };
  },

  toJSON(message: DeliveryAddressEntry): unknown {
    const obj: any = {};
    if (message.addressId !== "") {
      obj.addressId = message.addressId;
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.isDefault !== false) {
      obj.isDefault = message.isDefault;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeliveryAddressEntry>, I>>(base?: I): DeliveryAddressEntry {
    return DeliveryAddressEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeliveryAddressEntry>, I>>(object: I): DeliveryAddressEntry {
    const message = createBaseDeliveryAddressEntry();
    message.addressId = object.addressId ?? "";
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.isDefault = object.isDefault ?? false;
    message.label = object.label ?? "";
    return message;
  },
};

function createBaseListDeliveryAddressesResponse(): ListDeliveryAddressesResponse {
  return { addresses: [] };
}

export const ListDeliveryAddressesResponse = {
  encode(message: ListDeliveryAddressesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.addresses) {
      DeliveryAddressEntry.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListDeliveryAddressesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDeliveryAddressesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.addresses.push(DeliveryAddressEntry.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDeliveryAddressesResponse {
    return {
      addresses: globalThis.Array.isArray(object?.addresses)
        ? object.addresses.map((e: any) => DeliveryAddressEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListDeliveryAddressesResponse): unknown {
    const obj: any = {};
    if (message.addresses?.length) {
      obj.addresses = message.addresses.map((e) => DeliveryAddressEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDeliveryAddressesResponse>, I>>(base?: I): ListDeliveryAddressesResponse {
    return ListDeliveryAddressesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDeliveryAddressesResponse>, I>>(
    object: I,
  ): ListDeliveryAddressesResponse {
    const message = createBaseListDeliveryAddressesResponse();
    message.addresses = object.addresses?.map((e) => DeliveryAddressEntry.fromPartial(e)) || [];
    return message;
  },
};

export type ProfileServiceService = typeof ProfileServiceService;
export const ProfileServiceService = {
  /** Lấy thông tin hồ sơ khách hàng (Query từ MS-04 Order, MS-06 Care) */
  getCustomerProfile: {
    path: "/omamx.profile.v1.ProfileService/GetCustomerProfile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetCustomerProfileRequest) =>
      Buffer.from(GetCustomerProfileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetCustomerProfileRequest.decode(value),
    responseSerialize: (value: GetCustomerProfileResponse) =>
      Buffer.from(GetCustomerProfileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetCustomerProfileResponse.decode(value),
  },
  /** Lấy chi tiết một địa chỉ giao nhận cụ thể để lưu Address Snapshot vào đơn hàng (Query từ MS-04, MS-02) */
  getDeliveryAddress: {
    path: "/omamx.profile.v1.ProfileService/GetDeliveryAddress",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetDeliveryAddressRequest) =>
      Buffer.from(GetDeliveryAddressRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetDeliveryAddressRequest.decode(value),
    responseSerialize: (value: GetDeliveryAddressResponse) =>
      Buffer.from(GetDeliveryAddressResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetDeliveryAddressResponse.decode(value),
  },
  /** Lấy danh sách sổ địa chỉ nhận hàng của khách hàng */
  listDeliveryAddresses: {
    path: "/omamx.profile.v1.ProfileService/ListDeliveryAddresses",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListDeliveryAddressesRequest) =>
      Buffer.from(ListDeliveryAddressesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListDeliveryAddressesRequest.decode(value),
    responseSerialize: (value: ListDeliveryAddressesResponse) =>
      Buffer.from(ListDeliveryAddressesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListDeliveryAddressesResponse.decode(value),
  },
} as const;

export interface ProfileServiceServer extends UntypedServiceImplementation {
  /** Lấy thông tin hồ sơ khách hàng (Query từ MS-04 Order, MS-06 Care) */
  getCustomerProfile: handleUnaryCall<GetCustomerProfileRequest, GetCustomerProfileResponse>;
  /** Lấy chi tiết một địa chỉ giao nhận cụ thể để lưu Address Snapshot vào đơn hàng (Query từ MS-04, MS-02) */
  getDeliveryAddress: handleUnaryCall<GetDeliveryAddressRequest, GetDeliveryAddressResponse>;
  /** Lấy danh sách sổ địa chỉ nhận hàng của khách hàng */
  listDeliveryAddresses: handleUnaryCall<ListDeliveryAddressesRequest, ListDeliveryAddressesResponse>;
}

export interface ProfileServiceClient extends Client {
  /** Lấy thông tin hồ sơ khách hàng (Query từ MS-04 Order, MS-06 Care) */
  getCustomerProfile(
    request: GetCustomerProfileRequest,
    callback: (error: ServiceError | null, response: GetCustomerProfileResponse) => void,
  ): ClientUnaryCall;
  getCustomerProfile(
    request: GetCustomerProfileRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetCustomerProfileResponse) => void,
  ): ClientUnaryCall;
  getCustomerProfile(
    request: GetCustomerProfileRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetCustomerProfileResponse) => void,
  ): ClientUnaryCall;
  /** Lấy chi tiết một địa chỉ giao nhận cụ thể để lưu Address Snapshot vào đơn hàng (Query từ MS-04, MS-02) */
  getDeliveryAddress(
    request: GetDeliveryAddressRequest,
    callback: (error: ServiceError | null, response: GetDeliveryAddressResponse) => void,
  ): ClientUnaryCall;
  getDeliveryAddress(
    request: GetDeliveryAddressRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetDeliveryAddressResponse) => void,
  ): ClientUnaryCall;
  getDeliveryAddress(
    request: GetDeliveryAddressRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetDeliveryAddressResponse) => void,
  ): ClientUnaryCall;
  /** Lấy danh sách sổ địa chỉ nhận hàng của khách hàng */
  listDeliveryAddresses(
    request: ListDeliveryAddressesRequest,
    callback: (error: ServiceError | null, response: ListDeliveryAddressesResponse) => void,
  ): ClientUnaryCall;
  listDeliveryAddresses(
    request: ListDeliveryAddressesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListDeliveryAddressesResponse) => void,
  ): ClientUnaryCall;
  listDeliveryAddresses(
    request: ListDeliveryAddressesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListDeliveryAddressesResponse) => void,
  ): ClientUnaryCall;
}

export const ProfileServiceClient = makeGenericClientConstructor(
  ProfileServiceService,
  "omamx.profile.v1.ProfileService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ProfileServiceClient;
  service: typeof ProfileServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
