// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: identity/v1/identity.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { AuditContext } from "../../common/v1/types";

export const protobufPackage = "omamx.identity.v1";

/** Yêu cầu thẩm duyệt quyền động */
export interface SpecializedPermissionRequest {
  /** Mã người dùng thực hiện thao tác */
  userId: string;
  /** Hành động yêu cầu thẩm duyệt (Ví dụ: "FINANCE_REFUND_APPROVE", "B2B_DISCOUNT_APPLY") */
  action: string;
  /**
   * Thuộc tính ngữ cảnh động phục vụ đánh giá chính sách (Context Attributes)
   * Ví dụ: {"refund_amount": "15000000", "discount_percentage": "28", "order_channel": "B2B"}
   */
  contextAttributes: { [key: string]: string };
  /** Bối cảnh kiểm toán */
  auditContext?: AuditContext | undefined;
}

export interface SpecializedPermissionRequest_ContextAttributesEntry {
  key: string;
  value: string;
}

/** Phản hồi kết quả thẩm duyệt quyền động */
export interface SpecializedPermissionResponse {
  /** Quyết định: true nếu được phép thực hiện, false nếu bị từ chối */
  isAllowed: boolean;
  /** Lý do đưa ra quyết định (Phục vụ hiển thị UI và ghi nhận vào Audit Plane) */
  decisionReason: string;
  /** Cấp bậc thẩm duyệt được yêu cầu (Ví dụ: "DIRECTOR_APPROVAL_REQUIRED") */
  requiredApprovalLevel?:
    | string
    | undefined;
  /** Chi tiết lỗi nếu phát sinh sự cố trong quá trình thẩm duyệt */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu lấy JWKS Public Key */
export interface GetJwksPublicKeyRequest {
  /** Key ID (Optional - nếu bỏ trống sẽ lấy key active mới nhất) */
  keyId?: string | undefined;
}

/** Phản hồi JWKS Public Key */
export interface GetJwksPublicKeyResponse {
  keyId: string;
  /** Ví dụ: "RS256" hoặc "EdDSA" */
  algorithm: string;
  /** Chuỗi chứng chỉ khóa công khai định dạng PEM */
  publicKeyPem: string;
}

function createBaseSpecializedPermissionRequest(): SpecializedPermissionRequest {
  return { userId: "", action: "", contextAttributes: {}, auditContext: undefined };
}

export const SpecializedPermissionRequest = {
  encode(message: SpecializedPermissionRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.action !== "") {
      writer.uint32(18).string(message.action);
    }
    Object.entries(message.contextAttributes).forEach(([key, value]) => {
      SpecializedPermissionRequest_ContextAttributesEntry.encode({ key: key as any, value }, writer.uint32(26).fork())
        .ldelim();
    });
    if (message.auditContext !== undefined) {
      AuditContext.encode(message.auditContext, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SpecializedPermissionRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpecializedPermissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.action = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          const entry3 = SpecializedPermissionRequest_ContextAttributesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.contextAttributes[entry3.key] = entry3.value;
          }
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.auditContext = AuditContext.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpecializedPermissionRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      contextAttributes: isObject(object.contextAttributes)
        ? Object.entries(object.contextAttributes).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      auditContext: isSet(object.auditContext) ? AuditContext.fromJSON(object.auditContext) : undefined,
    };
  },

  toJSON(message: SpecializedPermissionRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.contextAttributes) {
      const entries = Object.entries(message.contextAttributes);
      if (entries.length > 0) {
        obj.contextAttributes = {};
        entries.forEach(([k, v]) => {
          obj.contextAttributes[k] = v;
        });
      }
    }
    if (message.auditContext !== undefined) {
      obj.auditContext = AuditContext.toJSON(message.auditContext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpecializedPermissionRequest>, I>>(base?: I): SpecializedPermissionRequest {
    return SpecializedPermissionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpecializedPermissionRequest>, I>>(object: I): SpecializedPermissionRequest {
    const message = createBaseSpecializedPermissionRequest();
    message.userId = object.userId ?? "";
    message.action = object.action ?? "";
    message.contextAttributes = Object.entries(object.contextAttributes ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.auditContext = (object.auditContext !== undefined && object.auditContext !== null)
      ? AuditContext.fromPartial(object.auditContext)
      : undefined;
    return message;
  },
};

function createBaseSpecializedPermissionRequest_ContextAttributesEntry(): SpecializedPermissionRequest_ContextAttributesEntry {
  return { key: "", value: "" };
}

export const SpecializedPermissionRequest_ContextAttributesEntry = {
  encode(
    message: SpecializedPermissionRequest_ContextAttributesEntry,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SpecializedPermissionRequest_ContextAttributesEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpecializedPermissionRequest_ContextAttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpecializedPermissionRequest_ContextAttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: SpecializedPermissionRequest_ContextAttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpecializedPermissionRequest_ContextAttributesEntry>, I>>(
    base?: I,
  ): SpecializedPermissionRequest_ContextAttributesEntry {
    return SpecializedPermissionRequest_ContextAttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpecializedPermissionRequest_ContextAttributesEntry>, I>>(
    object: I,
  ): SpecializedPermissionRequest_ContextAttributesEntry {
    const message = createBaseSpecializedPermissionRequest_ContextAttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseSpecializedPermissionResponse(): SpecializedPermissionResponse {
  return { isAllowed: false, decisionReason: "", requiredApprovalLevel: undefined, error: undefined };
}

export const SpecializedPermissionResponse = {
  encode(message: SpecializedPermissionResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isAllowed !== false) {
      writer.uint32(8).bool(message.isAllowed);
    }
    if (message.decisionReason !== "") {
      writer.uint32(18).string(message.decisionReason);
    }
    if (message.requiredApprovalLevel !== undefined) {
      writer.uint32(26).string(message.requiredApprovalLevel);
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SpecializedPermissionResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpecializedPermissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isAllowed = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.decisionReason = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.requiredApprovalLevel = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpecializedPermissionResponse {
    return {
      isAllowed: isSet(object.isAllowed) ? globalThis.Boolean(object.isAllowed) : false,
      decisionReason: isSet(object.decisionReason) ? globalThis.String(object.decisionReason) : "",
      requiredApprovalLevel: isSet(object.requiredApprovalLevel)
        ? globalThis.String(object.requiredApprovalLevel)
        : undefined,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: SpecializedPermissionResponse): unknown {
    const obj: any = {};
    if (message.isAllowed !== false) {
      obj.isAllowed = message.isAllowed;
    }
    if (message.decisionReason !== "") {
      obj.decisionReason = message.decisionReason;
    }
    if (message.requiredApprovalLevel !== undefined) {
      obj.requiredApprovalLevel = message.requiredApprovalLevel;
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpecializedPermissionResponse>, I>>(base?: I): SpecializedPermissionResponse {
    return SpecializedPermissionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpecializedPermissionResponse>, I>>(
    object: I,
  ): SpecializedPermissionResponse {
    const message = createBaseSpecializedPermissionResponse();
    message.isAllowed = object.isAllowed ?? false;
    message.decisionReason = object.decisionReason ?? "";
    message.requiredApprovalLevel = object.requiredApprovalLevel ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGetJwksPublicKeyRequest(): GetJwksPublicKeyRequest {
  return { keyId: undefined };
}

export const GetJwksPublicKeyRequest = {
  encode(message: GetJwksPublicKeyRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.keyId !== undefined) {
      writer.uint32(10).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetJwksPublicKeyRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetJwksPublicKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetJwksPublicKeyRequest {
    return { keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : undefined };
  },

  toJSON(message: GetJwksPublicKeyRequest): unknown {
    const obj: any = {};
    if (message.keyId !== undefined) {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetJwksPublicKeyRequest>, I>>(base?: I): GetJwksPublicKeyRequest {
    return GetJwksPublicKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetJwksPublicKeyRequest>, I>>(object: I): GetJwksPublicKeyRequest {
    const message = createBaseGetJwksPublicKeyRequest();
    message.keyId = object.keyId ?? undefined;
    return message;
  },
};

function createBaseGetJwksPublicKeyResponse(): GetJwksPublicKeyResponse {
  return { keyId: "", algorithm: "", publicKeyPem: "" };
}

export const GetJwksPublicKeyResponse = {
  encode(message: GetJwksPublicKeyResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.keyId !== "") {
      writer.uint32(10).string(message.keyId);
    }
    if (message.algorithm !== "") {
      writer.uint32(18).string(message.algorithm);
    }
    if (message.publicKeyPem !== "") {
      writer.uint32(26).string(message.publicKeyPem);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetJwksPublicKeyResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetJwksPublicKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.keyId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.algorithm = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.publicKeyPem = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetJwksPublicKeyResponse {
    return {
      keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : "",
      algorithm: isSet(object.algorithm) ? globalThis.String(object.algorithm) : "",
      publicKeyPem: isSet(object.publicKeyPem) ? globalThis.String(object.publicKeyPem) : "",
    };
  },

  toJSON(message: GetJwksPublicKeyResponse): unknown {
    const obj: any = {};
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.algorithm !== "") {
      obj.algorithm = message.algorithm;
    }
    if (message.publicKeyPem !== "") {
      obj.publicKeyPem = message.publicKeyPem;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetJwksPublicKeyResponse>, I>>(base?: I): GetJwksPublicKeyResponse {
    return GetJwksPublicKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetJwksPublicKeyResponse>, I>>(object: I): GetJwksPublicKeyResponse {
    const message = createBaseGetJwksPublicKeyResponse();
    message.keyId = object.keyId ?? "";
    message.algorithm = object.algorithm ?? "";
    message.publicKeyPem = object.publicKeyPem ?? "";
    return message;
  },
};

export type IdentityServiceService = typeof IdentityServiceService;
export const IdentityServiceService = {
  /**
   * Thẩm duyệt phân quyền động (ABAC/PBAC) cho các hành động có rủi ro tài chính cao
   * Ví dụ: "Kế toán duyệt Refund > 10 triệu VND", "Giám đốc duyệt chiết khấu B2B > 25%"
   */
  checkSpecializedPermission: {
    path: "/omamx.identity.v1.IdentityService/CheckSpecializedPermission",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SpecializedPermissionRequest) =>
      Buffer.from(SpecializedPermissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SpecializedPermissionRequest.decode(value),
    responseSerialize: (value: SpecializedPermissionResponse) =>
      Buffer.from(SpecializedPermissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SpecializedPermissionResponse.decode(value),
  },
  /** Cung cấp public key JWKS để API Gateway nạp vào cache cục bộ định kỳ (Local JWT Validation) */
  getJwksPublicKey: {
    path: "/omamx.identity.v1.IdentityService/GetJwksPublicKey",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetJwksPublicKeyRequest) => Buffer.from(GetJwksPublicKeyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetJwksPublicKeyRequest.decode(value),
    responseSerialize: (value: GetJwksPublicKeyResponse) =>
      Buffer.from(GetJwksPublicKeyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetJwksPublicKeyResponse.decode(value),
  },
} as const;

export interface IdentityServiceServer extends UntypedServiceImplementation {
  /**
   * Thẩm duyệt phân quyền động (ABAC/PBAC) cho các hành động có rủi ro tài chính cao
   * Ví dụ: "Kế toán duyệt Refund > 10 triệu VND", "Giám đốc duyệt chiết khấu B2B > 25%"
   */
  checkSpecializedPermission: handleUnaryCall<SpecializedPermissionRequest, SpecializedPermissionResponse>;
  /** Cung cấp public key JWKS để API Gateway nạp vào cache cục bộ định kỳ (Local JWT Validation) */
  getJwksPublicKey: handleUnaryCall<GetJwksPublicKeyRequest, GetJwksPublicKeyResponse>;
}

export interface IdentityServiceClient extends Client {
  /**
   * Thẩm duyệt phân quyền động (ABAC/PBAC) cho các hành động có rủi ro tài chính cao
   * Ví dụ: "Kế toán duyệt Refund > 10 triệu VND", "Giám đốc duyệt chiết khấu B2B > 25%"
   */
  checkSpecializedPermission(
    request: SpecializedPermissionRequest,
    callback: (error: ServiceError | null, response: SpecializedPermissionResponse) => void,
  ): ClientUnaryCall;
  checkSpecializedPermission(
    request: SpecializedPermissionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SpecializedPermissionResponse) => void,
  ): ClientUnaryCall;
  checkSpecializedPermission(
    request: SpecializedPermissionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SpecializedPermissionResponse) => void,
  ): ClientUnaryCall;
  /** Cung cấp public key JWKS để API Gateway nạp vào cache cục bộ định kỳ (Local JWT Validation) */
  getJwksPublicKey(
    request: GetJwksPublicKeyRequest,
    callback: (error: ServiceError | null, response: GetJwksPublicKeyResponse) => void,
  ): ClientUnaryCall;
  getJwksPublicKey(
    request: GetJwksPublicKeyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetJwksPublicKeyResponse) => void,
  ): ClientUnaryCall;
  getJwksPublicKey(
    request: GetJwksPublicKeyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetJwksPublicKeyResponse) => void,
  ): ClientUnaryCall;
}

export const IdentityServiceClient = makeGenericClientConstructor(
  IdentityServiceService,
  "omamx.identity.v1.IdentityService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): IdentityServiceClient;
  service: typeof IdentityServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
