$kind: http-request
method: GET
url: '{{baseUrl}}/metrics'
order: 3000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test('Expected HTTP 200', () => pm.response.to.have.status(200));
