apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
  namespace: omamx-ecommerce
data:
  HTTP_PORT: "8080"
  GRPC_PORT: "50051"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgres://omamx_user@profile-db.omamx-ecommerce.svc.cluster.local:5432/profile_db?sslmode=require"
  DB_MAX_CONNS: "50"
  DB_MIN_CONNS: "5"
  REDIS_ADDR: "profile-redis.omamx-ecommerce.svc.cluster.local:6379"
  VAULT_ADDR: "http://vault.security.svc.cluster.local:8200"
  VAULT_KEY_NAME: "profile-pii-kek"
  KAFKA_BROKERS: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TOPIC_PROFILE_EVENTS: "profile.events.v1"
  USE_VAULT_MOCK_DEV: "false"
