// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IdentityService_CheckSpecializedPermission_FullMethodName = "/omamx.identity.v1.IdentityService/CheckSpecializedPermission"
	IdentityService_GetJwksPublicKey_FullMethodName           = "/omamx.identity.v1.IdentityService/GetJwksPublicKey"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	// Thẩm duyệt phân quyền động (ABAC/PBAC) cho các hành động có rủi ro tài chính cao
	// Ví dụ: "Kế toán duyệt Refund > 10 triệu VND", "Giám đốc duyệt chiết khấu B2B > 25%"
	CheckSpecializedPermission(ctx context.Context, in *SpecializedPermissionRequest, opts ...grpc.CallOption) (*SpecializedPermissionResponse, error)
	// Cung cấp public key JWKS để API Gateway nạp vào cache cục bộ định kỳ (Local JWT Validation)
	GetJwksPublicKey(ctx context.Context, in *GetJwksPublicKeyRequest, opts ...grpc.CallOption) (*GetJwksPublicKeyResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) CheckSpecializedPermission(ctx context.Context, in *SpecializedPermissionRequest, opts ...grpc.CallOption) (*SpecializedPermissionResponse, error) {
	out := new(SpecializedPermissionResponse)
	err := c.cc.Invoke(ctx, IdentityService_CheckSpecializedPermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetJwksPublicKey(ctx context.Context, in *GetJwksPublicKeyRequest, opts ...grpc.CallOption) (*GetJwksPublicKeyResponse, error) {
	out := new(GetJwksPublicKeyResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetJwksPublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility
type IdentityServiceServer interface {
	// Thẩm duyệt phân quyền động (ABAC/PBAC) cho các hành động có rủi ro tài chính cao
	// Ví dụ: "Kế toán duyệt Refund > 10 triệu VND", "Giám đốc duyệt chiết khấu B2B > 25%"
	CheckSpecializedPermission(context.Context, *SpecializedPermissionRequest) (*SpecializedPermissionResponse, error)
	// Cung cấp public key JWKS để API Gateway nạp vào cache cục bộ định kỳ (Local JWT Validation)
	GetJwksPublicKey(context.Context, *GetJwksPublicKeyRequest) (*GetJwksPublicKeyResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityServiceServer struct {
}

func (UnimplementedIdentityServiceServer) CheckSpecializedPermission(context.Context, *SpecializedPermissionRequest) (*SpecializedPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSpecializedPermission not implemented")
}
func (UnimplementedIdentityServiceServer) GetJwksPublicKey(context.Context, *GetJwksPublicKeyRequest) (*GetJwksPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJwksPublicKey not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_CheckSpecializedPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpecializedPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CheckSpecializedPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CheckSpecializedPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CheckSpecializedPermission(ctx, req.(*SpecializedPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetJwksPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwksPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetJwksPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetJwksPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetJwksPublicKey(ctx, req.(*GetJwksPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckSpecializedPermission",
			Handler:    _IdentityService_CheckSpecializedPermission_Handler,
		},
		{
			MethodName: "GetJwksPublicKey",
			Handler:    _IdentityService_GetJwksPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/identity.proto",
}
