// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: promotion/v1/promotion.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Money } from "../../common/v1/types";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.promotion.v1";

/** Loại giảm giá của voucher */
export enum DiscountType {
  DISCOUNT_TYPE_UNSPECIFIED = 0,
  /** DISCOUNT_TYPE_FIXED_AMOUNT - Giảm số tiền cố định (Ví dụ: Giảm 30.000đ) */
  DISCOUNT_TYPE_FIXED_AMOUNT = 1,
  /** DISCOUNT_TYPE_PERCENTAGE - Giảm theo phần trăm (Ví dụ: Giảm 10%, có trần tối đa) */
  DISCOUNT_TYPE_PERCENTAGE = 2,
  /** DISCOUNT_TYPE_FREE_SHIPPING - Miễn phí vận chuyển (Trừ thẳng vào phí ship) */
  DISCOUNT_TYPE_FREE_SHIPPING = 3,
  UNRECOGNIZED = -1,
}

export function discountTypeFromJSON(object: any): DiscountType {
  switch (object) {
    case 0:
    case "DISCOUNT_TYPE_UNSPECIFIED":
      return DiscountType.DISCOUNT_TYPE_UNSPECIFIED;
    case 1:
    case "DISCOUNT_TYPE_FIXED_AMOUNT":
      return DiscountType.DISCOUNT_TYPE_FIXED_AMOUNT;
    case 2:
    case "DISCOUNT_TYPE_PERCENTAGE":
      return DiscountType.DISCOUNT_TYPE_PERCENTAGE;
    case 3:
    case "DISCOUNT_TYPE_FREE_SHIPPING":
      return DiscountType.DISCOUNT_TYPE_FREE_SHIPPING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DiscountType.UNRECOGNIZED;
  }
}

export function discountTypeToJSON(object: DiscountType): string {
  switch (object) {
    case DiscountType.DISCOUNT_TYPE_UNSPECIFIED:
      return "DISCOUNT_TYPE_UNSPECIFIED";
    case DiscountType.DISCOUNT_TYPE_FIXED_AMOUNT:
      return "DISCOUNT_TYPE_FIXED_AMOUNT";
    case DiscountType.DISCOUNT_TYPE_PERCENTAGE:
      return "DISCOUNT_TYPE_PERCENTAGE";
    case DiscountType.DISCOUNT_TYPE_FREE_SHIPPING:
      return "DISCOUNT_TYPE_FREE_SHIPPING";
    case DiscountType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Yêu cầu thẩm định và khóa voucher */
export interface ValidateAndLockVoucherRequest {
  /** Khóa chống lặp bắt buộc */
  idempotencyKey: string;
  /** Mã voucher khách hàng nhập (Ví dụ: "OMAMA_FREESHIP_30K", "TET_HUE_GIFT_50K") */
  voucherCode: string;
  /** Mã đơn hàng đang thực hiện checkout */
  orderId: string;
  /** Mã khách hàng áp dụng voucher */
  customerId: string;
  /** Tổng tiền hàng trước giảm giá */
  orderSubtotal?:
    | Money
    | undefined;
  /** Thời gian khóa giữ chỗ voucher (Mặc định: 15 phút, khớp với TTL của khóa kho) */
  ttlMinutes: number;
}

/** Phản hồi kết quả thẩm định và khóa voucher */
export interface ValidateAndLockVoucherResponse {
  /** Trạng thái hợp lệ: true nếu thỏa mãn toàn bộ điều kiện */
  isValid: boolean;
  /** Số tiền được giảm giá thực tế (Bắt buộc dùng optional) */
  discountAmount?:
    | Money
    | undefined;
  /** Loại hình giảm giá */
  discountType: DiscountType;
  /** Mã khóa giữ voucher trong cơ sở dữ liệu (UUID) */
  voucherLockId?:
    | string
    | undefined;
  /** Thời điểm khóa voucher hết hiệu lực */
  expiresAt?:
    | Date
    | undefined;
  /** Chi tiết lỗi nếu voucher không hợp lệ (Hết hạn, chưa đủ tiền tối thiểu, v.v.) */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu mở khóa voucher khi Saga kích hoạt đền bù */
export interface ReleaseVoucherRequest {
  idempotencyKey: string;
  voucherCode: string;
  voucherLockId: string;
  orderId: string;
  releaseReason: string;
}

/** Phản hồi mở khóa voucher */
export interface ReleaseVoucherResponse {
  isReleased: boolean;
  message: string;
}

/** Yêu cầu tính toán giảm giá thử nghiệm */
export interface CalculateDiscountRequest {
  voucherCode: string;
  customerId: string;
  orderSubtotal?: Money | undefined;
}

/** Phản hồi tính toán giảm giá thử nghiệm */
export interface CalculateDiscountResponse {
  isApplicable: boolean;
  estimatedDiscount?: Money | undefined;
  description: string;
}

function createBaseValidateAndLockVoucherRequest(): ValidateAndLockVoucherRequest {
  return { idempotencyKey: "", voucherCode: "", orderId: "", customerId: "", orderSubtotal: undefined, ttlMinutes: 0 };
}

export const ValidateAndLockVoucherRequest = {
  encode(message: ValidateAndLockVoucherRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.voucherCode !== "") {
      writer.uint32(18).string(message.voucherCode);
    }
    if (message.orderId !== "") {
      writer.uint32(26).string(message.orderId);
    }
    if (message.customerId !== "") {
      writer.uint32(34).string(message.customerId);
    }
    if (message.orderSubtotal !== undefined) {
      Money.encode(message.orderSubtotal, writer.uint32(42).fork()).ldelim();
    }
    if (message.ttlMinutes !== 0) {
      writer.uint32(48).int32(message.ttlMinutes);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ValidateAndLockVoucherRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateAndLockVoucherRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.voucherCode = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.customerId = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.orderSubtotal = Money.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.ttlMinutes = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateAndLockVoucherRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      voucherCode: isSet(object.voucherCode) ? globalThis.String(object.voucherCode) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
      orderSubtotal: isSet(object.orderSubtotal) ? Money.fromJSON(object.orderSubtotal) : undefined,
      ttlMinutes: isSet(object.ttlMinutes) ? globalThis.Number(object.ttlMinutes) : 0,
    };
  },

  toJSON(message: ValidateAndLockVoucherRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.voucherCode !== "") {
      obj.voucherCode = message.voucherCode;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    if (message.orderSubtotal !== undefined) {
      obj.orderSubtotal = Money.toJSON(message.orderSubtotal);
    }
    if (message.ttlMinutes !== 0) {
      obj.ttlMinutes = Math.round(message.ttlMinutes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateAndLockVoucherRequest>, I>>(base?: I): ValidateAndLockVoucherRequest {
    return ValidateAndLockVoucherRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateAndLockVoucherRequest>, I>>(
    object: I,
  ): ValidateAndLockVoucherRequest {
    const message = createBaseValidateAndLockVoucherRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.voucherCode = object.voucherCode ?? "";
    message.orderId = object.orderId ?? "";
    message.customerId = object.customerId ?? "";
    message.orderSubtotal = (object.orderSubtotal !== undefined && object.orderSubtotal !== null)
      ? Money.fromPartial(object.orderSubtotal)
      : undefined;
    message.ttlMinutes = object.ttlMinutes ?? 0;
    return message;
  },
};

function createBaseValidateAndLockVoucherResponse(): ValidateAndLockVoucherResponse {
  return {
    isValid: false,
    discountAmount: undefined,
    discountType: 0,
    voucherLockId: undefined,
    expiresAt: undefined,
    error: undefined,
  };
}

export const ValidateAndLockVoucherResponse = {
  encode(message: ValidateAndLockVoucherResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isValid !== false) {
      writer.uint32(8).bool(message.isValid);
    }
    if (message.discountAmount !== undefined) {
      Money.encode(message.discountAmount, writer.uint32(18).fork()).ldelim();
    }
    if (message.discountType !== 0) {
      writer.uint32(24).int32(message.discountType);
    }
    if (message.voucherLockId !== undefined) {
      writer.uint32(34).string(message.voucherLockId);
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(42).fork()).ldelim();
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ValidateAndLockVoucherResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateAndLockVoucherResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.discountAmount = Money.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.discountType = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.voucherLockId = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateAndLockVoucherResponse {
    return {
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
      discountAmount: isSet(object.discountAmount) ? Money.fromJSON(object.discountAmount) : undefined,
      discountType: isSet(object.discountType) ? discountTypeFromJSON(object.discountType) : 0,
      voucherLockId: isSet(object.voucherLockId) ? globalThis.String(object.voucherLockId) : undefined,
      expiresAt: isSet(object.expiresAt) ? fromJsonTimestamp(object.expiresAt) : undefined,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ValidateAndLockVoucherResponse): unknown {
    const obj: any = {};
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.discountAmount !== undefined) {
      obj.discountAmount = Money.toJSON(message.discountAmount);
    }
    if (message.discountType !== 0) {
      obj.discountType = discountTypeToJSON(message.discountType);
    }
    if (message.voucherLockId !== undefined) {
      obj.voucherLockId = message.voucherLockId;
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateAndLockVoucherResponse>, I>>(base?: I): ValidateAndLockVoucherResponse {
    return ValidateAndLockVoucherResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateAndLockVoucherResponse>, I>>(
    object: I,
  ): ValidateAndLockVoucherResponse {
    const message = createBaseValidateAndLockVoucherResponse();
    message.isValid = object.isValid ?? false;
    message.discountAmount = (object.discountAmount !== undefined && object.discountAmount !== null)
      ? Money.fromPartial(object.discountAmount)
      : undefined;
    message.discountType = object.discountType ?? 0;
    message.voucherLockId = object.voucherLockId ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseReleaseVoucherRequest(): ReleaseVoucherRequest {
  return { idempotencyKey: "", voucherCode: "", voucherLockId: "", orderId: "", releaseReason: "" };
}

export const ReleaseVoucherRequest = {
  encode(message: ReleaseVoucherRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.voucherCode !== "") {
      writer.uint32(18).string(message.voucherCode);
    }
    if (message.voucherLockId !== "") {
      writer.uint32(26).string(message.voucherLockId);
    }
    if (message.orderId !== "") {
      writer.uint32(34).string(message.orderId);
    }
    if (message.releaseReason !== "") {
      writer.uint32(42).string(message.releaseReason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReleaseVoucherRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReleaseVoucherRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.voucherCode = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.voucherLockId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.releaseReason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReleaseVoucherRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      voucherCode: isSet(object.voucherCode) ? globalThis.String(object.voucherCode) : "",
      voucherLockId: isSet(object.voucherLockId) ? globalThis.String(object.voucherLockId) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      releaseReason: isSet(object.releaseReason) ? globalThis.String(object.releaseReason) : "",
    };
  },

  toJSON(message: ReleaseVoucherRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.voucherCode !== "") {
      obj.voucherCode = message.voucherCode;
    }
    if (message.voucherLockId !== "") {
      obj.voucherLockId = message.voucherLockId;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.releaseReason !== "") {
      obj.releaseReason = message.releaseReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReleaseVoucherRequest>, I>>(base?: I): ReleaseVoucherRequest {
    return ReleaseVoucherRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReleaseVoucherRequest>, I>>(object: I): ReleaseVoucherRequest {
    const message = createBaseReleaseVoucherRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.voucherCode = object.voucherCode ?? "";
    message.voucherLockId = object.voucherLockId ?? "";
    message.orderId = object.orderId ?? "";
    message.releaseReason = object.releaseReason ?? "";
    return message;
  },
};

function createBaseReleaseVoucherResponse(): ReleaseVoucherResponse {
  return { isReleased: false, message: "" };
}

export const ReleaseVoucherResponse = {
  encode(message: ReleaseVoucherResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isReleased !== false) {
      writer.uint32(8).bool(message.isReleased);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReleaseVoucherResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReleaseVoucherResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isReleased = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReleaseVoucherResponse {
    return {
      isReleased: isSet(object.isReleased) ? globalThis.Boolean(object.isReleased) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ReleaseVoucherResponse): unknown {
    const obj: any = {};
    if (message.isReleased !== false) {
      obj.isReleased = message.isReleased;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReleaseVoucherResponse>, I>>(base?: I): ReleaseVoucherResponse {
    return ReleaseVoucherResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReleaseVoucherResponse>, I>>(object: I): ReleaseVoucherResponse {
    const message = createBaseReleaseVoucherResponse();
    message.isReleased = object.isReleased ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseCalculateDiscountRequest(): CalculateDiscountRequest {
  return { voucherCode: "", customerId: "", orderSubtotal: undefined };
}

export const CalculateDiscountRequest = {
  encode(message: CalculateDiscountRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.voucherCode !== "") {
      writer.uint32(10).string(message.voucherCode);
    }
    if (message.customerId !== "") {
      writer.uint32(18).string(message.customerId);
    }
    if (message.orderSubtotal !== undefined) {
      Money.encode(message.orderSubtotal, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CalculateDiscountRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateDiscountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.voucherCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.customerId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.orderSubtotal = Money.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateDiscountRequest {
    return {
      voucherCode: isSet(object.voucherCode) ? globalThis.String(object.voucherCode) : "",
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
      orderSubtotal: isSet(object.orderSubtotal) ? Money.fromJSON(object.orderSubtotal) : undefined,
    };
  },

  toJSON(message: CalculateDiscountRequest): unknown {
    const obj: any = {};
    if (message.voucherCode !== "") {
      obj.voucherCode = message.voucherCode;
    }
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    if (message.orderSubtotal !== undefined) {
      obj.orderSubtotal = Money.toJSON(message.orderSubtotal);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateDiscountRequest>, I>>(base?: I): CalculateDiscountRequest {
    return CalculateDiscountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateDiscountRequest>, I>>(object: I): CalculateDiscountRequest {
    const message = createBaseCalculateDiscountRequest();
    message.voucherCode = object.voucherCode ?? "";
    message.customerId = object.customerId ?? "";
    message.orderSubtotal = (object.orderSubtotal !== undefined && object.orderSubtotal !== null)
      ? Money.fromPartial(object.orderSubtotal)
      : undefined;
    return message;
  },
};

function createBaseCalculateDiscountResponse(): CalculateDiscountResponse {
  return { isApplicable: false, estimatedDiscount: undefined, description: "" };
}

export const CalculateDiscountResponse = {
  encode(message: CalculateDiscountResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isApplicable !== false) {
      writer.uint32(8).bool(message.isApplicable);
    }
    if (message.estimatedDiscount !== undefined) {
      Money.encode(message.estimatedDiscount, writer.uint32(18).fork()).ldelim();
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CalculateDiscountResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateDiscountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isApplicable = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.estimatedDiscount = Money.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateDiscountResponse {
    return {
      isApplicable: isSet(object.isApplicable) ? globalThis.Boolean(object.isApplicable) : false,
      estimatedDiscount: isSet(object.estimatedDiscount) ? Money.fromJSON(object.estimatedDiscount) : undefined,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: CalculateDiscountResponse): unknown {
    const obj: any = {};
    if (message.isApplicable !== false) {
      obj.isApplicable = message.isApplicable;
    }
    if (message.estimatedDiscount !== undefined) {
      obj.estimatedDiscount = Money.toJSON(message.estimatedDiscount);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateDiscountResponse>, I>>(base?: I): CalculateDiscountResponse {
    return CalculateDiscountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateDiscountResponse>, I>>(object: I): CalculateDiscountResponse {
    const message = createBaseCalculateDiscountResponse();
    message.isApplicable = object.isApplicable ?? false;
    message.estimatedDiscount = (object.estimatedDiscount !== undefined && object.estimatedDiscount !== null)
      ? Money.fromPartial(object.estimatedDiscount)
      : undefined;
    message.description = object.description ?? "";
    return message;
  },
};

export type PromotionServiceService = typeof PromotionServiceService;
export const PromotionServiceService = {
  /** Thẩm định điều kiện áp dụng và tạm khóa 1 lượt dùng voucher (Critical Path < 20ms) */
  validateAndLockVoucher: {
    path: "/omamx.promotion.v1.PromotionService/ValidateAndLockVoucher",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateAndLockVoucherRequest) =>
      Buffer.from(ValidateAndLockVoucherRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ValidateAndLockVoucherRequest.decode(value),
    responseSerialize: (value: ValidateAndLockVoucherResponse) =>
      Buffer.from(ValidateAndLockVoucherResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ValidateAndLockVoucherResponse.decode(value),
  },
  /** Mở khóa hoàn trả lượt dùng voucher khi đơn hàng bị hủy hoặc hết hạn thanh toán */
  releaseVoucher: {
    path: "/omamx.promotion.v1.PromotionService/ReleaseVoucher",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReleaseVoucherRequest) => Buffer.from(ReleaseVoucherRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReleaseVoucherRequest.decode(value),
    responseSerialize: (value: ReleaseVoucherResponse) => Buffer.from(ReleaseVoucherResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ReleaseVoucherResponse.decode(value),
  },
  /** Tính toán nhanh số tiền giảm giá dự kiến mà không khóa voucher (Dùng khi xem giỏ hàng) */
  calculateDiscount: {
    path: "/omamx.promotion.v1.PromotionService/CalculateDiscount",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CalculateDiscountRequest) => Buffer.from(CalculateDiscountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CalculateDiscountRequest.decode(value),
    responseSerialize: (value: CalculateDiscountResponse) =>
      Buffer.from(CalculateDiscountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CalculateDiscountResponse.decode(value),
  },
} as const;

export interface PromotionServiceServer extends UntypedServiceImplementation {
  /** Thẩm định điều kiện áp dụng và tạm khóa 1 lượt dùng voucher (Critical Path < 20ms) */
  validateAndLockVoucher: handleUnaryCall<ValidateAndLockVoucherRequest, ValidateAndLockVoucherResponse>;
  /** Mở khóa hoàn trả lượt dùng voucher khi đơn hàng bị hủy hoặc hết hạn thanh toán */
  releaseVoucher: handleUnaryCall<ReleaseVoucherRequest, ReleaseVoucherResponse>;
  /** Tính toán nhanh số tiền giảm giá dự kiến mà không khóa voucher (Dùng khi xem giỏ hàng) */
  calculateDiscount: handleUnaryCall<CalculateDiscountRequest, CalculateDiscountResponse>;
}

export interface PromotionServiceClient extends Client {
  /** Thẩm định điều kiện áp dụng và tạm khóa 1 lượt dùng voucher (Critical Path < 20ms) */
  validateAndLockVoucher(
    request: ValidateAndLockVoucherRequest,
    callback: (error: ServiceError | null, response: ValidateAndLockVoucherResponse) => void,
  ): ClientUnaryCall;
  validateAndLockVoucher(
    request: ValidateAndLockVoucherRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ValidateAndLockVoucherResponse) => void,
  ): ClientUnaryCall;
  validateAndLockVoucher(
    request: ValidateAndLockVoucherRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ValidateAndLockVoucherResponse) => void,
  ): ClientUnaryCall;
  /** Mở khóa hoàn trả lượt dùng voucher khi đơn hàng bị hủy hoặc hết hạn thanh toán */
  releaseVoucher(
    request: ReleaseVoucherRequest,
    callback: (error: ServiceError | null, response: ReleaseVoucherResponse) => void,
  ): ClientUnaryCall;
  releaseVoucher(
    request: ReleaseVoucherRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReleaseVoucherResponse) => void,
  ): ClientUnaryCall;
  releaseVoucher(
    request: ReleaseVoucherRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReleaseVoucherResponse) => void,
  ): ClientUnaryCall;
  /** Tính toán nhanh số tiền giảm giá dự kiến mà không khóa voucher (Dùng khi xem giỏ hàng) */
  calculateDiscount(
    request: CalculateDiscountRequest,
    callback: (error: ServiceError | null, response: CalculateDiscountResponse) => void,
  ): ClientUnaryCall;
  calculateDiscount(
    request: CalculateDiscountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CalculateDiscountResponse) => void,
  ): ClientUnaryCall;
  calculateDiscount(
    request: CalculateDiscountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CalculateDiscountResponse) => void,
  ): ClientUnaryCall;
}

export const PromotionServiceClient = makeGenericClientConstructor(
  PromotionServiceService,
  "omamx.promotion.v1.PromotionService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PromotionServiceClient;
  service: typeof PromotionServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
