// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: fulfillment/v1/fulfillment.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.fulfillment.v1";

/** Yêu cầu lấy link video đóng gói niêm phong */
export interface GetPackingVideoUrlRequest {
  /** Mã đơn hàng cần tra cứu */
  orderId: string;
  /** Người thực hiện yêu cầu (Chỉ CSKH, Thủ kho hoặc chính Chủ sở hữu đơn hàng) */
  requestingUserId: string;
  /** Vai trò của người yêu cầu ("CUSTOMER", "CUSTOMER_SERVICE", "WAREHOUSE_MANAGER") */
  userRole: string;
}

/** Phản hồi link video đóng gói */
export interface GetPackingVideoUrlResponse {
  /** Đơn hàng có video đóng gói hợp lệ hay không */
  hasVideo: boolean;
  /** Đường link Pre-signed S3 an toàn có thời hạn (Hết hạn sau 15 phút - NFR-09) */
  presignedVideoUrl?:
    | string
    | undefined;
  /** Thời điểm đường link hết hạn */
  expiresAt?:
    | Date
    | undefined;
  /** Mã số tem Seal O Mạ dán trên kiện hàng (Ví dụ: "SEAL-OMA-20261015-8899") */
  sealCode?:
    | string
    | undefined;
  /** Mã băm SHA-256 toàn vẹn của tệp video trên S3 (Chống sửa video giả mạo) */
  videoChecksumSha256?:
    | string
    | undefined;
  /** Chi tiết lỗi nếu không tìm thấy video hoặc không đủ quyền truy cập */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu xác nhận hoàn tất đóng gói kẹo */
export interface SubmitPackingEvidenceRequest {
  /** Khóa chống lặp giao dịch */
  idempotencyKey: string;
  /** Mã đơn hàng */
  orderId: string;
  /** Mã nhân viên/thợ xưởng Huế đóng gói */
  packerStaffId: string;
  /** Mã số tem Seal O Mạ vừa dán niêm phong lên hộp */
  sealCode: string;
  /** S3 Object Key nơi video đóng gói đã được tải lên AWS S3 */
  s3VideoObjectKey: string;
  /** Mã băm SHA-256 toàn vẹn của video */
  videoChecksumSha256: string;
  /** Danh sách các mã lô hàng FEFO đã quét barcode thực tế khi bốc kẹo */
  scannedBatchCodes: string[];
}

/** Phản hồi xác nhận hoàn tất đóng gói */
export interface SubmitPackingEvidenceResponse {
  isConfirmed: boolean;
  fulfillmentTaskId: string;
  packedAt?: Date | undefined;
}

function createBaseGetPackingVideoUrlRequest(): GetPackingVideoUrlRequest {
  return { orderId: "", requestingUserId: "", userRole: "" };
}

export const GetPackingVideoUrlRequest = {
  encode(message: GetPackingVideoUrlRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.requestingUserId !== "") {
      writer.uint32(18).string(message.requestingUserId);
    }
    if (message.userRole !== "") {
      writer.uint32(26).string(message.userRole);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPackingVideoUrlRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPackingVideoUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.requestingUserId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.userRole = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPackingVideoUrlRequest {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      requestingUserId: isSet(object.requestingUserId) ? globalThis.String(object.requestingUserId) : "",
      userRole: isSet(object.userRole) ? globalThis.String(object.userRole) : "",
    };
  },

  toJSON(message: GetPackingVideoUrlRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.requestingUserId !== "") {
      obj.requestingUserId = message.requestingUserId;
    }
    if (message.userRole !== "") {
      obj.userRole = message.userRole;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPackingVideoUrlRequest>, I>>(base?: I): GetPackingVideoUrlRequest {
    return GetPackingVideoUrlRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPackingVideoUrlRequest>, I>>(object: I): GetPackingVideoUrlRequest {
    const message = createBaseGetPackingVideoUrlRequest();
    message.orderId = object.orderId ?? "";
    message.requestingUserId = object.requestingUserId ?? "";
    message.userRole = object.userRole ?? "";
    return message;
  },
};

function createBaseGetPackingVideoUrlResponse(): GetPackingVideoUrlResponse {
  return {
    hasVideo: false,
    presignedVideoUrl: undefined,
    expiresAt: undefined,
    sealCode: undefined,
    videoChecksumSha256: undefined,
    error: undefined,
  };
}

export const GetPackingVideoUrlResponse = {
  encode(message: GetPackingVideoUrlResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.hasVideo !== false) {
      writer.uint32(8).bool(message.hasVideo);
    }
    if (message.presignedVideoUrl !== undefined) {
      writer.uint32(18).string(message.presignedVideoUrl);
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(26).fork()).ldelim();
    }
    if (message.sealCode !== undefined) {
      writer.uint32(34).string(message.sealCode);
    }
    if (message.videoChecksumSha256 !== undefined) {
      writer.uint32(42).string(message.videoChecksumSha256);
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPackingVideoUrlResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPackingVideoUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.hasVideo = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.presignedVideoUrl = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.sealCode = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.videoChecksumSha256 = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPackingVideoUrlResponse {
    return {
      hasVideo: isSet(object.hasVideo) ? globalThis.Boolean(object.hasVideo) : false,
      presignedVideoUrl: isSet(object.presignedVideoUrl) ? globalThis.String(object.presignedVideoUrl) : undefined,
      expiresAt: isSet(object.expiresAt) ? fromJsonTimestamp(object.expiresAt) : undefined,
      sealCode: isSet(object.sealCode) ? globalThis.String(object.sealCode) : undefined,
      videoChecksumSha256: isSet(object.videoChecksumSha256)
        ? globalThis.String(object.videoChecksumSha256)
        : undefined,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GetPackingVideoUrlResponse): unknown {
    const obj: any = {};
    if (message.hasVideo !== false) {
      obj.hasVideo = message.hasVideo;
    }
    if (message.presignedVideoUrl !== undefined) {
      obj.presignedVideoUrl = message.presignedVideoUrl;
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.sealCode !== undefined) {
      obj.sealCode = message.sealCode;
    }
    if (message.videoChecksumSha256 !== undefined) {
      obj.videoChecksumSha256 = message.videoChecksumSha256;
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPackingVideoUrlResponse>, I>>(base?: I): GetPackingVideoUrlResponse {
    return GetPackingVideoUrlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPackingVideoUrlResponse>, I>>(object: I): GetPackingVideoUrlResponse {
    const message = createBaseGetPackingVideoUrlResponse();
    message.hasVideo = object.hasVideo ?? false;
    message.presignedVideoUrl = object.presignedVideoUrl ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.sealCode = object.sealCode ?? undefined;
    message.videoChecksumSha256 = object.videoChecksumSha256 ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseSubmitPackingEvidenceRequest(): SubmitPackingEvidenceRequest {
  return {
    idempotencyKey: "",
    orderId: "",
    packerStaffId: "",
    sealCode: "",
    s3VideoObjectKey: "",
    videoChecksumSha256: "",
    scannedBatchCodes: [],
  };
}

export const SubmitPackingEvidenceRequest = {
  encode(message: SubmitPackingEvidenceRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.packerStaffId !== "") {
      writer.uint32(26).string(message.packerStaffId);
    }
    if (message.sealCode !== "") {
      writer.uint32(34).string(message.sealCode);
    }
    if (message.s3VideoObjectKey !== "") {
      writer.uint32(42).string(message.s3VideoObjectKey);
    }
    if (message.videoChecksumSha256 !== "") {
      writer.uint32(50).string(message.videoChecksumSha256);
    }
    for (const v of message.scannedBatchCodes) {
      writer.uint32(58).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SubmitPackingEvidenceRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitPackingEvidenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.packerStaffId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.sealCode = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.s3VideoObjectKey = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.videoChecksumSha256 = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.scannedBatchCodes.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitPackingEvidenceRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      packerStaffId: isSet(object.packerStaffId) ? globalThis.String(object.packerStaffId) : "",
      sealCode: isSet(object.sealCode) ? globalThis.String(object.sealCode) : "",
      s3VideoObjectKey: isSet(object.s3VideoObjectKey) ? globalThis.String(object.s3VideoObjectKey) : "",
      videoChecksumSha256: isSet(object.videoChecksumSha256) ? globalThis.String(object.videoChecksumSha256) : "",
      scannedBatchCodes: globalThis.Array.isArray(object?.scannedBatchCodes)
        ? object.scannedBatchCodes.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: SubmitPackingEvidenceRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.packerStaffId !== "") {
      obj.packerStaffId = message.packerStaffId;
    }
    if (message.sealCode !== "") {
      obj.sealCode = message.sealCode;
    }
    if (message.s3VideoObjectKey !== "") {
      obj.s3VideoObjectKey = message.s3VideoObjectKey;
    }
    if (message.videoChecksumSha256 !== "") {
      obj.videoChecksumSha256 = message.videoChecksumSha256;
    }
    if (message.scannedBatchCodes?.length) {
      obj.scannedBatchCodes = message.scannedBatchCodes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitPackingEvidenceRequest>, I>>(base?: I): SubmitPackingEvidenceRequest {
    return SubmitPackingEvidenceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitPackingEvidenceRequest>, I>>(object: I): SubmitPackingEvidenceRequest {
    const message = createBaseSubmitPackingEvidenceRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.orderId = object.orderId ?? "";
    message.packerStaffId = object.packerStaffId ?? "";
    message.sealCode = object.sealCode ?? "";
    message.s3VideoObjectKey = object.s3VideoObjectKey ?? "";
    message.videoChecksumSha256 = object.videoChecksumSha256 ?? "";
    message.scannedBatchCodes = object.scannedBatchCodes?.map((e) => e) || [];
    return message;
  },
};

function createBaseSubmitPackingEvidenceResponse(): SubmitPackingEvidenceResponse {
  return { isConfirmed: false, fulfillmentTaskId: "", packedAt: undefined };
}

export const SubmitPackingEvidenceResponse = {
  encode(message: SubmitPackingEvidenceResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isConfirmed !== false) {
      writer.uint32(8).bool(message.isConfirmed);
    }
    if (message.fulfillmentTaskId !== "") {
      writer.uint32(18).string(message.fulfillmentTaskId);
    }
    if (message.packedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.packedAt), writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SubmitPackingEvidenceResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitPackingEvidenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isConfirmed = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.fulfillmentTaskId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.packedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitPackingEvidenceResponse {
    return {
      isConfirmed: isSet(object.isConfirmed) ? globalThis.Boolean(object.isConfirmed) : false,
      fulfillmentTaskId: isSet(object.fulfillmentTaskId) ? globalThis.String(object.fulfillmentTaskId) : "",
      packedAt: isSet(object.packedAt) ? fromJsonTimestamp(object.packedAt) : undefined,
    };
  },

  toJSON(message: SubmitPackingEvidenceResponse): unknown {
    const obj: any = {};
    if (message.isConfirmed !== false) {
      obj.isConfirmed = message.isConfirmed;
    }
    if (message.fulfillmentTaskId !== "") {
      obj.fulfillmentTaskId = message.fulfillmentTaskId;
    }
    if (message.packedAt !== undefined) {
      obj.packedAt = message.packedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitPackingEvidenceResponse>, I>>(base?: I): SubmitPackingEvidenceResponse {
    return SubmitPackingEvidenceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitPackingEvidenceResponse>, I>>(
    object: I,
  ): SubmitPackingEvidenceResponse {
    const message = createBaseSubmitPackingEvidenceResponse();
    message.isConfirmed = object.isConfirmed ?? false;
    message.fulfillmentTaskId = object.fulfillmentTaskId ?? "";
    message.packedAt = object.packedAt ?? undefined;
    return message;
  },
};

export type FulfillmentServiceService = typeof FulfillmentServiceService;
export const FulfillmentServiceService = {
  /** Lấy Pre-signed S3 URL video niêm phong tem Seal O Mạ phục vụ đối soát khiếu nại (NFR-09) */
  getPackingVideoUrl: {
    path: "/omamx.fulfillment.v1.FulfillmentService/GetPackingVideoUrl",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetPackingVideoUrlRequest) =>
      Buffer.from(GetPackingVideoUrlRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetPackingVideoUrlRequest.decode(value),
    responseSerialize: (value: GetPackingVideoUrlResponse) =>
      Buffer.from(GetPackingVideoUrlResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetPackingVideoUrlResponse.decode(value),
  },
  /** Thợ xưởng quét mã vạch lô hàng FEFO và nạp video niêm phong tem Seal hoàn tất đóng gói */
  submitPackingEvidence: {
    path: "/omamx.fulfillment.v1.FulfillmentService/SubmitPackingEvidence",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SubmitPackingEvidenceRequest) =>
      Buffer.from(SubmitPackingEvidenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SubmitPackingEvidenceRequest.decode(value),
    responseSerialize: (value: SubmitPackingEvidenceResponse) =>
      Buffer.from(SubmitPackingEvidenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SubmitPackingEvidenceResponse.decode(value),
  },
} as const;

export interface FulfillmentServiceServer extends UntypedServiceImplementation {
  /** Lấy Pre-signed S3 URL video niêm phong tem Seal O Mạ phục vụ đối soát khiếu nại (NFR-09) */
  getPackingVideoUrl: handleUnaryCall<GetPackingVideoUrlRequest, GetPackingVideoUrlResponse>;
  /** Thợ xưởng quét mã vạch lô hàng FEFO và nạp video niêm phong tem Seal hoàn tất đóng gói */
  submitPackingEvidence: handleUnaryCall<SubmitPackingEvidenceRequest, SubmitPackingEvidenceResponse>;
}

export interface FulfillmentServiceClient extends Client {
  /** Lấy Pre-signed S3 URL video niêm phong tem Seal O Mạ phục vụ đối soát khiếu nại (NFR-09) */
  getPackingVideoUrl(
    request: GetPackingVideoUrlRequest,
    callback: (error: ServiceError | null, response: GetPackingVideoUrlResponse) => void,
  ): ClientUnaryCall;
  getPackingVideoUrl(
    request: GetPackingVideoUrlRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetPackingVideoUrlResponse) => void,
  ): ClientUnaryCall;
  getPackingVideoUrl(
    request: GetPackingVideoUrlRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetPackingVideoUrlResponse) => void,
  ): ClientUnaryCall;
  /** Thợ xưởng quét mã vạch lô hàng FEFO và nạp video niêm phong tem Seal hoàn tất đóng gói */
  submitPackingEvidence(
    request: SubmitPackingEvidenceRequest,
    callback: (error: ServiceError | null, response: SubmitPackingEvidenceResponse) => void,
  ): ClientUnaryCall;
  submitPackingEvidence(
    request: SubmitPackingEvidenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubmitPackingEvidenceResponse) => void,
  ): ClientUnaryCall;
  submitPackingEvidence(
    request: SubmitPackingEvidenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubmitPackingEvidenceResponse) => void,
  ): ClientUnaryCall;
}

export const FulfillmentServiceClient = makeGenericClientConstructor(
  FulfillmentServiceService,
  "omamx.fulfillment.v1.FulfillmentService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): FulfillmentServiceClient;
  service: typeof FulfillmentServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
