// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: promotion/v1/promotion.proto

package promotionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PromotionService_ValidateAndLockVoucher_FullMethodName = "/omamx.promotion.v1.PromotionService/ValidateAndLockVoucher"
	PromotionService_ReleaseVoucher_FullMethodName         = "/omamx.promotion.v1.PromotionService/ReleaseVoucher"
	PromotionService_CalculateDiscount_FullMethodName      = "/omamx.promotion.v1.PromotionService/CalculateDiscount"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionServiceClient interface {
	// Thẩm định điều kiện áp dụng và tạm khóa 1 lượt dùng voucher (Critical Path < 20ms)
	ValidateAndLockVoucher(ctx context.Context, in *ValidateAndLockVoucherRequest, opts ...grpc.CallOption) (*ValidateAndLockVoucherResponse, error)
	// Mở khóa hoàn trả lượt dùng voucher khi đơn hàng bị hủy hoặc hết hạn thanh toán
	ReleaseVoucher(ctx context.Context, in *ReleaseVoucherRequest, opts ...grpc.CallOption) (*ReleaseVoucherResponse, error)
	// Tính toán nhanh số tiền giảm giá dự kiến mà không khóa voucher (Dùng khi xem giỏ hàng)
	CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) ValidateAndLockVoucher(ctx context.Context, in *ValidateAndLockVoucherRequest, opts ...grpc.CallOption) (*ValidateAndLockVoucherResponse, error) {
	out := new(ValidateAndLockVoucherResponse)
	err := c.cc.Invoke(ctx, PromotionService_ValidateAndLockVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) ReleaseVoucher(ctx context.Context, in *ReleaseVoucherRequest, opts ...grpc.CallOption) (*ReleaseVoucherResponse, error) {
	out := new(ReleaseVoucherResponse)
	err := c.cc.Invoke(ctx, PromotionService_ReleaseVoucher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountRequest, opts ...grpc.CallOption) (*CalculateDiscountResponse, error) {
	out := new(CalculateDiscountResponse)
	err := c.cc.Invoke(ctx, PromotionService_CalculateDiscount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility
type PromotionServiceServer interface {
	// Thẩm định điều kiện áp dụng và tạm khóa 1 lượt dùng voucher (Critical Path < 20ms)
	ValidateAndLockVoucher(context.Context, *ValidateAndLockVoucherRequest) (*ValidateAndLockVoucherResponse, error)
	// Mở khóa hoàn trả lượt dùng voucher khi đơn hàng bị hủy hoặc hết hạn thanh toán
	ReleaseVoucher(context.Context, *ReleaseVoucherRequest) (*ReleaseVoucherResponse, error)
	// Tính toán nhanh số tiền giảm giá dự kiến mà không khóa voucher (Dùng khi xem giỏ hàng)
	CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPromotionServiceServer struct {
}

func (UnimplementedPromotionServiceServer) ValidateAndLockVoucher(context.Context, *ValidateAndLockVoucherRequest) (*ValidateAndLockVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAndLockVoucher not implemented")
}
func (UnimplementedPromotionServiceServer) ReleaseVoucher(context.Context, *ReleaseVoucherRequest) (*ReleaseVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseVoucher not implemented")
}
func (UnimplementedPromotionServiceServer) CalculateDiscount(context.Context, *CalculateDiscountRequest) (*CalculateDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_ValidateAndLockVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAndLockVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ValidateAndLockVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ValidateAndLockVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ValidateAndLockVoucher(ctx, req.(*ValidateAndLockVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_ReleaseVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ReleaseVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ReleaseVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ReleaseVoucher(ctx, req.(*ReleaseVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_CalculateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).CalculateDiscount(ctx, req.(*CalculateDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.promotion.v1.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAndLockVoucher",
			Handler:    _PromotionService_ValidateAndLockVoucher_Handler,
		},
		{
			MethodName: "ReleaseVoucher",
			Handler:    _PromotionService_ReleaseVoucher_Handler,
		},
		{
			MethodName: "CalculateDiscount",
			Handler:    _PromotionService_CalculateDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion/v1/promotion.proto",
}
