"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { AdminPermissionDetail, AdminPermissionList, AdminPermissionStatus, AdminPermissionSummary } from "@/lib/access/types";
import { AdminAccessApiError } from "@/lib/access/types";
import { adminAccessService } from "@/services/admin-access-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
function PermissionStatus({ item }: { item: Pick<AdminPermissionSummary, "status" | "statusLabel"> }) { return <span className={`admin-status permission-${item.status.toLowerCase()}`}>{item.statusLabel}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function PermissionCatalogWorkspace() {
  const [data, setData] = useState<AdminPermissionList | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [status, setStatus] = useState<"ALL" | AdminPermissionStatus>("ALL"); const [query, setQuery] = useState(""); const [resource, setResource] = useState("ALL"); const [kind, setKind] = useState("ALL"); const [menuCode, setMenuCode] = useState("");
  const [selected, setSelected] = useState<AdminPermissionSummary | null>(null); const [detail, setDetail] = useState<AdminPermissionDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminAccessService.permissions()); } catch (cause) { setLoadError(cause instanceof AdminAccessApiError ? cause.message : "Không thể tải danh mục Permission."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("vi"); return data?.items.filter((item) => (status === "ALL" || item.status === status) && (resource === "ALL" || item.resource === resource) && (kind === "ALL" || item.kind === kind) && (!needle || [item.permissionCode, item.permissionName, item.description, item.action, item.resource].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? []; }, [data, kind, query, resource, status]);
  async function openDetail(item: AdminPermissionSummary) { setMenuCode(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const result = await adminAccessService.permission(item.permissionCode); setDetail({ ...result, ...item }); } catch (cause) { setDetailError(cause instanceof AdminAccessApiError ? cause.message : "Không thể tải chi tiết Permission."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải danh mục Permission</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Quản trị <span>›</span> Permission</nav><h1>Danh mục Permission</h1><p>Tra cứu mã quyền, action, resource, scope và nơi đang sử dụng; quyền xem không được suy rộng thành quyền thao tác.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Tổng Permission</span><strong>{data.items.length}</strong><small>Trong registry Web Admin hiện tại</small></article><article><span>Đang hoạt động</span><strong>{data.items.filter((item) => item.status === "ACTIVE").length}</strong><small>Được module dùng để thực thi</small></article><article><span>Mã hệ thống</span><strong>{data.items.filter((item) => item.kind === "SYSTEM").length}</strong><small>Không đổi/xóa cứng tùy ý</small></article><article><span>Resource</span><strong>{data.resources.length}</strong><small>Phân tách theo tài nguyên nghiệp vụ</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc trạng thái Permission">{data.statusCounts.map((item) => <button className={status === item.status ? "active" : ""} type="button" role="tab" aria-selected={status === item.status} onClick={() => setStatus(item.status)} key={item.status}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã, tên, action hoặc resource…" /></label><label><span className="sr-only">Resource</span><select value={resource} onChange={(event) => setResource(event.target.value)}><option value="ALL">Tất cả resource</option>{data.resources.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label><span className="sr-only">Loại Permission</span><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="ALL">Tất cả loại</option><option value="SYSTEM">Mã hệ thống</option><option value="CONFIGURABLE">Có thể cấu hình</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setQuery(""); setResource("ALL"); setKind("ALL"); setStatus("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> Permission</span><span>Tính lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-permission-catalog-table"><thead><tr><th>Permission</th><th>Action</th><th>Resource / Scope</th><th>Loại</th><th>Trạng thái</th><th>Role sử dụng</th><th>Employee hiệu lực</th><th>Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.permissionCode}><td><strong>{item.permissionName}</strong><small>{item.permissionCode}</small></td><td><strong>{item.action}</strong></td><td><strong>{item.resource}</strong><small>{item.scopeLabel}</small></td><td>{item.kind === "SYSTEM" ? "Hệ thống" : "Cấu hình"}</td><td><PermissionStatus item={item} /></td><td><strong>{item.roleCount}</strong><small>Role</small></td><td><strong>{item.employeeCount}</strong><small>Employee</small></td><td>{DATE_TIME.format(new Date(item.updatedAt))}</td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.permissionCode}`} onClick={() => setMenuCode((current) => current === item.permissionCode ? "" : item.permissionCode)}>•••</button>{menuCode === item.permissionCode ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết sử dụng</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có Permission phù hợp</h3><p>Hãy thay đổi trạng thái, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Permission · ${selected.permissionCode}`} subtitle={selected.permissionName} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải nơi sử dụng Permission…</div> : detail ? <PermissionDetailContent detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function PermissionDetailContent({ detail }: { detail: AdminPermissionDetail }) { return <div className="admin-catalog-detail"><div className="admin-detail-summary"><PermissionStatus item={detail} /><span>{detail.kind === "SYSTEM" ? "Mã hệ thống" : "Có thể cấu hình"}</span><span>{detail.action} / {detail.resource}</span></div>{detail.protectedCode ? <section className="admin-protected-notice"><strong>Mã Permission được bảo vệ</strong><p>Module nghiệp vụ đang thực thi theo mã này; không được đổi tên hoặc xóa cứng gây mất kiểm soát quyền.</p></section> : null}<div className="admin-detail-grid"><section><h3>Định nghĩa Permission</h3><dl><div><dt>Mã</dt><dd>{detail.permissionCode}</dd></div><div><dt>Tên</dt><dd>{detail.permissionName}</dd></div><div><dt>Mô tả</dt><dd>{detail.description}</dd></div><div><dt>Action</dt><dd>{detail.action}</dd></div><div><dt>Resource</dt><dd>{detail.resource}</dd></div><div><dt>Scope</dt><dd>{detail.scopeLabel}</dd></div></dl></section><section><h3>Nơi thực thi</h3><ul className="admin-module-list">{detail.usedByModules.map((module) => <li key={module}>{module}</li>)}</ul></section></div><section><h3>Role đang sử dụng</h3><table className="admin-permission-table"><thead><tr><th>Role</th><th>Trạng thái</th><th>Employee hiệu lực</th></tr></thead><tbody>{detail.rolesUsing.map((role) => <tr key={role.roleCode}><td><strong>{role.roleName}</strong><small>{role.roleCode}</small></td><td>{role.status}</td><td>{role.employeeCount}</td></tr>)}</tbody></table></section><footer>Permission chỉ mô tả quyền cơ bản; điều kiện động như assignment, trạng thái nghiệp vụ hoặc hạn mức vẫn do Epic chuyên môn kiểm tra.</footer></div>; }
