// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: order/v1/order.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Address, AuditContext, Money } from "../../common/v1/types";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.order.v1";

/** Vòng đời trạng thái thực thể Đơn hàng (Tuân thủ triệt để stateDiagram-v2) */
export enum OrderStatus {
  /** ORDER_STATUS_UNSPECIFIED - Mặc định bắt buộc 0 */
  ORDER_STATUS_UNSPECIFIED = 0,
  /** ORDER_STATUS_DRAFT - Đang khởi tạo, khóa tồn kho */
  ORDER_STATUS_DRAFT = 1,
  /** ORDER_STATUS_PENDING_PAYMENT - Đã giữ tồn 15m, đang chờ quét VietQR */
  ORDER_STATUS_PENDING_PAYMENT = 2,
  /** ORDER_STATUS_PAID - Đã thanh toán thành công (HMAC verified) */
  ORDER_STATUS_PAID = 3,
  /** ORDER_STATUS_PROCESSING - Xưởng Huế tiếp nhận đóng gói */
  ORDER_STATUS_PROCESSING = 4,
  /** ORDER_STATUS_PACKED - Đã niêm phong tem Seal O Mạ, có video S3 */
  ORDER_STATUS_PACKED = 5,
  /** ORDER_STATUS_SHIPPED - Đã bàn giao bưu tá 3PL (GHN/ViettelPost) */
  ORDER_STATUS_SHIPPED = 6,
  /** ORDER_STATUS_DELIVERED - Giao hàng thành công đến tay khách */
  ORDER_STATUS_DELIVERED = 7,
  /** ORDER_STATUS_COMPLETED - Đơn hoàn tất sau 7 ngày không khiếu nại (Tích loyalty) */
  ORDER_STATUS_COMPLETED = 8,
  /** ORDER_STATUS_CANCELLED_TIMEOUT - Trạng thái hủy và hoàn trả */
  ORDER_STATUS_CANCELLED_TIMEOUT = 9,
  /** ORDER_STATUS_CANCELLED_BY_USER - Khách chủ động hủy khi chưa thanh toán */
  ORDER_STATUS_CANCELLED_BY_USER = 10,
  /** ORDER_STATUS_CANCELLED_OUT_OF_STOCK - Hủy do không đủ tồn kho khả dụng */
  ORDER_STATUS_CANCELLED_OUT_OF_STOCK = 11,
  /** ORDER_STATUS_RETURN_REQUESTED - Khách gửi khiếu nại kẹo vỡ/hỏng */
  ORDER_STATUS_RETURN_REQUESTED = 12,
  /** ORDER_STATUS_REFUNDED - Đã kiểm định video seal và hoàn tiền */
  ORDER_STATUS_REFUNDED = 13,
  UNRECOGNIZED = -1,
}

export function orderStatusFromJSON(object: any): OrderStatus {
  switch (object) {
    case 0:
    case "ORDER_STATUS_UNSPECIFIED":
      return OrderStatus.ORDER_STATUS_UNSPECIFIED;
    case 1:
    case "ORDER_STATUS_DRAFT":
      return OrderStatus.ORDER_STATUS_DRAFT;
    case 2:
    case "ORDER_STATUS_PENDING_PAYMENT":
      return OrderStatus.ORDER_STATUS_PENDING_PAYMENT;
    case 3:
    case "ORDER_STATUS_PAID":
      return OrderStatus.ORDER_STATUS_PAID;
    case 4:
    case "ORDER_STATUS_PROCESSING":
      return OrderStatus.ORDER_STATUS_PROCESSING;
    case 5:
    case "ORDER_STATUS_PACKED":
      return OrderStatus.ORDER_STATUS_PACKED;
    case 6:
    case "ORDER_STATUS_SHIPPED":
      return OrderStatus.ORDER_STATUS_SHIPPED;
    case 7:
    case "ORDER_STATUS_DELIVERED":
      return OrderStatus.ORDER_STATUS_DELIVERED;
    case 8:
    case "ORDER_STATUS_COMPLETED":
      return OrderStatus.ORDER_STATUS_COMPLETED;
    case 9:
    case "ORDER_STATUS_CANCELLED_TIMEOUT":
      return OrderStatus.ORDER_STATUS_CANCELLED_TIMEOUT;
    case 10:
    case "ORDER_STATUS_CANCELLED_BY_USER":
      return OrderStatus.ORDER_STATUS_CANCELLED_BY_USER;
    case 11:
    case "ORDER_STATUS_CANCELLED_OUT_OF_STOCK":
      return OrderStatus.ORDER_STATUS_CANCELLED_OUT_OF_STOCK;
    case 12:
    case "ORDER_STATUS_RETURN_REQUESTED":
      return OrderStatus.ORDER_STATUS_RETURN_REQUESTED;
    case 13:
    case "ORDER_STATUS_REFUNDED":
      return OrderStatus.ORDER_STATUS_REFUNDED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStatus.UNRECOGNIZED;
  }
}

export function orderStatusToJSON(object: OrderStatus): string {
  switch (object) {
    case OrderStatus.ORDER_STATUS_UNSPECIFIED:
      return "ORDER_STATUS_UNSPECIFIED";
    case OrderStatus.ORDER_STATUS_DRAFT:
      return "ORDER_STATUS_DRAFT";
    case OrderStatus.ORDER_STATUS_PENDING_PAYMENT:
      return "ORDER_STATUS_PENDING_PAYMENT";
    case OrderStatus.ORDER_STATUS_PAID:
      return "ORDER_STATUS_PAID";
    case OrderStatus.ORDER_STATUS_PROCESSING:
      return "ORDER_STATUS_PROCESSING";
    case OrderStatus.ORDER_STATUS_PACKED:
      return "ORDER_STATUS_PACKED";
    case OrderStatus.ORDER_STATUS_SHIPPED:
      return "ORDER_STATUS_SHIPPED";
    case OrderStatus.ORDER_STATUS_DELIVERED:
      return "ORDER_STATUS_DELIVERED";
    case OrderStatus.ORDER_STATUS_COMPLETED:
      return "ORDER_STATUS_COMPLETED";
    case OrderStatus.ORDER_STATUS_CANCELLED_TIMEOUT:
      return "ORDER_STATUS_CANCELLED_TIMEOUT";
    case OrderStatus.ORDER_STATUS_CANCELLED_BY_USER:
      return "ORDER_STATUS_CANCELLED_BY_USER";
    case OrderStatus.ORDER_STATUS_CANCELLED_OUT_OF_STOCK:
      return "ORDER_STATUS_CANCELLED_OUT_OF_STOCK";
    case OrderStatus.ORDER_STATUS_RETURN_REQUESTED:
      return "ORDER_STATUS_RETURN_REQUESTED";
    case OrderStatus.ORDER_STATUS_REFUNDED:
      return "ORDER_STATUS_REFUNDED";
    case OrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Mặt hàng chi tiết trong đơn hàng */
export interface OrderItem {
  skuCode: string;
  productName: string;
  quantity: number;
  /** Đơn giá tại thời điểm đặt hàng (Snapshot) */
  unitPrice?:
    | Money
    | undefined;
  /** Thành tiền = unit_price * quantity */
  totalPrice?:
    | Money
    | undefined;
  /** Ghi chú đóng gói cho mặt hàng (Optional) */
  itemNotes?: string | undefined;
}

/** Thông tin thanh toán đính kèm đơn hàng */
export interface PaymentInfo {
  /** VIETQR, COD, B2B_BANK_TRANSFER */
  paymentMethod: string;
  /** PENDING, PAID, REFUNDED */
  paymentStatus: string;
  /** Đường link ảnh QR VietQR động (chứa cú pháp chuyển khoản và số tiền chính xác) */
  vietqrUrl?:
    | string
    | undefined;
  /** Thời điểm nhận được tiền từ ngân hàng */
  paidAt?:
    | Date
    | undefined;
  /** Mã giao dịch ngân hàng đối soát */
  bankTransactionId?: string | undefined;
}

/** Yêu cầu tạo đơn hàng trực tiếp tại quầy POS offline */
export interface CreatePOSOrderRequest {
  /** Idempotency Key bắt buộc */
  idempotencyKey: string;
  /** Mã khách hàng (Nếu khách vãng lai không đăng ký tài khoản, gán "GUEST_OFFLINE") */
  customerId: string;
  /** Mã quầy thu ngân / chi nhánh (Ví dụ: "POS-KHO-HUONG-THUY", "POS-STORE-HOA-BINH") */
  posTerminalId: string;
  /** Mã nhân viên thu ngân tại quầy */
  cashierStaffId: string;
  /** Danh sách mặt hàng kẹo mua tại quầy */
  items: OrderItem[];
  /** Phương thức thanh toán tại quầy (CASH, VIETQR_DYNAMIC_POS, CARD) */
  paymentMethod: string;
  /** Mã voucher khuyến mãi (Nếu có) */
  voucherCode?:
    | string
    | undefined;
  /** Bối cảnh kiểm toán */
  auditContext?: AuditContext | undefined;
}

/** Phản hồi tạo đơn hàng tại quầy POS */
export interface CreatePOSOrderResponse {
  orderId: string;
  status: OrderStatus;
  /** Tổng tiền hàng trước giảm giá */
  subtotalAmount?:
    | Money
    | undefined;
  /** Số tiền giảm giá từ voucher (Bắt buộc dùng optional để phân biệt 0đ với không áp mã) */
  discountAmount?:
    | Money
    | undefined;
  /** Tổng số tiền khách hàng thực tế phải thanh toán tại quầy */
  finalAmount?:
    | Money
    | undefined;
  /** Thông tin thanh toán VietQR nếu khách chọn quét mã QR tại màn hình quầy thu ngân */
  payment?:
    | PaymentInfo
    | undefined;
  /** Lỗi nếu tạo thất bại (ví dụ hết hàng tại kho xưởng) */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu truy vấn chi tiết đơn hàng */
export interface GetOrderDetailRequest {
  orderId: string;
  /** Xác thực quyền truy cập: Chỉ chủ đơn hoặc Admin/Staff mới được xem */
  requestingUserId: string;
}

/** Phản hồi chi tiết đơn hàng */
export interface GetOrderDetailResponse {
  orderId: string;
  customerId: string;
  channel: string;
  status: OrderStatus;
  items: OrderItem[];
  shippingAddress?: Address | undefined;
  subtotalAmount?: Money | undefined;
  discountAmount?: Money | undefined;
  shippingFee?: Money | undefined;
  finalAmount?: Money | undefined;
  payment?:
    | PaymentInfo
    | undefined;
  /** Mã vận đơn giao vận 3PL (nếu đã bàn giao) */
  trackingCode?: string | undefined;
  shippingCarrier?:
    | string
    | undefined;
  /** Mã tem seal niêm phong gói kẹo O Mạ */
  sealCode?: string | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

/** Yêu cầu hủy đơn hàng */
export interface CancelOrderRequest {
  idempotencyKey: string;
  orderId: string;
  cancelReason: string;
  cancelledByUserId: string;
}

/** Phản hồi hủy đơn hàng */
export interface CancelOrderResponse {
  isCancelled: boolean;
  finalStatus: OrderStatus;
  message: string;
}

function createBaseOrderItem(): OrderItem {
  return {
    skuCode: "",
    productName: "",
    quantity: 0,
    unitPrice: undefined,
    totalPrice: undefined,
    itemNotes: undefined,
  };
}

export const OrderItem = {
  encode(message: OrderItem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.productName !== "") {
      writer.uint32(18).string(message.productName);
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    if (message.unitPrice !== undefined) {
      Money.encode(message.unitPrice, writer.uint32(34).fork()).ldelim();
    }
    if (message.totalPrice !== undefined) {
      Money.encode(message.totalPrice, writer.uint32(42).fork()).ldelim();
    }
    if (message.itemNotes !== undefined) {
      writer.uint32(50).string(message.itemNotes);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderItem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.productName = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.unitPrice = Money.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.totalPrice = Money.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.itemNotes = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderItem {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      productName: isSet(object.productName) ? globalThis.String(object.productName) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      unitPrice: isSet(object.unitPrice) ? Money.fromJSON(object.unitPrice) : undefined,
      totalPrice: isSet(object.totalPrice) ? Money.fromJSON(object.totalPrice) : undefined,
      itemNotes: isSet(object.itemNotes) ? globalThis.String(object.itemNotes) : undefined,
    };
  },

  toJSON(message: OrderItem): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.productName !== "") {
      obj.productName = message.productName;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.unitPrice !== undefined) {
      obj.unitPrice = Money.toJSON(message.unitPrice);
    }
    if (message.totalPrice !== undefined) {
      obj.totalPrice = Money.toJSON(message.totalPrice);
    }
    if (message.itemNotes !== undefined) {
      obj.itemNotes = message.itemNotes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderItem>, I>>(base?: I): OrderItem {
    return OrderItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderItem>, I>>(object: I): OrderItem {
    const message = createBaseOrderItem();
    message.skuCode = object.skuCode ?? "";
    message.productName = object.productName ?? "";
    message.quantity = object.quantity ?? 0;
    message.unitPrice = (object.unitPrice !== undefined && object.unitPrice !== null)
      ? Money.fromPartial(object.unitPrice)
      : undefined;
    message.totalPrice = (object.totalPrice !== undefined && object.totalPrice !== null)
      ? Money.fromPartial(object.totalPrice)
      : undefined;
    message.itemNotes = object.itemNotes ?? undefined;
    return message;
  },
};

function createBasePaymentInfo(): PaymentInfo {
  return {
    paymentMethod: "",
    paymentStatus: "",
    vietqrUrl: undefined,
    paidAt: undefined,
    bankTransactionId: undefined,
  };
}

export const PaymentInfo = {
  encode(message: PaymentInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.paymentMethod !== "") {
      writer.uint32(10).string(message.paymentMethod);
    }
    if (message.paymentStatus !== "") {
      writer.uint32(18).string(message.paymentStatus);
    }
    if (message.vietqrUrl !== undefined) {
      writer.uint32(26).string(message.vietqrUrl);
    }
    if (message.paidAt !== undefined) {
      Timestamp.encode(toTimestamp(message.paidAt), writer.uint32(34).fork()).ldelim();
    }
    if (message.bankTransactionId !== undefined) {
      writer.uint32(42).string(message.bankTransactionId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PaymentInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.paymentStatus = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.vietqrUrl = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.paidAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.bankTransactionId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentInfo {
    return {
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      paymentStatus: isSet(object.paymentStatus) ? globalThis.String(object.paymentStatus) : "",
      vietqrUrl: isSet(object.vietqrUrl) ? globalThis.String(object.vietqrUrl) : undefined,
      paidAt: isSet(object.paidAt) ? fromJsonTimestamp(object.paidAt) : undefined,
      bankTransactionId: isSet(object.bankTransactionId) ? globalThis.String(object.bankTransactionId) : undefined,
    };
  },

  toJSON(message: PaymentInfo): unknown {
    const obj: any = {};
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.paymentStatus !== "") {
      obj.paymentStatus = message.paymentStatus;
    }
    if (message.vietqrUrl !== undefined) {
      obj.vietqrUrl = message.vietqrUrl;
    }
    if (message.paidAt !== undefined) {
      obj.paidAt = message.paidAt.toISOString();
    }
    if (message.bankTransactionId !== undefined) {
      obj.bankTransactionId = message.bankTransactionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentInfo>, I>>(base?: I): PaymentInfo {
    return PaymentInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentInfo>, I>>(object: I): PaymentInfo {
    const message = createBasePaymentInfo();
    message.paymentMethod = object.paymentMethod ?? "";
    message.paymentStatus = object.paymentStatus ?? "";
    message.vietqrUrl = object.vietqrUrl ?? undefined;
    message.paidAt = object.paidAt ?? undefined;
    message.bankTransactionId = object.bankTransactionId ?? undefined;
    return message;
  },
};

function createBaseCreatePOSOrderRequest(): CreatePOSOrderRequest {
  return {
    idempotencyKey: "",
    customerId: "",
    posTerminalId: "",
    cashierStaffId: "",
    items: [],
    paymentMethod: "",
    voucherCode: undefined,
    auditContext: undefined,
  };
}

export const CreatePOSOrderRequest = {
  encode(message: CreatePOSOrderRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.customerId !== "") {
      writer.uint32(18).string(message.customerId);
    }
    if (message.posTerminalId !== "") {
      writer.uint32(26).string(message.posTerminalId);
    }
    if (message.cashierStaffId !== "") {
      writer.uint32(34).string(message.cashierStaffId);
    }
    for (const v of message.items) {
      OrderItem.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    if (message.paymentMethod !== "") {
      writer.uint32(50).string(message.paymentMethod);
    }
    if (message.voucherCode !== undefined) {
      writer.uint32(58).string(message.voucherCode);
    }
    if (message.auditContext !== undefined) {
      AuditContext.encode(message.auditContext, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreatePOSOrderRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePOSOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.customerId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.posTerminalId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.cashierStaffId = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.items.push(OrderItem.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.voucherCode = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.auditContext = AuditContext.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatePOSOrderRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
      posTerminalId: isSet(object.posTerminalId) ? globalThis.String(object.posTerminalId) : "",
      cashierStaffId: isSet(object.cashierStaffId) ? globalThis.String(object.cashierStaffId) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => OrderItem.fromJSON(e)) : [],
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      voucherCode: isSet(object.voucherCode) ? globalThis.String(object.voucherCode) : undefined,
      auditContext: isSet(object.auditContext) ? AuditContext.fromJSON(object.auditContext) : undefined,
    };
  },

  toJSON(message: CreatePOSOrderRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    if (message.posTerminalId !== "") {
      obj.posTerminalId = message.posTerminalId;
    }
    if (message.cashierStaffId !== "") {
      obj.cashierStaffId = message.cashierStaffId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderItem.toJSON(e));
    }
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.voucherCode !== undefined) {
      obj.voucherCode = message.voucherCode;
    }
    if (message.auditContext !== undefined) {
      obj.auditContext = AuditContext.toJSON(message.auditContext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatePOSOrderRequest>, I>>(base?: I): CreatePOSOrderRequest {
    return CreatePOSOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatePOSOrderRequest>, I>>(object: I): CreatePOSOrderRequest {
    const message = createBaseCreatePOSOrderRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.customerId = object.customerId ?? "";
    message.posTerminalId = object.posTerminalId ?? "";
    message.cashierStaffId = object.cashierStaffId ?? "";
    message.items = object.items?.map((e) => OrderItem.fromPartial(e)) || [];
    message.paymentMethod = object.paymentMethod ?? "";
    message.voucherCode = object.voucherCode ?? undefined;
    message.auditContext = (object.auditContext !== undefined && object.auditContext !== null)
      ? AuditContext.fromPartial(object.auditContext)
      : undefined;
    return message;
  },
};

function createBaseCreatePOSOrderResponse(): CreatePOSOrderResponse {
  return {
    orderId: "",
    status: 0,
    subtotalAmount: undefined,
    discountAmount: undefined,
    finalAmount: undefined,
    payment: undefined,
    error: undefined,
  };
}

export const CreatePOSOrderResponse = {
  encode(message: CreatePOSOrderResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.subtotalAmount !== undefined) {
      Money.encode(message.subtotalAmount, writer.uint32(26).fork()).ldelim();
    }
    if (message.discountAmount !== undefined) {
      Money.encode(message.discountAmount, writer.uint32(34).fork()).ldelim();
    }
    if (message.finalAmount !== undefined) {
      Money.encode(message.finalAmount, writer.uint32(42).fork()).ldelim();
    }
    if (message.payment !== undefined) {
      PaymentInfo.encode(message.payment, writer.uint32(50).fork()).ldelim();
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreatePOSOrderResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePOSOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.subtotalAmount = Money.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.discountAmount = Money.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.finalAmount = Money.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.payment = PaymentInfo.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatePOSOrderResponse {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      status: isSet(object.status) ? orderStatusFromJSON(object.status) : 0,
      subtotalAmount: isSet(object.subtotalAmount) ? Money.fromJSON(object.subtotalAmount) : undefined,
      discountAmount: isSet(object.discountAmount) ? Money.fromJSON(object.discountAmount) : undefined,
      finalAmount: isSet(object.finalAmount) ? Money.fromJSON(object.finalAmount) : undefined,
      payment: isSet(object.payment) ? PaymentInfo.fromJSON(object.payment) : undefined,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: CreatePOSOrderResponse): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.status !== 0) {
      obj.status = orderStatusToJSON(message.status);
    }
    if (message.subtotalAmount !== undefined) {
      obj.subtotalAmount = Money.toJSON(message.subtotalAmount);
    }
    if (message.discountAmount !== undefined) {
      obj.discountAmount = Money.toJSON(message.discountAmount);
    }
    if (message.finalAmount !== undefined) {
      obj.finalAmount = Money.toJSON(message.finalAmount);
    }
    if (message.payment !== undefined) {
      obj.payment = PaymentInfo.toJSON(message.payment);
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatePOSOrderResponse>, I>>(base?: I): CreatePOSOrderResponse {
    return CreatePOSOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatePOSOrderResponse>, I>>(object: I): CreatePOSOrderResponse {
    const message = createBaseCreatePOSOrderResponse();
    message.orderId = object.orderId ?? "";
    message.status = object.status ?? 0;
    message.subtotalAmount = (object.subtotalAmount !== undefined && object.subtotalAmount !== null)
      ? Money.fromPartial(object.subtotalAmount)
      : undefined;
    message.discountAmount = (object.discountAmount !== undefined && object.discountAmount !== null)
      ? Money.fromPartial(object.discountAmount)
      : undefined;
    message.finalAmount = (object.finalAmount !== undefined && object.finalAmount !== null)
      ? Money.fromPartial(object.finalAmount)
      : undefined;
    message.payment = (object.payment !== undefined && object.payment !== null)
      ? PaymentInfo.fromPartial(object.payment)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGetOrderDetailRequest(): GetOrderDetailRequest {
  return { orderId: "", requestingUserId: "" };
}

export const GetOrderDetailRequest = {
  encode(message: GetOrderDetailRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.requestingUserId !== "") {
      writer.uint32(18).string(message.requestingUserId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetOrderDetailRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrderDetailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.requestingUserId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrderDetailRequest {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      requestingUserId: isSet(object.requestingUserId) ? globalThis.String(object.requestingUserId) : "",
    };
  },

  toJSON(message: GetOrderDetailRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.requestingUserId !== "") {
      obj.requestingUserId = message.requestingUserId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrderDetailRequest>, I>>(base?: I): GetOrderDetailRequest {
    return GetOrderDetailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderDetailRequest>, I>>(object: I): GetOrderDetailRequest {
    const message = createBaseGetOrderDetailRequest();
    message.orderId = object.orderId ?? "";
    message.requestingUserId = object.requestingUserId ?? "";
    return message;
  },
};

function createBaseGetOrderDetailResponse(): GetOrderDetailResponse {
  return {
    orderId: "",
    customerId: "",
    channel: "",
    status: 0,
    items: [],
    shippingAddress: undefined,
    subtotalAmount: undefined,
    discountAmount: undefined,
    shippingFee: undefined,
    finalAmount: undefined,
    payment: undefined,
    trackingCode: undefined,
    shippingCarrier: undefined,
    sealCode: undefined,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const GetOrderDetailResponse = {
  encode(message: GetOrderDetailResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.customerId !== "") {
      writer.uint32(18).string(message.customerId);
    }
    if (message.channel !== "") {
      writer.uint32(26).string(message.channel);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    for (const v of message.items) {
      OrderItem.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    if (message.shippingAddress !== undefined) {
      Address.encode(message.shippingAddress, writer.uint32(50).fork()).ldelim();
    }
    if (message.subtotalAmount !== undefined) {
      Money.encode(message.subtotalAmount, writer.uint32(58).fork()).ldelim();
    }
    if (message.discountAmount !== undefined) {
      Money.encode(message.discountAmount, writer.uint32(66).fork()).ldelim();
    }
    if (message.shippingFee !== undefined) {
      Money.encode(message.shippingFee, writer.uint32(74).fork()).ldelim();
    }
    if (message.finalAmount !== undefined) {
      Money.encode(message.finalAmount, writer.uint32(82).fork()).ldelim();
    }
    if (message.payment !== undefined) {
      PaymentInfo.encode(message.payment, writer.uint32(90).fork()).ldelim();
    }
    if (message.trackingCode !== undefined) {
      writer.uint32(98).string(message.trackingCode);
    }
    if (message.shippingCarrier !== undefined) {
      writer.uint32(106).string(message.shippingCarrier);
    }
    if (message.sealCode !== undefined) {
      writer.uint32(114).string(message.sealCode);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(122).fork()).ldelim();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(130).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetOrderDetailResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrderDetailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.customerId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.channel = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.items.push(OrderItem.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.shippingAddress = Address.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.subtotalAmount = Money.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.discountAmount = Money.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.shippingFee = Money.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.finalAmount = Money.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.payment = PaymentInfo.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.trackingCode = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.shippingCarrier = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.sealCode = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrderDetailResponse {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      customerId: isSet(object.customerId) ? globalThis.String(object.customerId) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      status: isSet(object.status) ? orderStatusFromJSON(object.status) : 0,
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => OrderItem.fromJSON(e)) : [],
      shippingAddress: isSet(object.shippingAddress) ? Address.fromJSON(object.shippingAddress) : undefined,
      subtotalAmount: isSet(object.subtotalAmount) ? Money.fromJSON(object.subtotalAmount) : undefined,
      discountAmount: isSet(object.discountAmount) ? Money.fromJSON(object.discountAmount) : undefined,
      shippingFee: isSet(object.shippingFee) ? Money.fromJSON(object.shippingFee) : undefined,
      finalAmount: isSet(object.finalAmount) ? Money.fromJSON(object.finalAmount) : undefined,
      payment: isSet(object.payment) ? PaymentInfo.fromJSON(object.payment) : undefined,
      trackingCode: isSet(object.trackingCode) ? globalThis.String(object.trackingCode) : undefined,
      shippingCarrier: isSet(object.shippingCarrier) ? globalThis.String(object.shippingCarrier) : undefined,
      sealCode: isSet(object.sealCode) ? globalThis.String(object.sealCode) : undefined,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: GetOrderDetailResponse): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.customerId !== "") {
      obj.customerId = message.customerId;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.status !== 0) {
      obj.status = orderStatusToJSON(message.status);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderItem.toJSON(e));
    }
    if (message.shippingAddress !== undefined) {
      obj.shippingAddress = Address.toJSON(message.shippingAddress);
    }
    if (message.subtotalAmount !== undefined) {
      obj.subtotalAmount = Money.toJSON(message.subtotalAmount);
    }
    if (message.discountAmount !== undefined) {
      obj.discountAmount = Money.toJSON(message.discountAmount);
    }
    if (message.shippingFee !== undefined) {
      obj.shippingFee = Money.toJSON(message.shippingFee);
    }
    if (message.finalAmount !== undefined) {
      obj.finalAmount = Money.toJSON(message.finalAmount);
    }
    if (message.payment !== undefined) {
      obj.payment = PaymentInfo.toJSON(message.payment);
    }
    if (message.trackingCode !== undefined) {
      obj.trackingCode = message.trackingCode;
    }
    if (message.shippingCarrier !== undefined) {
      obj.shippingCarrier = message.shippingCarrier;
    }
    if (message.sealCode !== undefined) {
      obj.sealCode = message.sealCode;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrderDetailResponse>, I>>(base?: I): GetOrderDetailResponse {
    return GetOrderDetailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrderDetailResponse>, I>>(object: I): GetOrderDetailResponse {
    const message = createBaseGetOrderDetailResponse();
    message.orderId = object.orderId ?? "";
    message.customerId = object.customerId ?? "";
    message.channel = object.channel ?? "";
    message.status = object.status ?? 0;
    message.items = object.items?.map((e) => OrderItem.fromPartial(e)) || [];
    message.shippingAddress = (object.shippingAddress !== undefined && object.shippingAddress !== null)
      ? Address.fromPartial(object.shippingAddress)
      : undefined;
    message.subtotalAmount = (object.subtotalAmount !== undefined && object.subtotalAmount !== null)
      ? Money.fromPartial(object.subtotalAmount)
      : undefined;
    message.discountAmount = (object.discountAmount !== undefined && object.discountAmount !== null)
      ? Money.fromPartial(object.discountAmount)
      : undefined;
    message.shippingFee = (object.shippingFee !== undefined && object.shippingFee !== null)
      ? Money.fromPartial(object.shippingFee)
      : undefined;
    message.finalAmount = (object.finalAmount !== undefined && object.finalAmount !== null)
      ? Money.fromPartial(object.finalAmount)
      : undefined;
    message.payment = (object.payment !== undefined && object.payment !== null)
      ? PaymentInfo.fromPartial(object.payment)
      : undefined;
    message.trackingCode = object.trackingCode ?? undefined;
    message.shippingCarrier = object.shippingCarrier ?? undefined;
    message.sealCode = object.sealCode ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseCancelOrderRequest(): CancelOrderRequest {
  return { idempotencyKey: "", orderId: "", cancelReason: "", cancelledByUserId: "" };
}

export const CancelOrderRequest = {
  encode(message: CancelOrderRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.cancelReason !== "") {
      writer.uint32(26).string(message.cancelReason);
    }
    if (message.cancelledByUserId !== "") {
      writer.uint32(34).string(message.cancelledByUserId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CancelOrderRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.cancelReason = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.cancelledByUserId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelOrderRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      cancelReason: isSet(object.cancelReason) ? globalThis.String(object.cancelReason) : "",
      cancelledByUserId: isSet(object.cancelledByUserId) ? globalThis.String(object.cancelledByUserId) : "",
    };
  },

  toJSON(message: CancelOrderRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.cancelReason !== "") {
      obj.cancelReason = message.cancelReason;
    }
    if (message.cancelledByUserId !== "") {
      obj.cancelledByUserId = message.cancelledByUserId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelOrderRequest>, I>>(base?: I): CancelOrderRequest {
    return CancelOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOrderRequest>, I>>(object: I): CancelOrderRequest {
    const message = createBaseCancelOrderRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.orderId = object.orderId ?? "";
    message.cancelReason = object.cancelReason ?? "";
    message.cancelledByUserId = object.cancelledByUserId ?? "";
    return message;
  },
};

function createBaseCancelOrderResponse(): CancelOrderResponse {
  return { isCancelled: false, finalStatus: 0, message: "" };
}

export const CancelOrderResponse = {
  encode(message: CancelOrderResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isCancelled !== false) {
      writer.uint32(8).bool(message.isCancelled);
    }
    if (message.finalStatus !== 0) {
      writer.uint32(16).int32(message.finalStatus);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CancelOrderResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isCancelled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.finalStatus = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelOrderResponse {
    return {
      isCancelled: isSet(object.isCancelled) ? globalThis.Boolean(object.isCancelled) : false,
      finalStatus: isSet(object.finalStatus) ? orderStatusFromJSON(object.finalStatus) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CancelOrderResponse): unknown {
    const obj: any = {};
    if (message.isCancelled !== false) {
      obj.isCancelled = message.isCancelled;
    }
    if (message.finalStatus !== 0) {
      obj.finalStatus = orderStatusToJSON(message.finalStatus);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelOrderResponse>, I>>(base?: I): CancelOrderResponse {
    return CancelOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOrderResponse>, I>>(object: I): CancelOrderResponse {
    const message = createBaseCancelOrderResponse();
    message.isCancelled = object.isCancelled ?? false;
    message.finalStatus = object.finalStatus ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

export type OrderServiceService = typeof OrderServiceService;
export const OrderServiceService = {
  /**
   * Tạo đơn hàng trực tiếp tại quầy bán lẻ offline (POS Quầy Xưởng Hương Thủy & Cửa hàng Huế)
   * Bên Tiêu Thụ Duy Nhất: MS-13 channel-service (Phân hệ POS)
   * TUYỆT ĐỐI CẤM dùng RPC này cho đơn sàn Shopee/TikTok (Đơn sàn đi qua Kafka MarketplaceOrderImportedEvent)
   */
  createPosOrder: {
    path: "/omamx.order.v1.OrderService/CreatePOSOrder",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreatePOSOrderRequest) => Buffer.from(CreatePOSOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreatePOSOrderRequest.decode(value),
    responseSerialize: (value: CreatePOSOrderResponse) => Buffer.from(CreatePOSOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CreatePOSOrderResponse.decode(value),
  },
  /** Truy vấn chi tiết đơn hàng kèm trạng thái thanh toán và thông tin giao vận */
  getOrderDetail: {
    path: "/omamx.order.v1.OrderService/GetOrderDetail",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetOrderDetailRequest) => Buffer.from(GetOrderDetailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetOrderDetailRequest.decode(value),
    responseSerialize: (value: GetOrderDetailResponse) => Buffer.from(GetOrderDetailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetOrderDetailResponse.decode(value),
  },
  /** Khách hàng hoặc Quản trị viên yêu cầu hủy đơn hàng (Kích hoạt Saga Compensation) */
  cancelOrder: {
    path: "/omamx.order.v1.OrderService/CancelOrder",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CancelOrderRequest) => Buffer.from(CancelOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CancelOrderRequest.decode(value),
    responseSerialize: (value: CancelOrderResponse) => Buffer.from(CancelOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CancelOrderResponse.decode(value),
  },
} as const;

export interface OrderServiceServer extends UntypedServiceImplementation {
  /**
   * Tạo đơn hàng trực tiếp tại quầy bán lẻ offline (POS Quầy Xưởng Hương Thủy & Cửa hàng Huế)
   * Bên Tiêu Thụ Duy Nhất: MS-13 channel-service (Phân hệ POS)
   * TUYỆT ĐỐI CẤM dùng RPC này cho đơn sàn Shopee/TikTok (Đơn sàn đi qua Kafka MarketplaceOrderImportedEvent)
   */
  createPosOrder: handleUnaryCall<CreatePOSOrderRequest, CreatePOSOrderResponse>;
  /** Truy vấn chi tiết đơn hàng kèm trạng thái thanh toán và thông tin giao vận */
  getOrderDetail: handleUnaryCall<GetOrderDetailRequest, GetOrderDetailResponse>;
  /** Khách hàng hoặc Quản trị viên yêu cầu hủy đơn hàng (Kích hoạt Saga Compensation) */
  cancelOrder: handleUnaryCall<CancelOrderRequest, CancelOrderResponse>;
}

export interface OrderServiceClient extends Client {
  /**
   * Tạo đơn hàng trực tiếp tại quầy bán lẻ offline (POS Quầy Xưởng Hương Thủy & Cửa hàng Huế)
   * Bên Tiêu Thụ Duy Nhất: MS-13 channel-service (Phân hệ POS)
   * TUYỆT ĐỐI CẤM dùng RPC này cho đơn sàn Shopee/TikTok (Đơn sàn đi qua Kafka MarketplaceOrderImportedEvent)
   */
  createPosOrder(
    request: CreatePOSOrderRequest,
    callback: (error: ServiceError | null, response: CreatePOSOrderResponse) => void,
  ): ClientUnaryCall;
  createPosOrder(
    request: CreatePOSOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreatePOSOrderResponse) => void,
  ): ClientUnaryCall;
  createPosOrder(
    request: CreatePOSOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreatePOSOrderResponse) => void,
  ): ClientUnaryCall;
  /** Truy vấn chi tiết đơn hàng kèm trạng thái thanh toán và thông tin giao vận */
  getOrderDetail(
    request: GetOrderDetailRequest,
    callback: (error: ServiceError | null, response: GetOrderDetailResponse) => void,
  ): ClientUnaryCall;
  getOrderDetail(
    request: GetOrderDetailRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetOrderDetailResponse) => void,
  ): ClientUnaryCall;
  getOrderDetail(
    request: GetOrderDetailRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetOrderDetailResponse) => void,
  ): ClientUnaryCall;
  /** Khách hàng hoặc Quản trị viên yêu cầu hủy đơn hàng (Kích hoạt Saga Compensation) */
  cancelOrder(
    request: CancelOrderRequest,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
  cancelOrder(
    request: CancelOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
  cancelOrder(
    request: CancelOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CancelOrderResponse) => void,
  ): ClientUnaryCall;
}

export const OrderServiceClient = makeGenericClientConstructor(
  OrderServiceService,
  "omamx.order.v1.OrderService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OrderServiceClient;
  service: typeof OrderServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
