"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { ReturnCaseDetail, ReturnCaseList, ReturnCaseStatus, ReturnCaseSummary, ReturnCaseType, ReturnEvidenceState, ReturnRefundState } from "@/lib/returns/types";
import { AdminReturnApiError } from "@/lib/returns/types";
import { adminReturnService } from "@/services/admin-return-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
const MONEY = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
function Status({ code, label, prefix = "return-case" }: { code: string; label: string; prefix?: string }) { return <span className={`admin-status ${prefix}-${code.toLowerCase()}`}>{label}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }
const moneyOrPermission = (value: number | null) => value === null ? "Đã ẩn theo Permission" : MONEY.format(value);

export function ReturnWorkspace() {
  const [data, setData] = useState<ReturnCaseList | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [status, setStatus] = useState<"ALL" | ReturnCaseStatus>("ALL"); const [query, setQuery] = useState(""); const [caseType, setCaseType] = useState<"ALL" | ReturnCaseType>("ALL"); const [evidence, setEvidence] = useState<"ALL" | ReturnEvidenceState>("ALL"); const [refund, setRefund] = useState<"ALL" | ReturnRefundState>("ALL");
  const [menuId, setMenuId] = useState(""); const [selected, setSelected] = useState<ReturnCaseSummary | null>(null); const [detail, setDetail] = useState<ReturnCaseDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminReturnService.cases()); } catch (cause) { setLoadError(cause instanceof AdminReturnApiError ? cause.message : "Không thể tải danh sách Return Case."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("vi"); return data?.items.filter((item) => (status === "ALL" || item.status === status) && (caseType === "ALL" || item.caseType === caseType) && (evidence === "ALL" || item.evidenceState === evidence) && (refund === "ALL" || item.refundState === refund) && (!needle || [item.caseNumber, item.orderNumber, item.customerLabel, item.reasonLabel].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? []; }, [caseType, data, evidence, query, refund, status]);
  const active = data?.items.filter((item) => !["REJECTED", "REFUNDED"].includes(item.status)).length ?? 0;
  const reviewing = data?.items.filter((item) => item.status === "REVIEWING").length ?? 0;
  const missingEvidence = data?.items.filter((item) => item.evidenceState === "INCOMPLETE").length ?? 0;
  const pendingRefund = data?.items.filter((item) => ["PENDING", "FAILED"].includes(item.refundState)).length ?? 0;
  async function openDetail(item: ReturnCaseSummary) { setMenuId(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const loaded = await adminReturnService.case(item.caseId); setDetail({ ...loaded, ...item, customer: loaded.customer, order: loaded.order, lines: loaded.lines, payment: loaded.payment, shipment: loaded.shipment, evidences: loaded.evidences, evidenceMasked: loaded.evidenceMasked, decision: loaded.decision, refund: loaded.refund, history: loaded.history, createdAt: loaded.createdAt }); } catch (cause) { setDetailError(cause instanceof AdminReturnApiError ? cause.message : "Không thể tải hồ sơ Return Case."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải đổi trả</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Hậu mãi <span>›</span> Đổi trả & hoàn tiền</nav><h1>Quản lý đổi trả và hoàn tiền</h1><p>Theo dõi Return Case, hàng trả và Refund như các vòng đời độc lập theo Epic 14.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Case đang hoạt động</span><strong>{active}</strong><small>Không gồm đã từ chối hoặc đã hoàn tất Refund</small></article><article><span>Đang thẩm định</span><strong>{reviewing}</strong><small>Chờ CSKH hoặc Manager đánh giá hồ sơ</small></article><article><span>Thiếu bằng chứng</span><strong>{missingEvidence}</strong><small>Chưa đủ dữ liệu để chuyển bước xử lý</small></article><article><span>Refund cần theo dõi</span><strong>{pendingRefund}</strong><small>Đang chờ hoặc nhận kết quả thất bại</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc trạng thái Return Case">{data.statusCounts.map((item) => <button className={status === item.status ? "active" : ""} type="button" role="tab" aria-selected={status === item.status} onClick={() => setStatus(item.status)} key={item.status}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar return-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm Case, Order, khách hàng hoặc lý do…" /></label><label><span className="sr-only">Loại Case</span><select value={caseType} onChange={(event) => setCaseType(event.target.value as "ALL" | ReturnCaseType)}><option value="ALL">Mọi loại Case</option>{data.caseTypes.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label><label><span className="sr-only">Bằng chứng</span><select value={evidence} onChange={(event) => setEvidence(event.target.value as "ALL" | ReturnEvidenceState)}><option value="ALL">Mọi tình trạng bằng chứng</option><option value="INCOMPLETE">Chưa đầy đủ</option><option value="READY">Đã sẵn sàng</option><option value="UNDER_REVIEW">Đang thẩm định</option></select></label><label><span className="sr-only">Refund</span><select value={refund} onChange={(event) => setRefund(event.target.value as "ALL" | ReturnRefundState)}><option value="ALL">Mọi trạng thái Refund</option><option value="NOT_REQUIRED">Không yêu cầu</option><option value="NOT_CREATED">Chưa tạo</option><option value="PENDING">Đang chờ</option><option value="COMPLETED">Đã hoàn</option><option value="FAILED">Thất bại</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setStatus("ALL"); setQuery(""); setCaseType("ALL"); setEvidence("ALL"); setRefund("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> Case</span><span>Cập nhật lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-return-table"><thead><tr><th>Case / Order</th><th>Khách hàng</th><th>Loại yêu cầu</th><th>Trạng thái Case</th><th>Bằng chứng</th><th>Hàng trả</th><th>Refund</th><th>Phụ trách / Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.caseId}><td><strong>{item.caseNumber}</strong><small>{item.orderNumber} · {item.reasonLabel}</small></td><td><strong>{item.customerLabel}</strong><small>{item.channelLabel}</small></td><td><strong>{item.caseTypeLabel}</strong><small>{item.requestedItemCount} dòng/sản phẩm yêu cầu</small></td><td><Status code={item.status} label={item.statusLabel} /></td><td><Status code={item.evidenceState} label={item.evidenceStateLabel} prefix="return-evidence" /><small>{item.evidenceCount} tệp</small></td><td><Status code={item.goodsState} label={item.goodsStateLabel} prefix="return-goods" /></td><td><Status code={item.refundState} label={item.refundStateLabel} prefix="return-refund" /><small>{item.financialMasked ? "Số tiền đã ẩn" : item.refundAmountVnd === null ? "Không phát sinh" : MONEY.format(item.refundAmountVnd)}</small></td><td><strong>{item.assignedTo ?? "Chưa phân công"}</strong><small>{DATE_TIME.format(new Date(item.updatedAt))}</small></td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.caseNumber}`} onClick={() => setMenuId((current) => current === item.caseId ? "" : item.caseId)}>•••</button>{menuId === item.caseId ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có Case phù hợp</h3><p>Hãy thay đổi trạng thái, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Return Case · ${selected.caseNumber}`} subtitle={`${selected.orderNumber} · Revision ${selected.revision}`} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải Order, bằng chứng và Refund…</div> : detail ? <ReturnDetail detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function ReturnDetail({ detail }: { detail: ReturnCaseDetail }) {
  return <div className="admin-return-detail"><div className="admin-detail-summary"><Status code={detail.status} label={detail.statusLabel} /><span>{detail.caseTypeLabel}</span><span>{detail.reasonLabel}</span><span>{detail.assignedTo ?? "Chưa phân công"}</span></div>
    <div className="admin-detail-grid"><section><h3>Case và khách hàng</h3><dl><div><dt>Khách hàng</dt><dd>{detail.customer.displayName}</dd></div><div><dt>Liên hệ</dt><dd>{detail.customer.contactDisplay}</dd></div><div><dt>Kênh tiếp nhận</dt><dd>{detail.channelLabel}</dd></div><div><dt>Tạo lúc</dt><dd>{DATE_TIME.format(new Date(detail.createdAt))}</dd></div><div><dt>Bằng chứng</dt><dd>{detail.evidenceStateLabel}</dd></div></dl></section><section><h3>Order và Shipment</h3><dl><div><dt>Order</dt><dd>{detail.orderNumber}</dd></div><div><dt>Trạng thái</dt><dd>{detail.order.statusLabel}</dd></div><div><dt>Tổng Order</dt><dd>{MONEY.format(detail.order.totalVnd)}</dd></div><div><dt>Shipment</dt><dd>{detail.shipment.statusLabel}</dd></div><div><dt>Bằng chứng giao</dt><dd>{detail.shipment.proofLabel ?? "Không có"}</dd></div></dl></section></div>
    <section><h3>Dòng hàng yêu cầu</h3><div className="admin-table-wrap"><table className="admin-table return-line-table"><thead><tr><th>Sản phẩm / SKU</th><th>Đã mua</th><th>Yêu cầu</th><th>Được duyệt</th><th>Đơn giá</th></tr></thead><tbody>{detail.lines.map((item) => <tr key={item.lineId}><td><strong>{item.productName}</strong><small>{item.skuLabel}</small></td><td>{item.purchasedQuantity}</td><td>{item.requestedQuantity}</td><td>{item.approvedQuantity ?? "Chưa quyết định"}</td><td>{MONEY.format(item.unitPriceVnd)}</td></tr>)}</tbody></table></div></section>
    <section><h3>Bằng chứng khách gửi</h3>{detail.evidenceMasked ? <div className="return-permission-note">Danh sách media đã được che vì phiên hiện tại không có `RETURN_EVIDENCE_VIEW`.</div> : <div className="return-evidence-list">{detail.evidences.map((item) => <article key={item.evidenceId}><span>{item.mediaType.startsWith("video/") ? "▶" : "▧"}</span><div><strong>{item.fileName}</strong><small>{item.storageStateLabel} · {item.submittedByLabel}</small><small>{DATE_TIME.format(new Date(item.submittedAt))}</small></div><em>{item.originalPreserved ? "Bản gốc được bảo toàn" : "Chưa xác nhận bản gốc"}</em></article>)}</div>}</section>
    <div className="admin-detail-grid"><section><h3>Payment</h3><dl><div><dt>Payment ID</dt><dd>{detail.payment.paymentId}</dd></div><div><dt>Trạng thái</dt><dd>{detail.payment.statusLabel}</dd></div><div><dt>Phương thức</dt><dd>{detail.payment.methodLabel}</dd></div><div><dt>Đã thu</dt><dd>{moneyOrPermission(detail.payment.amountPaidVnd)}</dd></div><div><dt>Còn có thể hoàn</dt><dd>{moneyOrPermission(detail.payment.refundableVnd)}</dd></div></dl></section><section><h3>Refund độc lập</h3><dl><div><dt>Refund ID</dt><dd>{detail.refund.refundId ?? "Chưa tạo"}</dd></div><div><dt>Trạng thái</dt><dd>{detail.refund.stateLabel}</dd></div><div><dt>Được duyệt</dt><dd>{moneyOrPermission(detail.refund.approvedAmountVnd)}</dd></div><div><dt>Đã hoàn</dt><dd>{moneyOrPermission(detail.refund.completedAmountVnd)}</dd></div><div><dt>Phương thức</dt><dd>{detail.refund.masked ? "Đã ẩn theo Permission" : detail.refund.methodLabel ?? "Chưa có"}</dd></div></dl></section></div>
    {detail.decision ? <section className="return-decision"><h3>Quyết định hiện tại</h3><strong>{detail.decision.outcomeLabel}</strong><p>{detail.decision.basis ?? "Không có nội dung căn cứ."}</p><small>{detail.decision.decidedBy ?? "Chưa có người quyết định"}{detail.decision.decidedAt ? ` · ${DATE_TIME.format(new Date(detail.decision.decidedAt))}` : ""}</small></section> : null}
    <section><h3>Lịch sử Case</h3><ol className="admin-order-timeline">{detail.history.map((item) => <li key={item.eventId}><span /><div><strong>{item.label}</strong><small>{DATE_TIME.format(new Date(item.occurredAt))} · {item.actorLabel}</small>{item.detail ? <p>{item.detail}</p> : null}</div></li>)}</ol></section>
    <footer>Trạng thái Case, hàng trả, Order, Shipment, Payment và Refund được giữ riêng. Popup hiện chỉ đọc và không tự suy diễn rằng Approved là đã nhận hàng hoặc đã hoàn tiền.</footer>
  </div>;
}
