// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: shipping/v1/shipping.proto

package shippingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShippingService_CalculateShippingFee_FullMethodName = "/omamx.shipping.v1.ShippingService/CalculateShippingFee"
	ShippingService_CreateShipment_FullMethodName       = "/omamx.shipping.v1.ShippingService/CreateShipment"
	ShippingService_TrackShipment_FullMethodName        = "/omamx.shipping.v1.ShippingService/TrackShipment"
)

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingServiceClient interface {
	// Tính toán phí vận chuyển chính xác theo địa chỉ và khối lượng kiện hàng (Critical Path < 30ms)
	CalculateShippingFee(ctx context.Context, in *CalculateShippingFeeRequest, opts ...grpc.CallOption) (*CalculateShippingFeeResponse, error)
	// Tạo phiếu gửi hàng sang đơn vị 3PL (GHN/ViettelPost) sau khi kẹo đã niêm phong xong
	CreateShipment(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*CreateShipmentResponse, error)
	// Tra cứu hành trình vận chuyển thời gian thực của bưu kiện
	TrackShipment(ctx context.Context, in *TrackShipmentRequest, opts ...grpc.CallOption) (*TrackShipmentResponse, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CalculateShippingFee(ctx context.Context, in *CalculateShippingFeeRequest, opts ...grpc.CallOption) (*CalculateShippingFeeResponse, error) {
	out := new(CalculateShippingFeeResponse)
	err := c.cc.Invoke(ctx, ShippingService_CalculateShippingFee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) CreateShipment(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*CreateShipmentResponse, error) {
	out := new(CreateShipmentResponse)
	err := c.cc.Invoke(ctx, ShippingService_CreateShipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) TrackShipment(ctx context.Context, in *TrackShipmentRequest, opts ...grpc.CallOption) (*TrackShipmentResponse, error) {
	out := new(TrackShipmentResponse)
	err := c.cc.Invoke(ctx, ShippingService_TrackShipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
// All implementations must embed UnimplementedShippingServiceServer
// for forward compatibility
type ShippingServiceServer interface {
	// Tính toán phí vận chuyển chính xác theo địa chỉ và khối lượng kiện hàng (Critical Path < 30ms)
	CalculateShippingFee(context.Context, *CalculateShippingFeeRequest) (*CalculateShippingFeeResponse, error)
	// Tạo phiếu gửi hàng sang đơn vị 3PL (GHN/ViettelPost) sau khi kẹo đã niêm phong xong
	CreateShipment(context.Context, *CreateShipmentRequest) (*CreateShipmentResponse, error)
	// Tra cứu hành trình vận chuyển thời gian thực của bưu kiện
	TrackShipment(context.Context, *TrackShipmentRequest) (*TrackShipmentResponse, error)
	mustEmbedUnimplementedShippingServiceServer()
}

// UnimplementedShippingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShippingServiceServer struct {
}

func (UnimplementedShippingServiceServer) CalculateShippingFee(context.Context, *CalculateShippingFeeRequest) (*CalculateShippingFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateShippingFee not implemented")
}
func (UnimplementedShippingServiceServer) CreateShipment(context.Context, *CreateShipmentRequest) (*CreateShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShipment not implemented")
}
func (UnimplementedShippingServiceServer) TrackShipment(context.Context, *TrackShipmentRequest) (*TrackShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackShipment not implemented")
}
func (UnimplementedShippingServiceServer) mustEmbedUnimplementedShippingServiceServer() {}

// UnsafeShippingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingServiceServer will
// result in compilation errors.
type UnsafeShippingServiceServer interface {
	mustEmbedUnimplementedShippingServiceServer()
}

func RegisterShippingServiceServer(s grpc.ServiceRegistrar, srv ShippingServiceServer) {
	s.RegisterService(&ShippingService_ServiceDesc, srv)
}

func _ShippingService_CalculateShippingFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateShippingFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CalculateShippingFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_CalculateShippingFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CalculateShippingFee(ctx, req.(*CalculateShippingFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_CreateShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_CreateShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateShipment(ctx, req.(*CreateShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_TrackShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).TrackShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_TrackShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).TrackShipment(ctx, req.(*TrackShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingService_ServiceDesc is the grpc.ServiceDesc for ShippingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.shipping.v1.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateShippingFee",
			Handler:    _ShippingService_CalculateShippingFee_Handler,
		},
		{
			MethodName: "CreateShipment",
			Handler:    _ShippingService_CreateShipment_Handler,
		},
		{
			MethodName: "TrackShipment",
			Handler:    _ShippingService_TrackShipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping/v1/shipping.proto",
}
