"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { PaymentCaseDetail, PaymentCaseList, PaymentCaseSummary, PaymentRiskState, PaymentStatus, ReconciliationResult } from "@/lib/payments/types";
import { AdminPaymentApiError } from "@/lib/payments/types";
import { adminPaymentService } from "@/services/admin-payment-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
const MONEY = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
function Status({ code, label, prefix = "payment" }: { code: string; label: string; prefix?: string }) { return <span className={`admin-status ${prefix}-${code.toLowerCase()}`}>{label}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function PaymentWorkspace() {
  const [data, setData] = useState<PaymentCaseList | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [result, setResult] = useState<"ALL" | ReconciliationResult>("ALL"); const [query, setQuery] = useState(""); const [method, setMethod] = useState("ALL"); const [paymentStatus, setPaymentStatus] = useState<"ALL" | PaymentStatus>("ALL"); const [risk, setRisk] = useState<"ALL" | PaymentRiskState>("ALL");
  const [menuId, setMenuId] = useState(""); const [selected, setSelected] = useState<PaymentCaseSummary | null>(null); const [detail, setDetail] = useState<PaymentCaseDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminPaymentService.cases()); } catch (cause) { setLoadError(cause instanceof AdminPaymentApiError ? cause.message : "Không thể tải hồ sơ đối soát thanh toán."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("vi"); return data?.items.filter((item) => (result === "ALL" || item.result === result) && (method === "ALL" || item.methodCode === method) && (paymentStatus === "ALL" || item.paymentStatus === paymentStatus) && (risk === "ALL" || item.riskState === risk) && (!needle || [item.caseNumber, item.orderNumber, item.paymentId, item.referenceDisplay ?? ""].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? []; }, [data, method, paymentStatus, query, result, risk]);
  const matched = data?.items.filter((item) => item.result === "MATCHED").length ?? 0;
  const pending = data?.items.filter((item) => item.result === "PENDING").length ?? 0;
  const discrepancy = data?.items.filter((item) => !["MATCHED", "PENDING"].includes(item.result)).length ?? 0;
  async function openDetail(item: PaymentCaseSummary) { setMenuId(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const loaded = await adminPaymentService.case(item.caseId); setDetail({ ...loaded, ...item, order: loaded.order, attempts: loaded.attempts, transactions: loaded.transactions, comparisons: loaded.comparisons, history: loaded.history, originalEvidencePreserved: loaded.originalEvidencePreserved }); } catch (cause) { setDetailError(cause instanceof AdminPaymentApiError ? cause.message : "Không thể tải hồ sơ đối soát."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải thanh toán</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Kinh doanh <span>›</span> Thanh toán</nav><h1>Vận hành thanh toán</h1><p>Đối chiếu Payment với Order và bằng chứng giao dịch theo Epic 07; màn hình hiện chỉ đọc.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Tổng hồ sơ</span><strong>{data.items.length}</strong><small>Payment cần theo dõi trên projection hiện tại</small></article><article><span>Khớp hoàn toàn</span><strong>{matched}</strong><small>Khớp số tiền, tiền tệ, tham chiếu và trạng thái</small></article><article><span>Chờ bằng chứng</span><strong>{pending}</strong><small>Chưa có giao dịch đủ điều kiện xác nhận</small></article><article><span>Có chênh lệch</span><strong>{discrepancy}</strong><small>Cần nhân viên có thẩm quyền xem xét</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc kết quả đối soát">{data.resultCounts.map((item) => <button className={result === item.result ? "active" : ""} type="button" role="tab" aria-selected={result === item.result} onClick={() => setResult(item.result)} key={item.result}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar payment-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm hồ sơ, Order, Payment hoặc tham chiếu…" /></label><label><span className="sr-only">Phương thức</span><select value={method} onChange={(event) => setMethod(event.target.value)}><option value="ALL">Mọi phương thức</option>{data.methods.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label><label><span className="sr-only">Trạng thái Payment</span><select value={paymentStatus} onChange={(event) => setPaymentStatus(event.target.value as "ALL" | PaymentStatus)}><option value="ALL">Mọi trạng thái Payment</option>{data.paymentStatuses.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label><label><span className="sr-only">Rủi ro</span><select value={risk} onChange={(event) => setRisk(event.target.value as "ALL" | PaymentRiskState)}><option value="ALL">Mọi mức chú ý</option><option value="NONE">Bình thường</option><option value="ATTENTION">Cần chú ý</option><option value="BLOCKED">Bị chặn</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setResult("ALL"); setQuery(""); setMethod("ALL"); setPaymentStatus("ALL"); setRisk("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> hồ sơ</span><span>Cập nhật lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-payment-table"><thead><tr><th>Hồ sơ / Order</th><th>Phương thức</th><th>Payment</th><th>Phải thu</th><th>Đã xác nhận</th><th>Order</th><th>Kết quả đối soát</th><th>Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.caseId}><td><strong>{item.caseNumber}</strong><small>{item.orderNumber} · {item.paymentId}</small></td><td><strong>{item.methodLabel}</strong><small>{item.referenceDisplay ?? "Chưa có tham chiếu"}</small></td><td><Status code={item.paymentStatus} label={item.paymentStatusLabel} /><small>{item.transactionCount} giao dịch</small></td><td><strong>{MONEY.format(item.amountDueVnd)}</strong></td><td><strong>{MONEY.format(item.amountConfirmedVnd)}</strong></td><td><strong>{item.orderStatusLabel}</strong><small>{item.orderStatus}</small></td><td><Status code={item.result} label={item.resultLabel} prefix="reconciliation" />{item.riskReason ? <small className="payment-risk-text">{item.riskReason}</small> : null}</td><td>{DATE_TIME.format(new Date(item.updatedAt))}</td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.caseNumber}`} onClick={() => setMenuId((current) => current === item.caseId ? "" : item.caseId)}>•••</button>{menuId === item.caseId ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có hồ sơ phù hợp</h3><p>Hãy thay đổi kết quả, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Đối soát · ${selected.caseNumber}`} subtitle={`${selected.orderNumber} · Revision ${selected.revision}`} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải giao dịch và bằng chứng…</div> : detail ? <PaymentDetail detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function PaymentDetail({ detail }: { detail: PaymentCaseDetail }) {
  return <div className="admin-payment-detail"><div className="admin-detail-summary"><Status code={detail.result} label={detail.resultLabel} prefix="reconciliation" /><span>{detail.methodLabel}</span><span>{detail.paymentStatusLabel}</span><span>{detail.referenceDisplay ?? "Chưa có tham chiếu"}</span></div>{detail.riskReason ? <section className="admin-payment-warning"><strong>{detail.riskLabel}</strong><p>{detail.riskReason}</p></section> : null}
    <div className="admin-detail-grid"><section><h3>Order và nghĩa vụ thanh toán</h3><dl><div><dt>Order</dt><dd>{detail.orderNumber}</dd></div><div><dt>Đặt lúc</dt><dd>{DATE_TIME.format(new Date(detail.order.placedAt))}</dd></div><div><dt>Trạng thái Order</dt><dd>{detail.orderStatusLabel}</dd></div><div><dt>Tổng Order</dt><dd>{MONEY.format(detail.order.totalVnd)}</dd></div><div><dt>Phải thu</dt><dd>{MONEY.format(detail.amountDueVnd)}</dd></div></dl></section><section><h3>Payment</h3><dl><div><dt>Payment ID</dt><dd>{detail.paymentId}</dd></div><div><dt>Phương thức</dt><dd>{detail.methodLabel}</dd></div><div><dt>Trạng thái</dt><dd>{detail.paymentStatusLabel}</dd></div><div><dt>Đã xác nhận</dt><dd>{MONEY.format(detail.amountConfirmedVnd)}</dd></div><div><dt>Số giao dịch</dt><dd>{detail.transactionCount}</dd></div></dl></section></div>
    <section><h3>Kết quả đối chiếu</h3><div className="payment-comparison-grid">{detail.comparisons.map((item) => <article className={item.matched ? "matched" : "mismatched"} key={item.field}><span>{item.matched ? "✓" : "!"}</span><div><strong>{item.label}</strong><small>Mong đợi: {item.expectedDisplay}</small><small>Thực nhận: {item.actualDisplay}</small></div></article>)}</div></section>
    <section><h3>Payment Attempt</h3><div className="admin-table-wrap"><table className="admin-table payment-detail-table"><thead><tr><th>Attempt</th><th>Trạng thái</th><th>Số tiền</th><th>Tạo lúc</th><th>Hết hạn</th></tr></thead><tbody>{detail.attempts.map((item) => <tr key={item.attemptId}><td><strong>{item.attemptId}</strong></td><td>{item.statusLabel}</td><td>{MONEY.format(item.amountVnd)}</td><td>{DATE_TIME.format(new Date(item.createdAt))}</td><td>{item.expiresAt ? DATE_TIME.format(new Date(item.expiresAt)) : "Không có"}</td></tr>)}</tbody></table></div></section>
    <section><h3>Giao dịch xác nhận <small>{detail.transactions.some((item) => item.masked) ? "· Tham chiếu đã che theo Permission" : "· Có quyền xem tham chiếu đầy đủ"}</small></h3><div className="admin-table-wrap"><table className="admin-table payment-detail-table"><thead><tr><th>Giao dịch</th><th>Nguồn</th><th>Tham chiếu</th><th>Số tiền</th><th>Xác minh</th><th>Thời điểm</th></tr></thead><tbody>{detail.transactions.map((item) => <tr key={item.transactionId}><td><strong>{item.transactionId}</strong><small>{item.providerStatusCode}</small></td><td>{item.providerLabel}</td><td><strong>{item.providerReferenceDisplay}</strong><small>{item.bankReferenceDisplay ?? "Không có bank reference"}</small></td><td>{MONEY.format(item.receivedAmountVnd)}</td><td>{item.verified ? "Đã xác minh" : "Chưa xác minh"}{item.duplicate ? <small className="payment-duplicate">Nghi trùng</small> : null}</td><td>{DATE_TIME.format(new Date(item.occurredAt))}</td></tr>)}</tbody></table></div></section>
    <section><h3>Lịch sử hồ sơ</h3><ol className="admin-order-timeline">{detail.history.map((item) => <li key={item.eventId}><span /><div><strong>{item.label}</strong><small>{DATE_TIME.format(new Date(item.occurredAt))} · {item.actorLabel}</small>{item.detail ? <p>{item.detail}</p> : null}</div></li>)}</ol></section>
    <footer>{detail.originalEvidencePreserved ? "Bằng chứng giao dịch gốc được giữ bất biến; màn hình không cho ghi đè hay tự đánh dấu Paid." : "Không có xác nhận về việc bảo toàn bằng chứng gốc."}</footer>
  </div>;
}
