"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { AdminRoleDetail, AdminRoleList, AdminRoleStatus, AdminRoleSummary } from "@/lib/access/types";
import { AdminAccessApiError } from "@/lib/access/types";
import { adminAccessService } from "@/services/admin-access-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });

function RoleStatus({ role }: { role: Pick<AdminRoleSummary, "status" | "statusLabel"> }) { return <span className={`admin-status role-${role.status.toLowerCase()}`}>{role.statusLabel}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function RoleCatalogWorkspace() {
  const [data, setData] = useState<AdminRoleList | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [status, setStatus] = useState<"ALL" | AdminRoleStatus>("ALL");
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState("ALL");
  const [privileged, setPrivileged] = useState("ALL");
  const [menuCode, setMenuCode] = useState("");
  const [selected, setSelected] = useState<AdminRoleSummary | null>(null);
  const [detail, setDetail] = useState<AdminRoleDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminAccessService.roles()); } catch (cause) { setLoadError(cause instanceof AdminAccessApiError ? cause.message : "Không thể tải danh mục Role."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("vi"); return data?.items.filter((item) => (status === "ALL" || item.status === status) && (kind === "ALL" || item.kind === kind) && (privileged === "ALL" || item.privileged === (privileged === "YES")) && (!needle || [item.roleCode, item.roleName, item.description, item.scopeLabel].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? []; }, [data, kind, privileged, query, status]);
  async function openDetail(item: AdminRoleSummary) { setMenuCode(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const result = await adminAccessService.role(item.roleCode); setDetail({ ...result, ...item, protectedRole: item.kind === "SYSTEM" || item.privileged }); } catch (cause) { setDetailError(cause instanceof AdminAccessApiError ? cause.message : "Không thể tải chi tiết Role."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải danh mục Role</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Quản trị <span>›</span> Role</nav><h1>Quản lý Role</h1><p>Kiểm tra nhóm quyền, phạm vi, trạng thái và mức ảnh hưởng trước khi thay đổi cấu hình phân quyền.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Tổng Role</span><strong>{data.items.length}</strong><small>Gồm Role hệ thống và tùy chỉnh</small></article><article><span>Đang hoạt động</span><strong>{data.items.filter((item) => item.status === "ACTIVE").length}</strong><small>Có thể tham gia quyền hiệu lực</small></article><article><span>Role được bảo vệ</span><strong>{data.items.filter((item) => item.kind === "SYSTEM" || item.privileged).length}</strong><small>Không sửa ngoài quy trình đặc biệt</small></article><article><span>Employee đang nhận Role</span><strong>{data.items.reduce((sum, item) => sum + item.employeeCount, 0)}</strong><small>Có thể trùng giữa nhiều Role</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc trạng thái Role">{data.statusCounts.map((item) => <button className={status === item.status ? "active" : ""} type="button" role="tab" aria-selected={status === item.status} onClick={() => setStatus(item.status)} key={item.status}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã, tên, mô tả hoặc phạm vi Role…" /></label><label><span className="sr-only">Loại Role</span><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="ALL">Tất cả loại Role</option><option value="SYSTEM">Role hệ thống</option><option value="CUSTOM">Role tùy chỉnh</option></select></label><label><span className="sr-only">Đặc quyền</span><select value={privileged} onChange={(event) => setPrivileged(event.target.value)}><option value="ALL">Tất cả mức quyền</option><option value="YES">Role đặc quyền</option><option value="NO">Role thông thường</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setQuery(""); setKind("ALL"); setPrivileged("ALL"); setStatus("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> Role</span><span>Tính lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-role-table"><thead><tr><th>Role</th><th>Phạm vi</th><th>Loại</th><th>Trạng thái</th><th>Permission</th><th>Employee</th><th>Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.roleCode}><td><strong>{item.roleName}</strong><small>{item.roleCode}</small></td><td><span>{item.scopeLabel}</span></td><td><span>{item.kind === "SYSTEM" ? "Hệ thống" : "Tùy chỉnh"}{item.privileged ? " · Đặc quyền" : ""}</span></td><td><RoleStatus role={item} /></td><td><strong>{item.permissionCount}</strong><small>permission</small></td><td><strong>{item.employeeCount}</strong><small>assignment hiệu lực</small></td><td>{DATE_TIME.format(new Date(item.updatedAt))}</td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.roleCode}`} onClick={() => setMenuCode((current) => current === item.roleCode ? "" : item.roleCode)}>•••</button>{menuCode === item.roleCode ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết và ảnh hưởng</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có Role phù hợp</h3><p>Hãy thay đổi trạng thái, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Role · ${selected.roleCode}`} subtitle={selected.roleName} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải cấu hình Role…</div> : detail ? <RoleDetailContent detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function RoleDetailContent({ detail }: { detail: AdminRoleDetail }) { return <div className="admin-catalog-detail"><div className="admin-detail-summary"><RoleStatus role={detail} /><span>{detail.kind === "SYSTEM" ? "Role hệ thống" : "Role tùy chỉnh"}</span><span>{detail.scopeLabel}</span></div>{detail.protectedRole ? <section className="admin-protected-notice"><strong>Role được bảo vệ</strong><p>Role này không được sửa, vô hiệu hóa hoặc xóa cứng ngoài quy trình đặc biệt đã được phê duyệt.</p></section> : null}<div className="admin-detail-grid"><section><h3>Thông tin Role</h3><dl><div><dt>Mã Role</dt><dd>{detail.roleCode}</dd></div><div><dt>Tên hiển thị</dt><dd>{detail.roleName}</dd></div><div><dt>Mô tả</dt><dd>{detail.description}</dd></div><div><dt>Phạm vi</dt><dd>{detail.scopeLabel}</dd></div></dl></section><section><h3>Ảnh hưởng hiện tại</h3><dl><div><dt>Employee hiệu lực</dt><dd>{detail.impact.activeEmployees}</dd></div><div><dt>Assignment chờ hiệu lực</dt><dd>{detail.impact.scheduledAssignments}</dd></div><div><dt>Account đang khóa</dt><dd>{detail.impact.lockedAccounts}</dd></div><div><dt>Tổng Permission</dt><dd>{detail.permissions.length}</dd></div></dl></section></div><section><h3>Permission của Role</h3><table className="admin-permission-table"><thead><tr><th>Permission</th><th>Action</th><th>Resource</th><th>Scope</th></tr></thead><tbody>{detail.permissions.map((item) => <tr key={item.permissionCode}><td><strong>{item.permissionName}</strong><small>{item.permissionCode}</small></td><td>{item.action}</td><td>{item.resource}</td><td>{item.scopeLabel}</td></tr>)}</tbody></table></section><footer>Thay đổi tập Permission phải tính lại quyền hiệu lực từ mọi Role còn lại và phát sinh Audit; popup này chưa thực hiện mutation.</footer></div>; }
