// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: inventory/v1/inventory.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { AuditContext } from "../../common/v1/types";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.inventory.v1";

/** Trạng thái của thao tác giữ chỗ tồn kho */
export enum ReservationStatus {
  /** RESERVATION_STATUS_UNSPECIFIED - Giá trị 0 mặc định bắt buộc */
  RESERVATION_STATUS_UNSPECIFIED = 0,
  /** RESERVATION_STATUS_SUCCESS - Khóa tồn thành công toàn bộ mặt hàng */
  RESERVATION_STATUS_SUCCESS = 1,
  /** RESERVATION_STATUS_INSUFFICIENT - Không đủ tồn khả dụng (Hết hàng hoặc thiếu số lượng) */
  RESERVATION_STATUS_INSUFFICIENT = 2,
  /** RESERVATION_STATUS_SKU_NOT_FOUND - Mã SKU không tồn tại trong danh mục kho */
  RESERVATION_STATUS_SKU_NOT_FOUND = 3,
  /** RESERVATION_STATUS_SKU_INACTIVE - Sản phẩm tạm ngưng kinh doanh */
  RESERVATION_STATUS_SKU_INACTIVE = 4,
  UNRECOGNIZED = -1,
}

export function reservationStatusFromJSON(object: any): ReservationStatus {
  switch (object) {
    case 0:
    case "RESERVATION_STATUS_UNSPECIFIED":
      return ReservationStatus.RESERVATION_STATUS_UNSPECIFIED;
    case 1:
    case "RESERVATION_STATUS_SUCCESS":
      return ReservationStatus.RESERVATION_STATUS_SUCCESS;
    case 2:
    case "RESERVATION_STATUS_INSUFFICIENT":
      return ReservationStatus.RESERVATION_STATUS_INSUFFICIENT;
    case 3:
    case "RESERVATION_STATUS_SKU_NOT_FOUND":
      return ReservationStatus.RESERVATION_STATUS_SKU_NOT_FOUND;
    case 4:
    case "RESERVATION_STATUS_SKU_INACTIVE":
      return ReservationStatus.RESERVATION_STATUS_SKU_INACTIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ReservationStatus.UNRECOGNIZED;
  }
}

export function reservationStatusToJSON(object: ReservationStatus): string {
  switch (object) {
    case ReservationStatus.RESERVATION_STATUS_UNSPECIFIED:
      return "RESERVATION_STATUS_UNSPECIFIED";
    case ReservationStatus.RESERVATION_STATUS_SUCCESS:
      return "RESERVATION_STATUS_SUCCESS";
    case ReservationStatus.RESERVATION_STATUS_INSUFFICIENT:
      return "RESERVATION_STATUS_INSUFFICIENT";
    case ReservationStatus.RESERVATION_STATUS_SKU_NOT_FOUND:
      return "RESERVATION_STATUS_SKU_NOT_FOUND";
    case ReservationStatus.RESERVATION_STATUS_SKU_INACTIVE:
      return "RESERVATION_STATUS_SKU_INACTIVE";
    case ReservationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Trạng thái kiểm định chất lượng OCOP của lô kẹo mè xửng */
export enum BatchQualityStatus {
  BATCH_QUALITY_STATUS_UNSPECIFIED = 0,
  /** BATCH_QUALITY_STATUS_QA_TESTING - Đang kiểm định vệ sinh ATTP & độ giòn */
  BATCH_QUALITY_STATUS_QA_TESTING = 1,
  /** BATCH_QUALITY_STATUS_ACTIVE_FEFO - Đạt chuẩn OCOP - Đang lưu hành xuất bán */
  BATCH_QUALITY_STATUS_ACTIVE_FEFO = 2,
  /** BATCH_QUALITY_STATUS_EXPIRING_SOON - Cận date (còn dưới 45 ngày) - Ưu tiên xả hàng */
  BATCH_QUALITY_STATUS_EXPIRING_SOON = 3,
  /** BATCH_QUALITY_STATUS_QUARANTINED - Cách ly tiêu hủy / Đổi trả xưởng */
  BATCH_QUALITY_STATUS_QUARANTINED = 4,
  /** BATCH_QUALITY_STATUS_DEPLETED - Đã xuất bán hết sạch lô */
  BATCH_QUALITY_STATUS_DEPLETED = 5,
  UNRECOGNIZED = -1,
}

export function batchQualityStatusFromJSON(object: any): BatchQualityStatus {
  switch (object) {
    case 0:
    case "BATCH_QUALITY_STATUS_UNSPECIFIED":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_UNSPECIFIED;
    case 1:
    case "BATCH_QUALITY_STATUS_QA_TESTING":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_QA_TESTING;
    case 2:
    case "BATCH_QUALITY_STATUS_ACTIVE_FEFO":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_ACTIVE_FEFO;
    case 3:
    case "BATCH_QUALITY_STATUS_EXPIRING_SOON":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_EXPIRING_SOON;
    case 4:
    case "BATCH_QUALITY_STATUS_QUARANTINED":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_QUARANTINED;
    case 5:
    case "BATCH_QUALITY_STATUS_DEPLETED":
      return BatchQualityStatus.BATCH_QUALITY_STATUS_DEPLETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BatchQualityStatus.UNRECOGNIZED;
  }
}

export function batchQualityStatusToJSON(object: BatchQualityStatus): string {
  switch (object) {
    case BatchQualityStatus.BATCH_QUALITY_STATUS_UNSPECIFIED:
      return "BATCH_QUALITY_STATUS_UNSPECIFIED";
    case BatchQualityStatus.BATCH_QUALITY_STATUS_QA_TESTING:
      return "BATCH_QUALITY_STATUS_QA_TESTING";
    case BatchQualityStatus.BATCH_QUALITY_STATUS_ACTIVE_FEFO:
      return "BATCH_QUALITY_STATUS_ACTIVE_FEFO";
    case BatchQualityStatus.BATCH_QUALITY_STATUS_EXPIRING_SOON:
      return "BATCH_QUALITY_STATUS_EXPIRING_SOON";
    case BatchQualityStatus.BATCH_QUALITY_STATUS_QUARANTINED:
      return "BATCH_QUALITY_STATUS_QUARANTINED";
    case BatchQualityStatus.BATCH_QUALITY_STATUS_DEPLETED:
      return "BATCH_QUALITY_STATUS_DEPLETED";
    case BatchQualityStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Mặt hàng kẹo yêu cầu khóa giữ chỗ */
export interface ReserveItem {
  /** Mã biến thể sản phẩm (Ví dụ: "MX-GION-500G", "MX-DEO-HOMEMADE-300G") */
  skuCode: string;
  /** Số lượng hộp kẹo muốn mua (Bắt buộc > 0) */
  quantity: number;
}

/** Yêu cầu khóa tồn kho */
export interface ReserveStockRequest {
  /** Khóa chống lặp giao dịch (Idempotency Key bắt buộc để retry an toàn) */
  idempotencyKey: string;
  /** Mã định danh đơn hàng cần giữ chỗ (Ví dụ: "ORD-20261015-0042") */
  orderId: string;
  /** Danh sách các mặt hàng kẹo mè xửng cần khóa */
  items: ReserveItem[];
  /** Thời gian giữ chỗ (Mặc định: 15 phút) */
  ttlMinutes: number;
  /** Kênh bán hàng phát sinh yêu cầu (D2C_WEB, MOBILE_APP, SHOPEE, TIKTOK, POS_QUAY) */
  channel: string;
  /** Mã kho xuất phát (Optional - nếu để trống, hệ thống tự động chọn kho mặc định) */
  preferredWarehouseId?: string | undefined;
}

/** Chi tiết mặt hàng bị thiếu hàng khi không thể khóa tồn */
export interface UnavailableItemDetail {
  skuCode: string;
  requestedQuantity: number;
  availableQuantity: number;
}

/** Phản hồi kết quả khóa tồn kho */
export interface ReserveStockResponse {
  /** Trạng thái tổng quát của thao tác giữ chỗ */
  status: ReservationStatus;
  /** Mã phiếu giữ chỗ tồn kho trong cơ sở dữ liệu (UUID chuỗi) */
  reservationId?:
    | string
    | undefined;
  /**
   * Thời điểm chính xác phiếu giữ chỗ sẽ tự động hết hạn nếu chưa thanh toán
   * Tuân thủ chuẩn google.protobuf.Timestamp (Tránh lỗi sai lệch Timezone)
   */
  expiresAt?:
    | Date
    | undefined;
  /** Danh sách các mặt hàng không đáp ứng đủ số lượng (Chỉ có khi status = INSUFFICIENT) */
  unavailableItems: UnavailableItemDetail[];
  /** Chi tiết mã lỗi và thông điệp chuẩn hóa nếu thất bại */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu giải phóng tồn kho đã khóa */
export interface ReleaseReservationRequest {
  /** Khóa chống lặp giao dịch bắt buộc trên mọi lệnh ghi */
  idempotencyKey: string;
  /** Mã đơn hàng tương ứng */
  orderId: string;
  /** Mã phiếu giữ chỗ cần giải phóng */
  reservationId: string;
  /** Lý do giải phóng tồn (Ví dụ: "PAYMENT_TIMEOUT_15M", "USER_CANCELLED", "ORDER_REJECTED") */
  releaseReason: string;
  /** Bối cảnh kiểm toán (Ai thực hiện giải phóng: "SYSTEM_SAGA" hoặc "CUSTOMER") */
  auditContext?: AuditContext | undefined;
}

/** Phản hồi kết quả giải phóng tồn kho */
export interface ReleaseReservationResponse {
  /** Xác nhận đã giải phóng thành công hay chưa */
  isReleased: boolean;
  /** Số lượng mặt hàng đã được cộng hoàn trả lại vào tồn khả dụng */
  totalItemsRestored: number;
  /** Thông điệp kết quả */
  message: string;
}

/** Yêu cầu truy vấn mức tồn kho */
export interface GetStockLevelRequest {
  /** Danh sách mã SKU cần kiểm tra tồn kho */
  skuCodes: string[];
  /** Mã kho cần kiểm tra (Optional - nếu bỏ trống sẽ lấy tổng trên toàn hệ thống) */
  warehouseId?: string | undefined;
}

/** Thông tin mức tồn kho của từng SKU */
export interface StockLevelItem {
  skuCode: string;
  /** Tồn kho vật lý đang có trong các ngăn kệ */
  physicalQuantity: number;
  /** Số lượng đang bị tạm khóa (chờ thanh toán 15m hoặc chờ thợ đóng gói) */
  reservedQuantity: number;
  /** Số lượng kẹo thực tế có thể mở bán cho khách (Available = Physical - Reserved) */
  availableQuantity: number;
  /** Cảnh báo trạng thái tồn kho (Ví dụ: "IN_STOCK", "LOW_STOCK", "OUT_OF_STOCK") */
  stockStatus: string;
}

/** Phản hồi truy vấn mức tồn kho */
export interface GetStockLevelResponse {
  items: StockLevelItem[];
}

/** Yêu cầu tra cứu chi tiết lô hàng FEFO */
export interface GetBatchFEFODetailsRequest {
  skuCode: string;
  warehouseId?: string | undefined;
}

/** Thông tin chi tiết một lô sản xuất kẹo mè xửng */
export interface BatchItemDetail {
  /** Mã số lô sản xuất (Ví dụ: "LOT-OMAMA-20261001-01") */
  batchCode: string;
  /** Ngày sản xuất kẹo tại xưởng Huế */
  manufacturedAt?:
    | Date
    | undefined;
  /** Hạn sử dụng tốt nhất (FEFO Date - căn cứ xuất kho trước) */
  bestBefore?:
    | Date
    | undefined;
  /** Số ngày còn lại trước khi hết hạn */
  daysUntilExpiry: number;
  /** Số lượng hộp kẹo còn lại trong lô này */
  remainingQuantity: number;
  /** Trạng thái chất lượng OCOP */
  qualityStatus: BatchQualityStatus;
  /** Mã tem truy xuất nguồn gốc OCOP gắn kèm lô */
  ocopTraceQrCode: string;
}

/** Phản hồi danh sách lô hàng sắp xếp theo thứ tự FEFO (Hạn dùng gần nhất xếp đầu) */
export interface GetBatchFEFODetailsResponse {
  skuCode: string;
  batches: BatchItemDetail[];
}

function createBaseReserveItem(): ReserveItem {
  return { skuCode: "", quantity: 0 };
}

export const ReserveItem = {
  encode(message: ReserveItem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReserveItem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReserveItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.quantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReserveItem {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: ReserveItem): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReserveItem>, I>>(base?: I): ReserveItem {
    return ReserveItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReserveItem>, I>>(object: I): ReserveItem {
    const message = createBaseReserveItem();
    message.skuCode = object.skuCode ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseReserveStockRequest(): ReserveStockRequest {
  return { idempotencyKey: "", orderId: "", items: [], ttlMinutes: 0, channel: "", preferredWarehouseId: undefined };
}

export const ReserveStockRequest = {
  encode(message: ReserveStockRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    for (const v of message.items) {
      ReserveItem.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    if (message.ttlMinutes !== 0) {
      writer.uint32(32).int32(message.ttlMinutes);
    }
    if (message.channel !== "") {
      writer.uint32(42).string(message.channel);
    }
    if (message.preferredWarehouseId !== undefined) {
      writer.uint32(50).string(message.preferredWarehouseId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReserveStockRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReserveStockRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.items.push(ReserveItem.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.ttlMinutes = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.channel = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.preferredWarehouseId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReserveStockRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => ReserveItem.fromJSON(e)) : [],
      ttlMinutes: isSet(object.ttlMinutes) ? globalThis.Number(object.ttlMinutes) : 0,
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      preferredWarehouseId: isSet(object.preferredWarehouseId)
        ? globalThis.String(object.preferredWarehouseId)
        : undefined,
    };
  },

  toJSON(message: ReserveStockRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => ReserveItem.toJSON(e));
    }
    if (message.ttlMinutes !== 0) {
      obj.ttlMinutes = Math.round(message.ttlMinutes);
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.preferredWarehouseId !== undefined) {
      obj.preferredWarehouseId = message.preferredWarehouseId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReserveStockRequest>, I>>(base?: I): ReserveStockRequest {
    return ReserveStockRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReserveStockRequest>, I>>(object: I): ReserveStockRequest {
    const message = createBaseReserveStockRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.orderId = object.orderId ?? "";
    message.items = object.items?.map((e) => ReserveItem.fromPartial(e)) || [];
    message.ttlMinutes = object.ttlMinutes ?? 0;
    message.channel = object.channel ?? "";
    message.preferredWarehouseId = object.preferredWarehouseId ?? undefined;
    return message;
  },
};

function createBaseUnavailableItemDetail(): UnavailableItemDetail {
  return { skuCode: "", requestedQuantity: 0, availableQuantity: 0 };
}

export const UnavailableItemDetail = {
  encode(message: UnavailableItemDetail, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.requestedQuantity !== 0) {
      writer.uint32(16).int32(message.requestedQuantity);
    }
    if (message.availableQuantity !== 0) {
      writer.uint32(24).int32(message.availableQuantity);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UnavailableItemDetail {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnavailableItemDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.requestedQuantity = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.availableQuantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnavailableItemDetail {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      requestedQuantity: isSet(object.requestedQuantity) ? globalThis.Number(object.requestedQuantity) : 0,
      availableQuantity: isSet(object.availableQuantity) ? globalThis.Number(object.availableQuantity) : 0,
    };
  },

  toJSON(message: UnavailableItemDetail): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.requestedQuantity !== 0) {
      obj.requestedQuantity = Math.round(message.requestedQuantity);
    }
    if (message.availableQuantity !== 0) {
      obj.availableQuantity = Math.round(message.availableQuantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnavailableItemDetail>, I>>(base?: I): UnavailableItemDetail {
    return UnavailableItemDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnavailableItemDetail>, I>>(object: I): UnavailableItemDetail {
    const message = createBaseUnavailableItemDetail();
    message.skuCode = object.skuCode ?? "";
    message.requestedQuantity = object.requestedQuantity ?? 0;
    message.availableQuantity = object.availableQuantity ?? 0;
    return message;
  },
};

function createBaseReserveStockResponse(): ReserveStockResponse {
  return { status: 0, reservationId: undefined, expiresAt: undefined, unavailableItems: [], error: undefined };
}

export const ReserveStockResponse = {
  encode(message: ReserveStockResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.reservationId !== undefined) {
      writer.uint32(18).string(message.reservationId);
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.unavailableItems) {
      UnavailableItemDetail.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReserveStockResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReserveStockResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.reservationId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.unavailableItems.push(UnavailableItemDetail.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReserveStockResponse {
    return {
      status: isSet(object.status) ? reservationStatusFromJSON(object.status) : 0,
      reservationId: isSet(object.reservationId) ? globalThis.String(object.reservationId) : undefined,
      expiresAt: isSet(object.expiresAt) ? fromJsonTimestamp(object.expiresAt) : undefined,
      unavailableItems: globalThis.Array.isArray(object?.unavailableItems)
        ? object.unavailableItems.map((e: any) => UnavailableItemDetail.fromJSON(e))
        : [],
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ReserveStockResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = reservationStatusToJSON(message.status);
    }
    if (message.reservationId !== undefined) {
      obj.reservationId = message.reservationId;
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.unavailableItems?.length) {
      obj.unavailableItems = message.unavailableItems.map((e) => UnavailableItemDetail.toJSON(e));
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReserveStockResponse>, I>>(base?: I): ReserveStockResponse {
    return ReserveStockResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReserveStockResponse>, I>>(object: I): ReserveStockResponse {
    const message = createBaseReserveStockResponse();
    message.status = object.status ?? 0;
    message.reservationId = object.reservationId ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.unavailableItems = object.unavailableItems?.map((e) => UnavailableItemDetail.fromPartial(e)) || [];
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseReleaseReservationRequest(): ReleaseReservationRequest {
  return { idempotencyKey: "", orderId: "", reservationId: "", releaseReason: "", auditContext: undefined };
}

export const ReleaseReservationRequest = {
  encode(message: ReleaseReservationRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.reservationId !== "") {
      writer.uint32(26).string(message.reservationId);
    }
    if (message.releaseReason !== "") {
      writer.uint32(34).string(message.releaseReason);
    }
    if (message.auditContext !== undefined) {
      AuditContext.encode(message.auditContext, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReleaseReservationRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReleaseReservationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.reservationId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.releaseReason = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.auditContext = AuditContext.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReleaseReservationRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      reservationId: isSet(object.reservationId) ? globalThis.String(object.reservationId) : "",
      releaseReason: isSet(object.releaseReason) ? globalThis.String(object.releaseReason) : "",
      auditContext: isSet(object.auditContext) ? AuditContext.fromJSON(object.auditContext) : undefined,
    };
  },

  toJSON(message: ReleaseReservationRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.reservationId !== "") {
      obj.reservationId = message.reservationId;
    }
    if (message.releaseReason !== "") {
      obj.releaseReason = message.releaseReason;
    }
    if (message.auditContext !== undefined) {
      obj.auditContext = AuditContext.toJSON(message.auditContext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReleaseReservationRequest>, I>>(base?: I): ReleaseReservationRequest {
    return ReleaseReservationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReleaseReservationRequest>, I>>(object: I): ReleaseReservationRequest {
    const message = createBaseReleaseReservationRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.orderId = object.orderId ?? "";
    message.reservationId = object.reservationId ?? "";
    message.releaseReason = object.releaseReason ?? "";
    message.auditContext = (object.auditContext !== undefined && object.auditContext !== null)
      ? AuditContext.fromPartial(object.auditContext)
      : undefined;
    return message;
  },
};

function createBaseReleaseReservationResponse(): ReleaseReservationResponse {
  return { isReleased: false, totalItemsRestored: 0, message: "" };
}

export const ReleaseReservationResponse = {
  encode(message: ReleaseReservationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isReleased !== false) {
      writer.uint32(8).bool(message.isReleased);
    }
    if (message.totalItemsRestored !== 0) {
      writer.uint32(16).int32(message.totalItemsRestored);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReleaseReservationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReleaseReservationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isReleased = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.totalItemsRestored = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReleaseReservationResponse {
    return {
      isReleased: isSet(object.isReleased) ? globalThis.Boolean(object.isReleased) : false,
      totalItemsRestored: isSet(object.totalItemsRestored) ? globalThis.Number(object.totalItemsRestored) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ReleaseReservationResponse): unknown {
    const obj: any = {};
    if (message.isReleased !== false) {
      obj.isReleased = message.isReleased;
    }
    if (message.totalItemsRestored !== 0) {
      obj.totalItemsRestored = Math.round(message.totalItemsRestored);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReleaseReservationResponse>, I>>(base?: I): ReleaseReservationResponse {
    return ReleaseReservationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReleaseReservationResponse>, I>>(object: I): ReleaseReservationResponse {
    const message = createBaseReleaseReservationResponse();
    message.isReleased = object.isReleased ?? false;
    message.totalItemsRestored = object.totalItemsRestored ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetStockLevelRequest(): GetStockLevelRequest {
  return { skuCodes: [], warehouseId: undefined };
}

export const GetStockLevelRequest = {
  encode(message: GetStockLevelRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.skuCodes) {
      writer.uint32(10).string(v!);
    }
    if (message.warehouseId !== undefined) {
      writer.uint32(18).string(message.warehouseId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetStockLevelRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStockLevelRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCodes.push(reader.string());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.warehouseId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStockLevelRequest {
    return {
      skuCodes: globalThis.Array.isArray(object?.skuCodes) ? object.skuCodes.map((e: any) => globalThis.String(e)) : [],
      warehouseId: isSet(object.warehouseId) ? globalThis.String(object.warehouseId) : undefined,
    };
  },

  toJSON(message: GetStockLevelRequest): unknown {
    const obj: any = {};
    if (message.skuCodes?.length) {
      obj.skuCodes = message.skuCodes;
    }
    if (message.warehouseId !== undefined) {
      obj.warehouseId = message.warehouseId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStockLevelRequest>, I>>(base?: I): GetStockLevelRequest {
    return GetStockLevelRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStockLevelRequest>, I>>(object: I): GetStockLevelRequest {
    const message = createBaseGetStockLevelRequest();
    message.skuCodes = object.skuCodes?.map((e) => e) || [];
    message.warehouseId = object.warehouseId ?? undefined;
    return message;
  },
};

function createBaseStockLevelItem(): StockLevelItem {
  return { skuCode: "", physicalQuantity: 0, reservedQuantity: 0, availableQuantity: 0, stockStatus: "" };
}

export const StockLevelItem = {
  encode(message: StockLevelItem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.physicalQuantity !== 0) {
      writer.uint32(16).int32(message.physicalQuantity);
    }
    if (message.reservedQuantity !== 0) {
      writer.uint32(24).int32(message.reservedQuantity);
    }
    if (message.availableQuantity !== 0) {
      writer.uint32(32).int32(message.availableQuantity);
    }
    if (message.stockStatus !== "") {
      writer.uint32(42).string(message.stockStatus);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StockLevelItem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStockLevelItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.physicalQuantity = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.reservedQuantity = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.availableQuantity = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.stockStatus = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StockLevelItem {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      physicalQuantity: isSet(object.physicalQuantity) ? globalThis.Number(object.physicalQuantity) : 0,
      reservedQuantity: isSet(object.reservedQuantity) ? globalThis.Number(object.reservedQuantity) : 0,
      availableQuantity: isSet(object.availableQuantity) ? globalThis.Number(object.availableQuantity) : 0,
      stockStatus: isSet(object.stockStatus) ? globalThis.String(object.stockStatus) : "",
    };
  },

  toJSON(message: StockLevelItem): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.physicalQuantity !== 0) {
      obj.physicalQuantity = Math.round(message.physicalQuantity);
    }
    if (message.reservedQuantity !== 0) {
      obj.reservedQuantity = Math.round(message.reservedQuantity);
    }
    if (message.availableQuantity !== 0) {
      obj.availableQuantity = Math.round(message.availableQuantity);
    }
    if (message.stockStatus !== "") {
      obj.stockStatus = message.stockStatus;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StockLevelItem>, I>>(base?: I): StockLevelItem {
    return StockLevelItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StockLevelItem>, I>>(object: I): StockLevelItem {
    const message = createBaseStockLevelItem();
    message.skuCode = object.skuCode ?? "";
    message.physicalQuantity = object.physicalQuantity ?? 0;
    message.reservedQuantity = object.reservedQuantity ?? 0;
    message.availableQuantity = object.availableQuantity ?? 0;
    message.stockStatus = object.stockStatus ?? "";
    return message;
  },
};

function createBaseGetStockLevelResponse(): GetStockLevelResponse {
  return { items: [] };
}

export const GetStockLevelResponse = {
  encode(message: GetStockLevelResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.items) {
      StockLevelItem.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetStockLevelResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStockLevelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.items.push(StockLevelItem.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStockLevelResponse {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => StockLevelItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetStockLevelResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => StockLevelItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStockLevelResponse>, I>>(base?: I): GetStockLevelResponse {
    return GetStockLevelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStockLevelResponse>, I>>(object: I): GetStockLevelResponse {
    const message = createBaseGetStockLevelResponse();
    message.items = object.items?.map((e) => StockLevelItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetBatchFEFODetailsRequest(): GetBatchFEFODetailsRequest {
  return { skuCode: "", warehouseId: undefined };
}

export const GetBatchFEFODetailsRequest = {
  encode(message: GetBatchFEFODetailsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.warehouseId !== undefined) {
      writer.uint32(18).string(message.warehouseId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBatchFEFODetailsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatchFEFODetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.warehouseId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBatchFEFODetailsRequest {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      warehouseId: isSet(object.warehouseId) ? globalThis.String(object.warehouseId) : undefined,
    };
  },

  toJSON(message: GetBatchFEFODetailsRequest): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.warehouseId !== undefined) {
      obj.warehouseId = message.warehouseId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBatchFEFODetailsRequest>, I>>(base?: I): GetBatchFEFODetailsRequest {
    return GetBatchFEFODetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBatchFEFODetailsRequest>, I>>(object: I): GetBatchFEFODetailsRequest {
    const message = createBaseGetBatchFEFODetailsRequest();
    message.skuCode = object.skuCode ?? "";
    message.warehouseId = object.warehouseId ?? undefined;
    return message;
  },
};

function createBaseBatchItemDetail(): BatchItemDetail {
  return {
    batchCode: "",
    manufacturedAt: undefined,
    bestBefore: undefined,
    daysUntilExpiry: 0,
    remainingQuantity: 0,
    qualityStatus: 0,
    ocopTraceQrCode: "",
  };
}

export const BatchItemDetail = {
  encode(message: BatchItemDetail, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.batchCode !== "") {
      writer.uint32(10).string(message.batchCode);
    }
    if (message.manufacturedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.manufacturedAt), writer.uint32(18).fork()).ldelim();
    }
    if (message.bestBefore !== undefined) {
      Timestamp.encode(toTimestamp(message.bestBefore), writer.uint32(26).fork()).ldelim();
    }
    if (message.daysUntilExpiry !== 0) {
      writer.uint32(32).int32(message.daysUntilExpiry);
    }
    if (message.remainingQuantity !== 0) {
      writer.uint32(40).int32(message.remainingQuantity);
    }
    if (message.qualityStatus !== 0) {
      writer.uint32(48).int32(message.qualityStatus);
    }
    if (message.ocopTraceQrCode !== "") {
      writer.uint32(58).string(message.ocopTraceQrCode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BatchItemDetail {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatchItemDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.batchCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.manufacturedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bestBefore = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.daysUntilExpiry = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.remainingQuantity = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.qualityStatus = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.ocopTraceQrCode = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BatchItemDetail {
    return {
      batchCode: isSet(object.batchCode) ? globalThis.String(object.batchCode) : "",
      manufacturedAt: isSet(object.manufacturedAt) ? fromJsonTimestamp(object.manufacturedAt) : undefined,
      bestBefore: isSet(object.bestBefore) ? fromJsonTimestamp(object.bestBefore) : undefined,
      daysUntilExpiry: isSet(object.daysUntilExpiry) ? globalThis.Number(object.daysUntilExpiry) : 0,
      remainingQuantity: isSet(object.remainingQuantity) ? globalThis.Number(object.remainingQuantity) : 0,
      qualityStatus: isSet(object.qualityStatus) ? batchQualityStatusFromJSON(object.qualityStatus) : 0,
      ocopTraceQrCode: isSet(object.ocopTraceQrCode) ? globalThis.String(object.ocopTraceQrCode) : "",
    };
  },

  toJSON(message: BatchItemDetail): unknown {
    const obj: any = {};
    if (message.batchCode !== "") {
      obj.batchCode = message.batchCode;
    }
    if (message.manufacturedAt !== undefined) {
      obj.manufacturedAt = message.manufacturedAt.toISOString();
    }
    if (message.bestBefore !== undefined) {
      obj.bestBefore = message.bestBefore.toISOString();
    }
    if (message.daysUntilExpiry !== 0) {
      obj.daysUntilExpiry = Math.round(message.daysUntilExpiry);
    }
    if (message.remainingQuantity !== 0) {
      obj.remainingQuantity = Math.round(message.remainingQuantity);
    }
    if (message.qualityStatus !== 0) {
      obj.qualityStatus = batchQualityStatusToJSON(message.qualityStatus);
    }
    if (message.ocopTraceQrCode !== "") {
      obj.ocopTraceQrCode = message.ocopTraceQrCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BatchItemDetail>, I>>(base?: I): BatchItemDetail {
    return BatchItemDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BatchItemDetail>, I>>(object: I): BatchItemDetail {
    const message = createBaseBatchItemDetail();
    message.batchCode = object.batchCode ?? "";
    message.manufacturedAt = object.manufacturedAt ?? undefined;
    message.bestBefore = object.bestBefore ?? undefined;
    message.daysUntilExpiry = object.daysUntilExpiry ?? 0;
    message.remainingQuantity = object.remainingQuantity ?? 0;
    message.qualityStatus = object.qualityStatus ?? 0;
    message.ocopTraceQrCode = object.ocopTraceQrCode ?? "";
    return message;
  },
};

function createBaseGetBatchFEFODetailsResponse(): GetBatchFEFODetailsResponse {
  return { skuCode: "", batches: [] };
}

export const GetBatchFEFODetailsResponse = {
  encode(message: GetBatchFEFODetailsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    for (const v of message.batches) {
      BatchItemDetail.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetBatchFEFODetailsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBatchFEFODetailsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.batches.push(BatchItemDetail.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBatchFEFODetailsResponse {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      batches: globalThis.Array.isArray(object?.batches)
        ? object.batches.map((e: any) => BatchItemDetail.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetBatchFEFODetailsResponse): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.batches?.length) {
      obj.batches = message.batches.map((e) => BatchItemDetail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBatchFEFODetailsResponse>, I>>(base?: I): GetBatchFEFODetailsResponse {
    return GetBatchFEFODetailsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBatchFEFODetailsResponse>, I>>(object: I): GetBatchFEFODetailsResponse {
    const message = createBaseGetBatchFEFODetailsResponse();
    message.skuCode = object.skuCode ?? "";
    message.batches = object.batches?.map((e) => BatchItemDetail.fromPartial(e)) || [];
    return message;
  },
};

export type InventoryServiceService = typeof InventoryServiceService;
export const InventoryServiceService = {
  /**
   * Khóa giữ chỗ tồn kho tức thời trong 15 phút (Command Critical Path < 20ms)
   * Chỉ duy nhất MS-04 Order Saga Orchestrator được quyền gọi RPC này
   */
  reserveStock: {
    path: "/omamx.inventory.v1.InventoryService/ReserveStock",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReserveStockRequest) => Buffer.from(ReserveStockRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReserveStockRequest.decode(value),
    responseSerialize: (value: ReserveStockResponse) => Buffer.from(ReserveStockResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ReserveStockResponse.decode(value),
  },
  /**
   * Giải phóng tồn kho khóa tạm khi đơn hàng bị hủy hoặc quá hạn 15 phút
   * Kích hoạt bởi cơ chế Centralized Compensation của MS-04
   */
  releaseReservation: {
    path: "/omamx.inventory.v1.InventoryService/ReleaseReservation",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReleaseReservationRequest) =>
      Buffer.from(ReleaseReservationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReleaseReservationRequest.decode(value),
    responseSerialize: (value: ReleaseReservationResponse) =>
      Buffer.from(ReleaseReservationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ReleaseReservationResponse.decode(value),
  },
  /** Truy vấn số lượng tồn kho vật lý và khả dụng theo danh sách mã SKU */
  getStockLevel: {
    path: "/omamx.inventory.v1.InventoryService/GetStockLevel",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetStockLevelRequest) => Buffer.from(GetStockLevelRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetStockLevelRequest.decode(value),
    responseSerialize: (value: GetStockLevelResponse) => Buffer.from(GetStockLevelResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetStockLevelResponse.decode(value),
  },
  /** Truy vấn thông tin lô hàng kẹo mè xửng theo chiến lược FEFO (First Expired, First Out) */
  getBatchFefoDetails: {
    path: "/omamx.inventory.v1.InventoryService/GetBatchFEFODetails",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetBatchFEFODetailsRequest) =>
      Buffer.from(GetBatchFEFODetailsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetBatchFEFODetailsRequest.decode(value),
    responseSerialize: (value: GetBatchFEFODetailsResponse) =>
      Buffer.from(GetBatchFEFODetailsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetBatchFEFODetailsResponse.decode(value),
  },
} as const;

export interface InventoryServiceServer extends UntypedServiceImplementation {
  /**
   * Khóa giữ chỗ tồn kho tức thời trong 15 phút (Command Critical Path < 20ms)
   * Chỉ duy nhất MS-04 Order Saga Orchestrator được quyền gọi RPC này
   */
  reserveStock: handleUnaryCall<ReserveStockRequest, ReserveStockResponse>;
  /**
   * Giải phóng tồn kho khóa tạm khi đơn hàng bị hủy hoặc quá hạn 15 phút
   * Kích hoạt bởi cơ chế Centralized Compensation của MS-04
   */
  releaseReservation: handleUnaryCall<ReleaseReservationRequest, ReleaseReservationResponse>;
  /** Truy vấn số lượng tồn kho vật lý và khả dụng theo danh sách mã SKU */
  getStockLevel: handleUnaryCall<GetStockLevelRequest, GetStockLevelResponse>;
  /** Truy vấn thông tin lô hàng kẹo mè xửng theo chiến lược FEFO (First Expired, First Out) */
  getBatchFefoDetails: handleUnaryCall<GetBatchFEFODetailsRequest, GetBatchFEFODetailsResponse>;
}

export interface InventoryServiceClient extends Client {
  /**
   * Khóa giữ chỗ tồn kho tức thời trong 15 phút (Command Critical Path < 20ms)
   * Chỉ duy nhất MS-04 Order Saga Orchestrator được quyền gọi RPC này
   */
  reserveStock(
    request: ReserveStockRequest,
    callback: (error: ServiceError | null, response: ReserveStockResponse) => void,
  ): ClientUnaryCall;
  reserveStock(
    request: ReserveStockRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReserveStockResponse) => void,
  ): ClientUnaryCall;
  reserveStock(
    request: ReserveStockRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReserveStockResponse) => void,
  ): ClientUnaryCall;
  /**
   * Giải phóng tồn kho khóa tạm khi đơn hàng bị hủy hoặc quá hạn 15 phút
   * Kích hoạt bởi cơ chế Centralized Compensation của MS-04
   */
  releaseReservation(
    request: ReleaseReservationRequest,
    callback: (error: ServiceError | null, response: ReleaseReservationResponse) => void,
  ): ClientUnaryCall;
  releaseReservation(
    request: ReleaseReservationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReleaseReservationResponse) => void,
  ): ClientUnaryCall;
  releaseReservation(
    request: ReleaseReservationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReleaseReservationResponse) => void,
  ): ClientUnaryCall;
  /** Truy vấn số lượng tồn kho vật lý và khả dụng theo danh sách mã SKU */
  getStockLevel(
    request: GetStockLevelRequest,
    callback: (error: ServiceError | null, response: GetStockLevelResponse) => void,
  ): ClientUnaryCall;
  getStockLevel(
    request: GetStockLevelRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetStockLevelResponse) => void,
  ): ClientUnaryCall;
  getStockLevel(
    request: GetStockLevelRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetStockLevelResponse) => void,
  ): ClientUnaryCall;
  /** Truy vấn thông tin lô hàng kẹo mè xửng theo chiến lược FEFO (First Expired, First Out) */
  getBatchFefoDetails(
    request: GetBatchFEFODetailsRequest,
    callback: (error: ServiceError | null, response: GetBatchFEFODetailsResponse) => void,
  ): ClientUnaryCall;
  getBatchFefoDetails(
    request: GetBatchFEFODetailsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetBatchFEFODetailsResponse) => void,
  ): ClientUnaryCall;
  getBatchFefoDetails(
    request: GetBatchFEFODetailsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetBatchFEFODetailsResponse) => void,
  ): ClientUnaryCall;
}

export const InventoryServiceClient = makeGenericClientConstructor(
  InventoryServiceService,
  "omamx.inventory.v1.InventoryService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InventoryServiceClient;
  service: typeof InventoryServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
