// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InventoryService_ReserveStock_FullMethodName        = "/omamx.inventory.v1.InventoryService/ReserveStock"
	InventoryService_ReleaseReservation_FullMethodName  = "/omamx.inventory.v1.InventoryService/ReleaseReservation"
	InventoryService_GetStockLevel_FullMethodName       = "/omamx.inventory.v1.InventoryService/GetStockLevel"
	InventoryService_GetBatchFEFODetails_FullMethodName = "/omamx.inventory.v1.InventoryService/GetBatchFEFODetails"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// Khóa giữ chỗ tồn kho tức thời trong 15 phút (Command Critical Path < 20ms)
	// Chỉ duy nhất MS-04 Order Saga Orchestrator được quyền gọi RPC này
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
	// Giải phóng tồn kho khóa tạm khi đơn hàng bị hủy hoặc quá hạn 15 phút
	// Kích hoạt bởi cơ chế Centralized Compensation của MS-04
	ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error)
	// Truy vấn số lượng tồn kho vật lý và khả dụng theo danh sách mã SKU
	GetStockLevel(ctx context.Context, in *GetStockLevelRequest, opts ...grpc.CallOption) (*GetStockLevelResponse, error)
	// Truy vấn thông tin lô hàng kẹo mè xửng theo chiến lược FEFO (First Expired, First Out)
	GetBatchFEFODetails(ctx context.Context, in *GetBatchFEFODetailsRequest, opts ...grpc.CallOption) (*GetBatchFEFODetailsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	out := new(ReserveStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReserveStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error) {
	out := new(ReleaseReservationResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseReservation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetStockLevel(ctx context.Context, in *GetStockLevelRequest, opts ...grpc.CallOption) (*GetStockLevelResponse, error) {
	out := new(GetStockLevelResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStockLevel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetBatchFEFODetails(ctx context.Context, in *GetBatchFEFODetailsRequest, opts ...grpc.CallOption) (*GetBatchFEFODetailsResponse, error) {
	out := new(GetBatchFEFODetailsResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetBatchFEFODetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	// Khóa giữ chỗ tồn kho tức thời trong 15 phút (Command Critical Path < 20ms)
	// Chỉ duy nhất MS-04 Order Saga Orchestrator được quyền gọi RPC này
	ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error)
	// Giải phóng tồn kho khóa tạm khi đơn hàng bị hủy hoặc quá hạn 15 phút
	// Kích hoạt bởi cơ chế Centralized Compensation của MS-04
	ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error)
	// Truy vấn số lượng tồn kho vật lý và khả dụng theo danh sách mã SKU
	GetStockLevel(context.Context, *GetStockLevelRequest) (*GetStockLevelResponse, error)
	// Truy vấn thông tin lô hàng kẹo mè xửng theo chiến lược FEFO (First Expired, First Out)
	GetBatchFEFODetails(context.Context, *GetBatchFEFODetailsRequest) (*GetBatchFEFODetailsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseReservation not implemented")
}
func (UnimplementedInventoryServiceServer) GetStockLevel(context.Context, *GetStockLevelRequest) (*GetStockLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockLevel not implemented")
}
func (UnimplementedInventoryServiceServer) GetBatchFEFODetails(context.Context, *GetBatchFEFODetailsRequest) (*GetBatchFEFODetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchFEFODetails not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseReservation(ctx, req.(*ReleaseReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetStockLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStockLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStockLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStockLevel(ctx, req.(*GetStockLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetBatchFEFODetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchFEFODetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetBatchFEFODetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetBatchFEFODetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetBatchFEFODetails(ctx, req.(*GetBatchFEFODetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveStock",
			Handler:    _InventoryService_ReserveStock_Handler,
		},
		{
			MethodName: "ReleaseReservation",
			Handler:    _InventoryService_ReleaseReservation_Handler,
		},
		{
			MethodName: "GetStockLevel",
			Handler:    _InventoryService_GetStockLevel_Handler,
		},
		{
			MethodName: "GetBatchFEFODetails",
			Handler:    _InventoryService_GetBatchFEFODetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
