// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: common/v1/errors.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "omamx.common.v1";

export enum ErrorCode {
  /** ERROR_CODE_UNSPECIFIED - 0 BẮT BUỘC là UNSPECIFIED (Tuân thủ luật cứng của Protobuf3) */
  ERROR_CODE_UNSPECIFIED = 0,
  /** ERR_INTERNAL_SERVER_ERROR - --- LỖI HỆ THỐNG DÙNG CHUNG (1 - 99) --- */
  ERR_INTERNAL_SERVER_ERROR = 1,
  ERR_INVALID_ARGUMENT = 2,
  ERR_UNAUTHENTICATED = 3,
  ERR_PERMISSION_DENIED = 4,
  ERR_RESOURCE_NOT_FOUND = 5,
  /** ERR_IDEMPOTENCY_CONFLICT - Trùng Idempotency Key nhưng payload gửi lên khác bản ghi trước */
  ERR_IDEMPOTENCY_CONFLICT = 6,
  /** ERR_CIRCUIT_BREAKER_OPEN - Cầu dao bảo vệ dịch vụ đang ngắt mạch */
  ERR_CIRCUIT_BREAKER_OPEN = 7,
  /** ERR_DEADLINE_EXCEEDED - Quá thời gian chờ phản hồi (Strict Timeout 2.0s) */
  ERR_DEADLINE_EXCEEDED = 8,
  /** ERR_INVENTORY_INSUFFICIENT_STOCK - --- LỖI MIỀN TỒN KHO & LÔ HÀNG (MS-01: INVENTORY - 100 - 199) --- */
  ERR_INVENTORY_INSUFFICIENT_STOCK = 100,
  /** ERR_INVENTORY_SKU_NOT_FOUND - Không tìm thấy mã sản phẩm trong kho */
  ERR_INVENTORY_SKU_NOT_FOUND = 101,
  /** ERR_INVENTORY_SKU_INACTIVE - Mặt hàng kẹo đã ngừng sản xuất / ngừng bán */
  ERR_INVENTORY_SKU_INACTIVE = 102,
  /** ERR_INVENTORY_RESERVATION_NOT_FOUND - Không tìm thấy phiếu khóa tồn kho */
  ERR_INVENTORY_RESERVATION_NOT_FOUND = 103,
  /** ERR_INVENTORY_RESERVATION_EXPIRED - Phiếu giữ chỗ đã hết hạn 15 phút */
  ERR_INVENTORY_RESERVATION_EXPIRED = 104,
  /** ERR_INVENTORY_BATCH_QUARANTINED - Lô kẹo đang bị cách ly kiểm định / cận date tiêu hủy */
  ERR_INVENTORY_BATCH_QUARANTINED = 105,
  /** ERR_CATALOG_PRICE_TAMPERED - --- LỖI MIỀN DANH MỤC & GIÁ (MS-05: CATALOG - 200 - 299) --- */
  ERR_CATALOG_PRICE_TAMPERED = 200,
  /** ERR_CATALOG_PRODUCT_OUT_OF_SEASON - Kẹo mùa vụ (ví dụ: Mè xửng truyền thống Tết) chưa mở bán */
  ERR_CATALOG_PRODUCT_OUT_OF_SEASON = 201,
  /** ERR_CATALOG_VARIANT_MISMATCH - Biến thể SKU không khớp với sản phẩm cha */
  ERR_CATALOG_VARIANT_MISMATCH = 202,
  /** ERR_PROMOTION_VOUCHER_NOT_FOUND - --- LỖI MIỀN KHUYẾN MÃI & VOUCHER (MS-07: PROMOTION - 300 - 399) --- */
  ERR_PROMOTION_VOUCHER_NOT_FOUND = 300,
  /** ERR_PROMOTION_VOUCHER_EXPIRED - Mã giảm giá đã hết hạn sử dụng */
  ERR_PROMOTION_VOUCHER_EXPIRED = 301,
  /** ERR_PROMOTION_USAGE_LIMIT_EXCEEDED - Voucher đã hết lượt sử dụng trên toàn hệ thống / trên tài khoản */
  ERR_PROMOTION_USAGE_LIMIT_EXCEEDED = 302,
  /** ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET - Giá trị đơn hàng chưa đạt mức tối thiểu áp mã */
  ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET = 303,
  /** ERR_PROMOTION_VOUCHER_ALREADY_LOCKED - Voucher đang bị tạm giữ bởi một giao dịch checkout khác */
  ERR_PROMOTION_VOUCHER_ALREADY_LOCKED = 304,
  /** ERR_ORDER_NOT_FOUND - --- LỖI MIỀN ĐƠN HÀNG & SAGA (MS-04: ORDER - 400 - 499) --- */
  ERR_ORDER_NOT_FOUND = 400,
  /** ERR_ORDER_INVALID_STATE_TRANSITION - Chuyển trạng thái đơn không hợp lệ (Ví dụ: Đã CANCELLED mà đòi PAID) */
  ERR_ORDER_INVALID_STATE_TRANSITION = 401,
  /** ERR_ORDER_ALREADY_PAID - Đơn hàng này đã được thanh toán trước đó */
  ERR_ORDER_ALREADY_PAID = 402,
  /** ERR_ORDER_PAYMENT_TIMEOUT - Đơn hàng bị hủy tự động do quá hạn thanh toán 15 phút */
  ERR_ORDER_PAYMENT_TIMEOUT = 403,
  /** ERR_ORDER_CANCELLED_BY_USER - Khách hàng chủ động hủy đơn */
  ERR_ORDER_CANCELLED_BY_USER = 404,
  /** ERR_ORDER_SAGA_COMPENSATION_FAILED - Đền bù phân tán gặp sự cố (Cần can thiệp vận hành) */
  ERR_ORDER_SAGA_COMPENSATION_FAILED = 405,
  /** ERR_PAYMENT_GATEWAY_UNAVAILABLE - --- LỖI MIỀN THANH TOÁN (MS-19 / PAYMENT MODULE - 500 - 599) --- */
  ERR_PAYMENT_GATEWAY_UNAVAILABLE = 500,
  /** ERR_PAYMENT_HMAC_VERIFICATION_FAILED - Chữ ký bảo mật Webhook ngân hàng không hợp lệ */
  ERR_PAYMENT_HMAC_VERIFICATION_FAILED = 501,
  /** ERR_PAYMENT_AMOUNT_MISMATCH - Số tiền ngân hàng báo về không khớp với giá trị đơn hàng */
  ERR_PAYMENT_AMOUNT_MISMATCH = 502,
  /** ERR_PAYMENT_TRANSACTION_EXPIRED - Giao dịch thanh toán hết hiệu lực */
  ERR_PAYMENT_TRANSACTION_EXPIRED = 503,
  /** ERR_SHIPPING_SERVICE_UNAVAILABLE - --- LỖI MIỀN VẬN CHUYỂN (MS-12: SHIPPING - 600 - 699) --- */
  ERR_SHIPPING_SERVICE_UNAVAILABLE = 600,
  /** ERR_SHIPPING_ADDRESS_UNSUPPORTED - Địa chỉ nằm ngoài phạm vi giao hàng */
  ERR_SHIPPING_ADDRESS_UNSUPPORTED = 601,
  /** ERR_SHIPPING_WEIGHT_EXCEEDED - Kiện kẹo vượt quá trọng lượng tối đa của một bưu kiện */
  ERR_SHIPPING_WEIGHT_EXCEEDED = 602,
  /** ERR_FULFILLMENT_VIDEO_NOT_FOUND - --- LỖI MIỀN FULFILLMENT & TEM SEAL (MS-02: FULFILLMENT - 700 - 799) --- */
  ERR_FULFILLMENT_VIDEO_NOT_FOUND = 700,
  /** ERR_FULFILLMENT_SEAL_CODE_INVALID - Mã tem seal O Mạ trên kiện hàng không khớp hệ thống */
  ERR_FULFILLMENT_SEAL_CODE_INVALID = 701,
  UNRECOGNIZED = -1,
}

export function errorCodeFromJSON(object: any): ErrorCode {
  switch (object) {
    case 0:
    case "ERROR_CODE_UNSPECIFIED":
      return ErrorCode.ERROR_CODE_UNSPECIFIED;
    case 1:
    case "ERR_INTERNAL_SERVER_ERROR":
      return ErrorCode.ERR_INTERNAL_SERVER_ERROR;
    case 2:
    case "ERR_INVALID_ARGUMENT":
      return ErrorCode.ERR_INVALID_ARGUMENT;
    case 3:
    case "ERR_UNAUTHENTICATED":
      return ErrorCode.ERR_UNAUTHENTICATED;
    case 4:
    case "ERR_PERMISSION_DENIED":
      return ErrorCode.ERR_PERMISSION_DENIED;
    case 5:
    case "ERR_RESOURCE_NOT_FOUND":
      return ErrorCode.ERR_RESOURCE_NOT_FOUND;
    case 6:
    case "ERR_IDEMPOTENCY_CONFLICT":
      return ErrorCode.ERR_IDEMPOTENCY_CONFLICT;
    case 7:
    case "ERR_CIRCUIT_BREAKER_OPEN":
      return ErrorCode.ERR_CIRCUIT_BREAKER_OPEN;
    case 8:
    case "ERR_DEADLINE_EXCEEDED":
      return ErrorCode.ERR_DEADLINE_EXCEEDED;
    case 100:
    case "ERR_INVENTORY_INSUFFICIENT_STOCK":
      return ErrorCode.ERR_INVENTORY_INSUFFICIENT_STOCK;
    case 101:
    case "ERR_INVENTORY_SKU_NOT_FOUND":
      return ErrorCode.ERR_INVENTORY_SKU_NOT_FOUND;
    case 102:
    case "ERR_INVENTORY_SKU_INACTIVE":
      return ErrorCode.ERR_INVENTORY_SKU_INACTIVE;
    case 103:
    case "ERR_INVENTORY_RESERVATION_NOT_FOUND":
      return ErrorCode.ERR_INVENTORY_RESERVATION_NOT_FOUND;
    case 104:
    case "ERR_INVENTORY_RESERVATION_EXPIRED":
      return ErrorCode.ERR_INVENTORY_RESERVATION_EXPIRED;
    case 105:
    case "ERR_INVENTORY_BATCH_QUARANTINED":
      return ErrorCode.ERR_INVENTORY_BATCH_QUARANTINED;
    case 200:
    case "ERR_CATALOG_PRICE_TAMPERED":
      return ErrorCode.ERR_CATALOG_PRICE_TAMPERED;
    case 201:
    case "ERR_CATALOG_PRODUCT_OUT_OF_SEASON":
      return ErrorCode.ERR_CATALOG_PRODUCT_OUT_OF_SEASON;
    case 202:
    case "ERR_CATALOG_VARIANT_MISMATCH":
      return ErrorCode.ERR_CATALOG_VARIANT_MISMATCH;
    case 300:
    case "ERR_PROMOTION_VOUCHER_NOT_FOUND":
      return ErrorCode.ERR_PROMOTION_VOUCHER_NOT_FOUND;
    case 301:
    case "ERR_PROMOTION_VOUCHER_EXPIRED":
      return ErrorCode.ERR_PROMOTION_VOUCHER_EXPIRED;
    case 302:
    case "ERR_PROMOTION_USAGE_LIMIT_EXCEEDED":
      return ErrorCode.ERR_PROMOTION_USAGE_LIMIT_EXCEEDED;
    case 303:
    case "ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET":
      return ErrorCode.ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET;
    case 304:
    case "ERR_PROMOTION_VOUCHER_ALREADY_LOCKED":
      return ErrorCode.ERR_PROMOTION_VOUCHER_ALREADY_LOCKED;
    case 400:
    case "ERR_ORDER_NOT_FOUND":
      return ErrorCode.ERR_ORDER_NOT_FOUND;
    case 401:
    case "ERR_ORDER_INVALID_STATE_TRANSITION":
      return ErrorCode.ERR_ORDER_INVALID_STATE_TRANSITION;
    case 402:
    case "ERR_ORDER_ALREADY_PAID":
      return ErrorCode.ERR_ORDER_ALREADY_PAID;
    case 403:
    case "ERR_ORDER_PAYMENT_TIMEOUT":
      return ErrorCode.ERR_ORDER_PAYMENT_TIMEOUT;
    case 404:
    case "ERR_ORDER_CANCELLED_BY_USER":
      return ErrorCode.ERR_ORDER_CANCELLED_BY_USER;
    case 405:
    case "ERR_ORDER_SAGA_COMPENSATION_FAILED":
      return ErrorCode.ERR_ORDER_SAGA_COMPENSATION_FAILED;
    case 500:
    case "ERR_PAYMENT_GATEWAY_UNAVAILABLE":
      return ErrorCode.ERR_PAYMENT_GATEWAY_UNAVAILABLE;
    case 501:
    case "ERR_PAYMENT_HMAC_VERIFICATION_FAILED":
      return ErrorCode.ERR_PAYMENT_HMAC_VERIFICATION_FAILED;
    case 502:
    case "ERR_PAYMENT_AMOUNT_MISMATCH":
      return ErrorCode.ERR_PAYMENT_AMOUNT_MISMATCH;
    case 503:
    case "ERR_PAYMENT_TRANSACTION_EXPIRED":
      return ErrorCode.ERR_PAYMENT_TRANSACTION_EXPIRED;
    case 600:
    case "ERR_SHIPPING_SERVICE_UNAVAILABLE":
      return ErrorCode.ERR_SHIPPING_SERVICE_UNAVAILABLE;
    case 601:
    case "ERR_SHIPPING_ADDRESS_UNSUPPORTED":
      return ErrorCode.ERR_SHIPPING_ADDRESS_UNSUPPORTED;
    case 602:
    case "ERR_SHIPPING_WEIGHT_EXCEEDED":
      return ErrorCode.ERR_SHIPPING_WEIGHT_EXCEEDED;
    case 700:
    case "ERR_FULFILLMENT_VIDEO_NOT_FOUND":
      return ErrorCode.ERR_FULFILLMENT_VIDEO_NOT_FOUND;
    case 701:
    case "ERR_FULFILLMENT_SEAL_CODE_INVALID":
      return ErrorCode.ERR_FULFILLMENT_SEAL_CODE_INVALID;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: ErrorCode): string {
  switch (object) {
    case ErrorCode.ERROR_CODE_UNSPECIFIED:
      return "ERROR_CODE_UNSPECIFIED";
    case ErrorCode.ERR_INTERNAL_SERVER_ERROR:
      return "ERR_INTERNAL_SERVER_ERROR";
    case ErrorCode.ERR_INVALID_ARGUMENT:
      return "ERR_INVALID_ARGUMENT";
    case ErrorCode.ERR_UNAUTHENTICATED:
      return "ERR_UNAUTHENTICATED";
    case ErrorCode.ERR_PERMISSION_DENIED:
      return "ERR_PERMISSION_DENIED";
    case ErrorCode.ERR_RESOURCE_NOT_FOUND:
      return "ERR_RESOURCE_NOT_FOUND";
    case ErrorCode.ERR_IDEMPOTENCY_CONFLICT:
      return "ERR_IDEMPOTENCY_CONFLICT";
    case ErrorCode.ERR_CIRCUIT_BREAKER_OPEN:
      return "ERR_CIRCUIT_BREAKER_OPEN";
    case ErrorCode.ERR_DEADLINE_EXCEEDED:
      return "ERR_DEADLINE_EXCEEDED";
    case ErrorCode.ERR_INVENTORY_INSUFFICIENT_STOCK:
      return "ERR_INVENTORY_INSUFFICIENT_STOCK";
    case ErrorCode.ERR_INVENTORY_SKU_NOT_FOUND:
      return "ERR_INVENTORY_SKU_NOT_FOUND";
    case ErrorCode.ERR_INVENTORY_SKU_INACTIVE:
      return "ERR_INVENTORY_SKU_INACTIVE";
    case ErrorCode.ERR_INVENTORY_RESERVATION_NOT_FOUND:
      return "ERR_INVENTORY_RESERVATION_NOT_FOUND";
    case ErrorCode.ERR_INVENTORY_RESERVATION_EXPIRED:
      return "ERR_INVENTORY_RESERVATION_EXPIRED";
    case ErrorCode.ERR_INVENTORY_BATCH_QUARANTINED:
      return "ERR_INVENTORY_BATCH_QUARANTINED";
    case ErrorCode.ERR_CATALOG_PRICE_TAMPERED:
      return "ERR_CATALOG_PRICE_TAMPERED";
    case ErrorCode.ERR_CATALOG_PRODUCT_OUT_OF_SEASON:
      return "ERR_CATALOG_PRODUCT_OUT_OF_SEASON";
    case ErrorCode.ERR_CATALOG_VARIANT_MISMATCH:
      return "ERR_CATALOG_VARIANT_MISMATCH";
    case ErrorCode.ERR_PROMOTION_VOUCHER_NOT_FOUND:
      return "ERR_PROMOTION_VOUCHER_NOT_FOUND";
    case ErrorCode.ERR_PROMOTION_VOUCHER_EXPIRED:
      return "ERR_PROMOTION_VOUCHER_EXPIRED";
    case ErrorCode.ERR_PROMOTION_USAGE_LIMIT_EXCEEDED:
      return "ERR_PROMOTION_USAGE_LIMIT_EXCEEDED";
    case ErrorCode.ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET:
      return "ERR_PROMOTION_MIN_ORDER_AMOUNT_NOT_MET";
    case ErrorCode.ERR_PROMOTION_VOUCHER_ALREADY_LOCKED:
      return "ERR_PROMOTION_VOUCHER_ALREADY_LOCKED";
    case ErrorCode.ERR_ORDER_NOT_FOUND:
      return "ERR_ORDER_NOT_FOUND";
    case ErrorCode.ERR_ORDER_INVALID_STATE_TRANSITION:
      return "ERR_ORDER_INVALID_STATE_TRANSITION";
    case ErrorCode.ERR_ORDER_ALREADY_PAID:
      return "ERR_ORDER_ALREADY_PAID";
    case ErrorCode.ERR_ORDER_PAYMENT_TIMEOUT:
      return "ERR_ORDER_PAYMENT_TIMEOUT";
    case ErrorCode.ERR_ORDER_CANCELLED_BY_USER:
      return "ERR_ORDER_CANCELLED_BY_USER";
    case ErrorCode.ERR_ORDER_SAGA_COMPENSATION_FAILED:
      return "ERR_ORDER_SAGA_COMPENSATION_FAILED";
    case ErrorCode.ERR_PAYMENT_GATEWAY_UNAVAILABLE:
      return "ERR_PAYMENT_GATEWAY_UNAVAILABLE";
    case ErrorCode.ERR_PAYMENT_HMAC_VERIFICATION_FAILED:
      return "ERR_PAYMENT_HMAC_VERIFICATION_FAILED";
    case ErrorCode.ERR_PAYMENT_AMOUNT_MISMATCH:
      return "ERR_PAYMENT_AMOUNT_MISMATCH";
    case ErrorCode.ERR_PAYMENT_TRANSACTION_EXPIRED:
      return "ERR_PAYMENT_TRANSACTION_EXPIRED";
    case ErrorCode.ERR_SHIPPING_SERVICE_UNAVAILABLE:
      return "ERR_SHIPPING_SERVICE_UNAVAILABLE";
    case ErrorCode.ERR_SHIPPING_ADDRESS_UNSUPPORTED:
      return "ERR_SHIPPING_ADDRESS_UNSUPPORTED";
    case ErrorCode.ERR_SHIPPING_WEIGHT_EXCEEDED:
      return "ERR_SHIPPING_WEIGHT_EXCEEDED";
    case ErrorCode.ERR_FULFILLMENT_VIDEO_NOT_FOUND:
      return "ERR_FULFILLMENT_VIDEO_NOT_FOUND";
    case ErrorCode.ERR_FULFILLMENT_SEAL_CODE_INVALID:
      return "ERR_FULFILLMENT_SEAL_CODE_INVALID";
    case ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Cấu trúc chi tiết mô tả lỗi trả về kèm theo gRPC status */
export interface ErrorDetail {
  /** Mã lỗi nghiệp vụ định danh duy nhất */
  errorCode: ErrorCode;
  /** Thông điệp thân thiện hiển thị cho người dùng (Tiếng Việt) */
  userMessage: string;
  /** Thông điệp kỹ thuật phục vụ lập trình viên debug */
  devMessage: string;
  /** Miền nghiệp vụ phát sinh lỗi (Ví dụ: "inventory", "payment", "order") */
  domain: string;
  /** Metadata bổ sung (Ví dụ: "sku_code": "MX-GION-500G", "available_qty": "1") */
  metadata: { [key: string]: string };
  /** Đường dẫn hướng dẫn xử lý hoặc tài liệu API (Optional) */
  helpLink?: string | undefined;
}

export interface ErrorDetail_MetadataEntry {
  key: string;
  value: string;
}

function createBaseErrorDetail(): ErrorDetail {
  return { errorCode: 0, userMessage: "", devMessage: "", domain: "", metadata: {}, helpLink: undefined };
}

export const ErrorDetail = {
  encode(message: ErrorDetail, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.errorCode !== 0) {
      writer.uint32(8).int32(message.errorCode);
    }
    if (message.userMessage !== "") {
      writer.uint32(18).string(message.userMessage);
    }
    if (message.devMessage !== "") {
      writer.uint32(26).string(message.devMessage);
    }
    if (message.domain !== "") {
      writer.uint32(34).string(message.domain);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      ErrorDetail_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).ldelim();
    });
    if (message.helpLink !== undefined) {
      writer.uint32(50).string(message.helpLink);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ErrorDetail {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.errorCode = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.userMessage = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.devMessage = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.domain = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          const entry5 = ErrorDetail_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.helpLink = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorDetail {
    return {
      errorCode: isSet(object.errorCode) ? errorCodeFromJSON(object.errorCode) : 0,
      userMessage: isSet(object.userMessage) ? globalThis.String(object.userMessage) : "",
      devMessage: isSet(object.devMessage) ? globalThis.String(object.devMessage) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      helpLink: isSet(object.helpLink) ? globalThis.String(object.helpLink) : undefined,
    };
  },

  toJSON(message: ErrorDetail): unknown {
    const obj: any = {};
    if (message.errorCode !== 0) {
      obj.errorCode = errorCodeToJSON(message.errorCode);
    }
    if (message.userMessage !== "") {
      obj.userMessage = message.userMessage;
    }
    if (message.devMessage !== "") {
      obj.devMessage = message.devMessage;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.helpLink !== undefined) {
      obj.helpLink = message.helpLink;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorDetail>, I>>(base?: I): ErrorDetail {
    return ErrorDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorDetail>, I>>(object: I): ErrorDetail {
    const message = createBaseErrorDetail();
    message.errorCode = object.errorCode ?? 0;
    message.userMessage = object.userMessage ?? "";
    message.devMessage = object.devMessage ?? "";
    message.domain = object.domain ?? "";
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.helpLink = object.helpLink ?? undefined;
    return message;
  },
};

function createBaseErrorDetail_MetadataEntry(): ErrorDetail_MetadataEntry {
  return { key: "", value: "" };
}

export const ErrorDetail_MetadataEntry = {
  encode(message: ErrorDetail_MetadataEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ErrorDetail_MetadataEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorDetail_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorDetail_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ErrorDetail_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorDetail_MetadataEntry>, I>>(base?: I): ErrorDetail_MetadataEntry {
    return ErrorDetail_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorDetail_MetadataEntry>, I>>(object: I): ErrorDetail_MetadataEntry {
    const message = createBaseErrorDetail_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
