// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: common/v1/types.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "omamx.common.v1";

/** Đơn vị đo lường trọng lượng kẹo mè xửng và nguyên liệu */
export enum WeightUnit {
  WEIGHT_UNIT_UNSPECIFIED = 0,
  WEIGHT_UNIT_GRAM = 1,
  WEIGHT_UNIT_KILOGRAM = 2,
  UNRECOGNIZED = -1,
}

export function weightUnitFromJSON(object: any): WeightUnit {
  switch (object) {
    case 0:
    case "WEIGHT_UNIT_UNSPECIFIED":
      return WeightUnit.WEIGHT_UNIT_UNSPECIFIED;
    case 1:
    case "WEIGHT_UNIT_GRAM":
      return WeightUnit.WEIGHT_UNIT_GRAM;
    case 2:
    case "WEIGHT_UNIT_KILOGRAM":
      return WeightUnit.WEIGHT_UNIT_KILOGRAM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WeightUnit.UNRECOGNIZED;
  }
}

export function weightUnitToJSON(object: WeightUnit): string {
  switch (object) {
    case WeightUnit.WEIGHT_UNIT_UNSPECIFIED:
      return "WEIGHT_UNIT_UNSPECIFIED";
    case WeightUnit.WEIGHT_UNIT_GRAM:
      return "WEIGHT_UNIT_GRAM";
    case WeightUnit.WEIGHT_UNIT_KILOGRAM:
      return "WEIGHT_UNIT_KILOGRAM";
    case WeightUnit.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Chuẩn tiền tệ quốc tế hóa, chống tràn số Number.MAX_SAFE_INTEGER trên Node.js */
export interface Money {
  /** Mã tiền tệ 3 ký tự theo chuẩn ISO 4217 (Ví dụ: "VND", "USD") */
  currencyCode: string;
  /**
   * Phần nguyên của số tiền (Ví dụ: 110000 trong 110.000 VND).
   * Chú ý: Ở phía Node.js, bắt buộc parse trường này bằng BigInt(units), tuyệt đối không dùng Number().
   */
  units: bigint;
  /** Số đơn vị nano (10^-9) của số tiền. Với đồng Việt Nam (VND) không có hào/xu, trường này luôn = 0. */
  nanos: number;
}

/** Địa chỉ giao nhận hàng hóa 4 cấp chuẩn hóa hành chính Việt Nam */
export interface Address {
  /** Họ và tên người nhận kiện hàng */
  recipientName: string;
  /** Số điện thoại người nhận (Định dạng E.164 hoặc số di động VN 10 chữ số) */
  phoneNumber: string;
  /** Địa chỉ chi tiết (Số nhà, ngõ, tên đường) */
  streetAddress: string;
  /** Phường / Xã / Thị trấn (Ví dụ: "Phường Thuận Hòa") */
  ward: string;
  /** Quận / Huyện / Thị xã / Thành phố trực thuộc tỉnh (Ví dụ: "Thành phố Huế") */
  district: string;
  /** Tỉnh / Thành phố trực thuộc trung ương (Ví dụ: "Tỉnh Thừa Thiên Huế") */
  province: string;
  /** Mã quốc gia theo ISO 3166-1 alpha-2 (Mặc định là "VN") */
  countryCode: string;
  /** Mã bưu chính (Optional) */
  postalCode?: string | undefined;
}

/** Kiểu định lượng trọng lượng với độ chính xác cao (Tránh sai số IEEE-754 giữa Node.js, Python và Go) */
export interface Weight {
  /** Giá trị khối lượng biểu diễn dưới dạng chuỗi số thập phân (Ví dụ: "500.00", "0.250") */
  decimalValue: string;
  /** Đơn vị đo lường */
  unit: WeightUnit;
}

/** Tham số phân trang dùng cho các truy vấn danh sách (Query List) */
export interface PaginationRequest {
  /** Số thứ tự trang cần lấy (Bắt đầu từ 1) */
  page: number;
  /** Số lượng bản ghi tối đa trên một trang (Mặc định: 20, Tối đa: 100) */
  pageSize: number;
}

/** Kết quả phân trang trả về từ các truy vấn danh sách */
export interface PaginationResponse {
  /** Trang hiện tại */
  currentPage: number;
  /** Số lượng phần tử trên trang hiện tại */
  pageSize: number;
  /** Tổng số lượng bản ghi thỏa mãn điều kiện lọc */
  totalItems: bigint;
  /** Tổng số trang */
  totalPages: number;
}

/** Bối cảnh kiểm toán (Audit Context) được truyền qua gRPC Metadata để phục vụ Audit Plane */
export interface AuditContext {
  /** Mã định danh người dùng hoặc hệ thống thực hiện thao tác (Ví dụ: "STAFF-WH-02", "CUST-9876") */
  actorId: string;
  /** Vai trò của người thực hiện (Ví dụ: "CUSTOMER", "WAREHOUSE_STAFF", "SYSTEM_SAGA") */
  actorRole: string;
  /** Địa chỉ IP của client gọi yêu cầu */
  clientIp: string;
  /** Chuỗi vết dấu phân tán W3C Distributed Tracing (traceparent) */
  traceparent: string;
  /** User-Agent của ứng dụng client */
  userAgent?: string | undefined;
}

function createBaseMoney(): Money {
  return { currencyCode: "", units: BigInt("0"), nanos: 0 };
}

export const Money = {
  encode(message: Money, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.currencyCode !== "") {
      writer.uint32(10).string(message.currencyCode);
    }
    if (message.units !== BigInt("0")) {
      if (BigInt.asIntN(64, message.units) !== message.units) {
        throw new globalThis.Error("value provided for field message.units of type int64 too large");
      }
      writer.uint32(16).int64(message.units.toString());
    }
    if (message.nanos !== 0) {
      writer.uint32(24).int32(message.nanos);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Money {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoney();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.currencyCode = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.units = longToBigint(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.nanos = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Money {
    return {
      currencyCode: isSet(object.currencyCode) ? globalThis.String(object.currencyCode) : "",
      units: isSet(object.units) ? BigInt(object.units) : BigInt("0"),
      nanos: isSet(object.nanos) ? globalThis.Number(object.nanos) : 0,
    };
  },

  toJSON(message: Money): unknown {
    const obj: any = {};
    if (message.currencyCode !== "") {
      obj.currencyCode = message.currencyCode;
    }
    if (message.units !== BigInt("0")) {
      obj.units = message.units.toString();
    }
    if (message.nanos !== 0) {
      obj.nanos = Math.round(message.nanos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Money>, I>>(base?: I): Money {
    return Money.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Money>, I>>(object: I): Money {
    const message = createBaseMoney();
    message.currencyCode = object.currencyCode ?? "";
    message.units = object.units ?? BigInt("0");
    message.nanos = object.nanos ?? 0;
    return message;
  },
};

function createBaseAddress(): Address {
  return {
    recipientName: "",
    phoneNumber: "",
    streetAddress: "",
    ward: "",
    district: "",
    province: "",
    countryCode: "",
    postalCode: undefined,
  };
}

export const Address = {
  encode(message: Address, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.recipientName !== "") {
      writer.uint32(10).string(message.recipientName);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(18).string(message.phoneNumber);
    }
    if (message.streetAddress !== "") {
      writer.uint32(26).string(message.streetAddress);
    }
    if (message.ward !== "") {
      writer.uint32(34).string(message.ward);
    }
    if (message.district !== "") {
      writer.uint32(42).string(message.district);
    }
    if (message.province !== "") {
      writer.uint32(50).string(message.province);
    }
    if (message.countryCode !== "") {
      writer.uint32(58).string(message.countryCode);
    }
    if (message.postalCode !== undefined) {
      writer.uint32(66).string(message.postalCode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Address {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.recipientName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.streetAddress = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.ward = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.district = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.province = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.postalCode = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      recipientName: isSet(object.recipientName) ? globalThis.String(object.recipientName) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      streetAddress: isSet(object.streetAddress) ? globalThis.String(object.streetAddress) : "",
      ward: isSet(object.ward) ? globalThis.String(object.ward) : "",
      district: isSet(object.district) ? globalThis.String(object.district) : "",
      province: isSet(object.province) ? globalThis.String(object.province) : "",
      countryCode: isSet(object.countryCode) ? globalThis.String(object.countryCode) : "",
      postalCode: isSet(object.postalCode) ? globalThis.String(object.postalCode) : undefined,
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.recipientName !== "") {
      obj.recipientName = message.recipientName;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.streetAddress !== "") {
      obj.streetAddress = message.streetAddress;
    }
    if (message.ward !== "") {
      obj.ward = message.ward;
    }
    if (message.district !== "") {
      obj.district = message.district;
    }
    if (message.province !== "") {
      obj.province = message.province;
    }
    if (message.countryCode !== "") {
      obj.countryCode = message.countryCode;
    }
    if (message.postalCode !== undefined) {
      obj.postalCode = message.postalCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.recipientName = object.recipientName ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.streetAddress = object.streetAddress ?? "";
    message.ward = object.ward ?? "";
    message.district = object.district ?? "";
    message.province = object.province ?? "";
    message.countryCode = object.countryCode ?? "";
    message.postalCode = object.postalCode ?? undefined;
    return message;
  },
};

function createBaseWeight(): Weight {
  return { decimalValue: "", unit: 0 };
}

export const Weight = {
  encode(message: Weight, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.decimalValue !== "") {
      writer.uint32(10).string(message.decimalValue);
    }
    if (message.unit !== 0) {
      writer.uint32(16).int32(message.unit);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Weight {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWeight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.decimalValue = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.unit = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Weight {
    return {
      decimalValue: isSet(object.decimalValue) ? globalThis.String(object.decimalValue) : "",
      unit: isSet(object.unit) ? weightUnitFromJSON(object.unit) : 0,
    };
  },

  toJSON(message: Weight): unknown {
    const obj: any = {};
    if (message.decimalValue !== "") {
      obj.decimalValue = message.decimalValue;
    }
    if (message.unit !== 0) {
      obj.unit = weightUnitToJSON(message.unit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Weight>, I>>(base?: I): Weight {
    return Weight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Weight>, I>>(object: I): Weight {
    const message = createBaseWeight();
    message.decimalValue = object.decimalValue ?? "";
    message.unit = object.unit ?? 0;
    return message;
  },
};

function createBasePaginationRequest(): PaginationRequest {
  return { page: 0, pageSize: 0 };
}

export const PaginationRequest = {
  encode(message: PaginationRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PaginationRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaginationRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
    };
  },

  toJSON(message: PaginationRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaginationRequest>, I>>(base?: I): PaginationRequest {
    return PaginationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaginationRequest>, I>>(object: I): PaginationRequest {
    const message = createBasePaginationRequest();
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBasePaginationResponse(): PaginationResponse {
  return { currentPage: 0, pageSize: 0, totalItems: BigInt("0"), totalPages: 0 };
}

export const PaginationResponse = {
  encode(message: PaginationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.currentPage !== 0) {
      writer.uint32(8).int32(message.currentPage);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.totalItems !== BigInt("0")) {
      if (BigInt.asIntN(64, message.totalItems) !== message.totalItems) {
        throw new globalThis.Error("value provided for field message.totalItems of type int64 too large");
      }
      writer.uint32(24).int64(message.totalItems.toString());
    }
    if (message.totalPages !== 0) {
      writer.uint32(32).int32(message.totalPages);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PaginationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.currentPage = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.totalItems = longToBigint(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalPages = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaginationResponse {
    return {
      currentPage: isSet(object.currentPage) ? globalThis.Number(object.currentPage) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
      totalItems: isSet(object.totalItems) ? BigInt(object.totalItems) : BigInt("0"),
      totalPages: isSet(object.totalPages) ? globalThis.Number(object.totalPages) : 0,
    };
  },

  toJSON(message: PaginationResponse): unknown {
    const obj: any = {};
    if (message.currentPage !== 0) {
      obj.currentPage = Math.round(message.currentPage);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.totalItems !== BigInt("0")) {
      obj.totalItems = message.totalItems.toString();
    }
    if (message.totalPages !== 0) {
      obj.totalPages = Math.round(message.totalPages);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaginationResponse>, I>>(base?: I): PaginationResponse {
    return PaginationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaginationResponse>, I>>(object: I): PaginationResponse {
    const message = createBasePaginationResponse();
    message.currentPage = object.currentPage ?? 0;
    message.pageSize = object.pageSize ?? 0;
    message.totalItems = object.totalItems ?? BigInt("0");
    message.totalPages = object.totalPages ?? 0;
    return message;
  },
};

function createBaseAuditContext(): AuditContext {
  return { actorId: "", actorRole: "", clientIp: "", traceparent: "", userAgent: undefined };
}

export const AuditContext = {
  encode(message: AuditContext, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.actorId !== "") {
      writer.uint32(10).string(message.actorId);
    }
    if (message.actorRole !== "") {
      writer.uint32(18).string(message.actorRole);
    }
    if (message.clientIp !== "") {
      writer.uint32(26).string(message.clientIp);
    }
    if (message.traceparent !== "") {
      writer.uint32(34).string(message.traceparent);
    }
    if (message.userAgent !== undefined) {
      writer.uint32(42).string(message.userAgent);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AuditContext {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuditContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.actorId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.actorRole = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.clientIp = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.traceparent = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.userAgent = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuditContext {
    return {
      actorId: isSet(object.actorId) ? globalThis.String(object.actorId) : "",
      actorRole: isSet(object.actorRole) ? globalThis.String(object.actorRole) : "",
      clientIp: isSet(object.clientIp) ? globalThis.String(object.clientIp) : "",
      traceparent: isSet(object.traceparent) ? globalThis.String(object.traceparent) : "",
      userAgent: isSet(object.userAgent) ? globalThis.String(object.userAgent) : undefined,
    };
  },

  toJSON(message: AuditContext): unknown {
    const obj: any = {};
    if (message.actorId !== "") {
      obj.actorId = message.actorId;
    }
    if (message.actorRole !== "") {
      obj.actorRole = message.actorRole;
    }
    if (message.clientIp !== "") {
      obj.clientIp = message.clientIp;
    }
    if (message.traceparent !== "") {
      obj.traceparent = message.traceparent;
    }
    if (message.userAgent !== undefined) {
      obj.userAgent = message.userAgent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuditContext>, I>>(base?: I): AuditContext {
    return AuditContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuditContext>, I>>(object: I): AuditContext {
    const message = createBaseAuditContext();
    message.actorId = object.actorId ?? "";
    message.actorRole = object.actorRole ?? "";
    message.clientIp = object.clientIp ?? "";
    message.traceparent = object.traceparent ?? "";
    message.userAgent = object.userAgent ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToBigint(long: Long) {
  return BigInt(long.toString());
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
