// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fulfillment/v1/fulfillment.proto

package fulfillmentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FulfillmentService_GetPackingVideoUrl_FullMethodName    = "/omamx.fulfillment.v1.FulfillmentService/GetPackingVideoUrl"
	FulfillmentService_SubmitPackingEvidence_FullMethodName = "/omamx.fulfillment.v1.FulfillmentService/SubmitPackingEvidence"
)

// FulfillmentServiceClient is the client API for FulfillmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulfillmentServiceClient interface {
	// Lấy Pre-signed S3 URL video niêm phong tem Seal O Mạ phục vụ đối soát khiếu nại (NFR-09)
	GetPackingVideoUrl(ctx context.Context, in *GetPackingVideoUrlRequest, opts ...grpc.CallOption) (*GetPackingVideoUrlResponse, error)
	// Thợ xưởng quét mã vạch lô hàng FEFO và nạp video niêm phong tem Seal hoàn tất đóng gói
	SubmitPackingEvidence(ctx context.Context, in *SubmitPackingEvidenceRequest, opts ...grpc.CallOption) (*SubmitPackingEvidenceResponse, error)
}

type fulfillmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulfillmentServiceClient(cc grpc.ClientConnInterface) FulfillmentServiceClient {
	return &fulfillmentServiceClient{cc}
}

func (c *fulfillmentServiceClient) GetPackingVideoUrl(ctx context.Context, in *GetPackingVideoUrlRequest, opts ...grpc.CallOption) (*GetPackingVideoUrlResponse, error) {
	out := new(GetPackingVideoUrlResponse)
	err := c.cc.Invoke(ctx, FulfillmentService_GetPackingVideoUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulfillmentServiceClient) SubmitPackingEvidence(ctx context.Context, in *SubmitPackingEvidenceRequest, opts ...grpc.CallOption) (*SubmitPackingEvidenceResponse, error) {
	out := new(SubmitPackingEvidenceResponse)
	err := c.cc.Invoke(ctx, FulfillmentService_SubmitPackingEvidence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulfillmentServiceServer is the server API for FulfillmentService service.
// All implementations must embed UnimplementedFulfillmentServiceServer
// for forward compatibility
type FulfillmentServiceServer interface {
	// Lấy Pre-signed S3 URL video niêm phong tem Seal O Mạ phục vụ đối soát khiếu nại (NFR-09)
	GetPackingVideoUrl(context.Context, *GetPackingVideoUrlRequest) (*GetPackingVideoUrlResponse, error)
	// Thợ xưởng quét mã vạch lô hàng FEFO và nạp video niêm phong tem Seal hoàn tất đóng gói
	SubmitPackingEvidence(context.Context, *SubmitPackingEvidenceRequest) (*SubmitPackingEvidenceResponse, error)
	mustEmbedUnimplementedFulfillmentServiceServer()
}

// UnimplementedFulfillmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFulfillmentServiceServer struct {
}

func (UnimplementedFulfillmentServiceServer) GetPackingVideoUrl(context.Context, *GetPackingVideoUrlRequest) (*GetPackingVideoUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackingVideoUrl not implemented")
}
func (UnimplementedFulfillmentServiceServer) SubmitPackingEvidence(context.Context, *SubmitPackingEvidenceRequest) (*SubmitPackingEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPackingEvidence not implemented")
}
func (UnimplementedFulfillmentServiceServer) mustEmbedUnimplementedFulfillmentServiceServer() {}

// UnsafeFulfillmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulfillmentServiceServer will
// result in compilation errors.
type UnsafeFulfillmentServiceServer interface {
	mustEmbedUnimplementedFulfillmentServiceServer()
}

func RegisterFulfillmentServiceServer(s grpc.ServiceRegistrar, srv FulfillmentServiceServer) {
	s.RegisterService(&FulfillmentService_ServiceDesc, srv)
}

func _FulfillmentService_GetPackingVideoUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackingVideoUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServiceServer).GetPackingVideoUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulfillmentService_GetPackingVideoUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServiceServer).GetPackingVideoUrl(ctx, req.(*GetPackingVideoUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulfillmentService_SubmitPackingEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPackingEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulfillmentServiceServer).SubmitPackingEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulfillmentService_SubmitPackingEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulfillmentServiceServer).SubmitPackingEvidence(ctx, req.(*SubmitPackingEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FulfillmentService_ServiceDesc is the grpc.ServiceDesc for FulfillmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulfillmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.fulfillment.v1.FulfillmentService",
	HandlerType: (*FulfillmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPackingVideoUrl",
			Handler:    _FulfillmentService_GetPackingVideoUrl_Handler,
		},
		{
			MethodName: "SubmitPackingEvidence",
			Handler:    _FulfillmentService_SubmitPackingEvidence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fulfillment/v1/fulfillment.proto",
}
