// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: catalog/v1/catalog.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Money, PaginationRequest, PaginationResponse, Weight } from "../../common/v1/types";

export const protobufPackage = "omamx.catalog.v1";

/** Mặt hàng cần kiểm tra giá bán */
export interface PriceCheckItem {
  /** Mã SKU của biến thể kẹo (Ví dụ: "MX-GION-500G") */
  skuCode: string;
  /** Đơn giá mà phía Client (Web/Mobile) gửi lên để kiểm tra */
  clientUnitPrice?:
    | Money
    | undefined;
  /** Số lượng mua */
  quantity: number;
}

/** Yêu cầu thẩm định giá bán */
export interface ValidatePriceAndSKURequest {
  /** Khóa chống lặp (Bắt buộc trên mọi command) */
  idempotencyKey: string;
  /** Kênh bán hàng (D2C_WEB, MOBILE_APP, B2B_WHOLESALE, POS_QUAY) */
  channel: string;
  /** Danh sách các mặt hàng và mức giá cần kiểm định */
  items: PriceCheckItem[];
}

/** Chi tiết sai lệch giá phát hiện được */
export interface PriceDiscrepancy {
  skuCode: string;
  clientUnitPrice?: Money | undefined;
  authoritativeUnitPrice?: Money | undefined;
  discrepancyReason: string;
}

/** Phản hồi kết quả thẩm định giá bán */
export interface ValidatePriceAndSKUResponse {
  /** Kết quả hợp lệ: true nếu toàn bộ mã hàng hợp lệ và đúng giá 100% */
  isValid: boolean;
  /** Tổng số tiền chuẩn xác của giỏ hàng được tính toán lại từ Database gốc của Catalog */
  canonicalSubtotal?:
    | Money
    | undefined;
  /** Danh sách chi tiết các mặt hàng bị sai lệch giá hoặc ngừng bán (nếu có) */
  discrepancies: PriceDiscrepancy[];
  /** Chi tiết lỗi chuẩn hóa nếu phát hiện gian lận giá */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu lấy thông tin biến thể sản phẩm */
export interface GetProductVariantRequest {
  skuCode: string;
}

/** Thông tin chi tiết một biến thể kẹo mè xửng O Mạ */
export interface ProductVariantDetail {
  skuCode: string;
  productId: string;
  /** Ví dụ: "Kẹo Mè Xửng Giòn Huế - Hộp 500g" */
  variantName: string;
  /** Đơn giá bán lẻ niêm yết */
  unitPrice?:
    | Money
    | undefined;
  /** Khối lượng tịnh bảo đảm độ chính xác (Ví dụ: "500.00" gram) */
  netWeight?:
    | Weight
    | undefined;
  /** Xếp hạng sao tiêu chuẩn OCOP (Ví dụ: "OCOP_4_STAR") */
  ocopRating: string;
  /** Loại đóng gói bao bì (Ví dụ: "HOP_GIAY_KRAFT", "GOI_HUT_CHAN_KHONG") */
  packagingType: string;
  /** Thời hạn sử dụng tính bằng số ngày (Shelf Life, ví dụ: 90 ngày) */
  shelfLifeDays: number;
  /** Trạng thái sản phẩm (true: đang bán, false: tạm ngừng sản xuất) */
  isActive: boolean;
}

/** Phản hồi thông tin biến thể */
export interface GetProductVariantResponse {
  variant?: ProductVariantDetail | undefined;
}

/** Yêu cầu danh sách biến thể */
export interface ListProductVariantsRequest {
  /** Bộ lọc phân trang */
  pagination?:
    | PaginationRequest
    | undefined;
  /** Lọc theo danh mục sản phẩm (Optional) */
  categoryId?:
    | string
    | undefined;
  /** Lọc theo xếp hạng OCOP (Optional) */
  ocopRating?:
    | string
    | undefined;
  /** Chỉ lấy các sản phẩm đang kích hoạt bán (Mặc định: true) */
  activeOnly?: boolean | undefined;
}

/** Phản hồi danh sách biến thể */
export interface ListProductVariantsResponse {
  variants: ProductVariantDetail[];
  pagination?: PaginationResponse | undefined;
}

function createBasePriceCheckItem(): PriceCheckItem {
  return { skuCode: "", clientUnitPrice: undefined, quantity: 0 };
}

export const PriceCheckItem = {
  encode(message: PriceCheckItem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.clientUnitPrice !== undefined) {
      Money.encode(message.clientUnitPrice, writer.uint32(18).fork()).ldelim();
    }
    if (message.quantity !== 0) {
      writer.uint32(24).int32(message.quantity);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PriceCheckItem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePriceCheckItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.clientUnitPrice = Money.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PriceCheckItem {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      clientUnitPrice: isSet(object.clientUnitPrice) ? Money.fromJSON(object.clientUnitPrice) : undefined,
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: PriceCheckItem): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.clientUnitPrice !== undefined) {
      obj.clientUnitPrice = Money.toJSON(message.clientUnitPrice);
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PriceCheckItem>, I>>(base?: I): PriceCheckItem {
    return PriceCheckItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PriceCheckItem>, I>>(object: I): PriceCheckItem {
    const message = createBasePriceCheckItem();
    message.skuCode = object.skuCode ?? "";
    message.clientUnitPrice = (object.clientUnitPrice !== undefined && object.clientUnitPrice !== null)
      ? Money.fromPartial(object.clientUnitPrice)
      : undefined;
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

function createBaseValidatePriceAndSKURequest(): ValidatePriceAndSKURequest {
  return { idempotencyKey: "", channel: "", items: [] };
}

export const ValidatePriceAndSKURequest = {
  encode(message: ValidatePriceAndSKURequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    for (const v of message.items) {
      PriceCheckItem.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ValidatePriceAndSKURequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidatePriceAndSKURequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.items.push(PriceCheckItem.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidatePriceAndSKURequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => PriceCheckItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: ValidatePriceAndSKURequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => PriceCheckItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidatePriceAndSKURequest>, I>>(base?: I): ValidatePriceAndSKURequest {
    return ValidatePriceAndSKURequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidatePriceAndSKURequest>, I>>(object: I): ValidatePriceAndSKURequest {
    const message = createBaseValidatePriceAndSKURequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.channel = object.channel ?? "";
    message.items = object.items?.map((e) => PriceCheckItem.fromPartial(e)) || [];
    return message;
  },
};

function createBasePriceDiscrepancy(): PriceDiscrepancy {
  return { skuCode: "", clientUnitPrice: undefined, authoritativeUnitPrice: undefined, discrepancyReason: "" };
}

export const PriceDiscrepancy = {
  encode(message: PriceDiscrepancy, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.clientUnitPrice !== undefined) {
      Money.encode(message.clientUnitPrice, writer.uint32(18).fork()).ldelim();
    }
    if (message.authoritativeUnitPrice !== undefined) {
      Money.encode(message.authoritativeUnitPrice, writer.uint32(26).fork()).ldelim();
    }
    if (message.discrepancyReason !== "") {
      writer.uint32(34).string(message.discrepancyReason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PriceDiscrepancy {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePriceDiscrepancy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.clientUnitPrice = Money.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.authoritativeUnitPrice = Money.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.discrepancyReason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PriceDiscrepancy {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      clientUnitPrice: isSet(object.clientUnitPrice) ? Money.fromJSON(object.clientUnitPrice) : undefined,
      authoritativeUnitPrice: isSet(object.authoritativeUnitPrice)
        ? Money.fromJSON(object.authoritativeUnitPrice)
        : undefined,
      discrepancyReason: isSet(object.discrepancyReason) ? globalThis.String(object.discrepancyReason) : "",
    };
  },

  toJSON(message: PriceDiscrepancy): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.clientUnitPrice !== undefined) {
      obj.clientUnitPrice = Money.toJSON(message.clientUnitPrice);
    }
    if (message.authoritativeUnitPrice !== undefined) {
      obj.authoritativeUnitPrice = Money.toJSON(message.authoritativeUnitPrice);
    }
    if (message.discrepancyReason !== "") {
      obj.discrepancyReason = message.discrepancyReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PriceDiscrepancy>, I>>(base?: I): PriceDiscrepancy {
    return PriceDiscrepancy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PriceDiscrepancy>, I>>(object: I): PriceDiscrepancy {
    const message = createBasePriceDiscrepancy();
    message.skuCode = object.skuCode ?? "";
    message.clientUnitPrice = (object.clientUnitPrice !== undefined && object.clientUnitPrice !== null)
      ? Money.fromPartial(object.clientUnitPrice)
      : undefined;
    message.authoritativeUnitPrice =
      (object.authoritativeUnitPrice !== undefined && object.authoritativeUnitPrice !== null)
        ? Money.fromPartial(object.authoritativeUnitPrice)
        : undefined;
    message.discrepancyReason = object.discrepancyReason ?? "";
    return message;
  },
};

function createBaseValidatePriceAndSKUResponse(): ValidatePriceAndSKUResponse {
  return { isValid: false, canonicalSubtotal: undefined, discrepancies: [], error: undefined };
}

export const ValidatePriceAndSKUResponse = {
  encode(message: ValidatePriceAndSKUResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isValid !== false) {
      writer.uint32(8).bool(message.isValid);
    }
    if (message.canonicalSubtotal !== undefined) {
      Money.encode(message.canonicalSubtotal, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.discrepancies) {
      PriceDiscrepancy.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ValidatePriceAndSKUResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidatePriceAndSKUResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.canonicalSubtotal = Money.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.discrepancies.push(PriceDiscrepancy.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidatePriceAndSKUResponse {
    return {
      isValid: isSet(object.isValid) ? globalThis.Boolean(object.isValid) : false,
      canonicalSubtotal: isSet(object.canonicalSubtotal) ? Money.fromJSON(object.canonicalSubtotal) : undefined,
      discrepancies: globalThis.Array.isArray(object?.discrepancies)
        ? object.discrepancies.map((e: any) => PriceDiscrepancy.fromJSON(e))
        : [],
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ValidatePriceAndSKUResponse): unknown {
    const obj: any = {};
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.canonicalSubtotal !== undefined) {
      obj.canonicalSubtotal = Money.toJSON(message.canonicalSubtotal);
    }
    if (message.discrepancies?.length) {
      obj.discrepancies = message.discrepancies.map((e) => PriceDiscrepancy.toJSON(e));
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidatePriceAndSKUResponse>, I>>(base?: I): ValidatePriceAndSKUResponse {
    return ValidatePriceAndSKUResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidatePriceAndSKUResponse>, I>>(object: I): ValidatePriceAndSKUResponse {
    const message = createBaseValidatePriceAndSKUResponse();
    message.isValid = object.isValid ?? false;
    message.canonicalSubtotal = (object.canonicalSubtotal !== undefined && object.canonicalSubtotal !== null)
      ? Money.fromPartial(object.canonicalSubtotal)
      : undefined;
    message.discrepancies = object.discrepancies?.map((e) => PriceDiscrepancy.fromPartial(e)) || [];
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGetProductVariantRequest(): GetProductVariantRequest {
  return { skuCode: "" };
}

export const GetProductVariantRequest = {
  encode(message: GetProductVariantRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetProductVariantRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductVariantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductVariantRequest {
    return { skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "" };
  },

  toJSON(message: GetProductVariantRequest): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductVariantRequest>, I>>(base?: I): GetProductVariantRequest {
    return GetProductVariantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductVariantRequest>, I>>(object: I): GetProductVariantRequest {
    const message = createBaseGetProductVariantRequest();
    message.skuCode = object.skuCode ?? "";
    return message;
  },
};

function createBaseProductVariantDetail(): ProductVariantDetail {
  return {
    skuCode: "",
    productId: "",
    variantName: "",
    unitPrice: undefined,
    netWeight: undefined,
    ocopRating: "",
    packagingType: "",
    shelfLifeDays: 0,
    isActive: false,
  };
}

export const ProductVariantDetail = {
  encode(message: ProductVariantDetail, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.skuCode !== "") {
      writer.uint32(10).string(message.skuCode);
    }
    if (message.productId !== "") {
      writer.uint32(18).string(message.productId);
    }
    if (message.variantName !== "") {
      writer.uint32(26).string(message.variantName);
    }
    if (message.unitPrice !== undefined) {
      Money.encode(message.unitPrice, writer.uint32(34).fork()).ldelim();
    }
    if (message.netWeight !== undefined) {
      Weight.encode(message.netWeight, writer.uint32(42).fork()).ldelim();
    }
    if (message.ocopRating !== "") {
      writer.uint32(50).string(message.ocopRating);
    }
    if (message.packagingType !== "") {
      writer.uint32(58).string(message.packagingType);
    }
    if (message.shelfLifeDays !== 0) {
      writer.uint32(64).int32(message.shelfLifeDays);
    }
    if (message.isActive !== false) {
      writer.uint32(72).bool(message.isActive);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ProductVariantDetail {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductVariantDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.skuCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.productId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.variantName = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.unitPrice = Money.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.netWeight = Weight.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.ocopRating = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.packagingType = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.shelfLifeDays = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.isActive = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductVariantDetail {
    return {
      skuCode: isSet(object.skuCode) ? globalThis.String(object.skuCode) : "",
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      variantName: isSet(object.variantName) ? globalThis.String(object.variantName) : "",
      unitPrice: isSet(object.unitPrice) ? Money.fromJSON(object.unitPrice) : undefined,
      netWeight: isSet(object.netWeight) ? Weight.fromJSON(object.netWeight) : undefined,
      ocopRating: isSet(object.ocopRating) ? globalThis.String(object.ocopRating) : "",
      packagingType: isSet(object.packagingType) ? globalThis.String(object.packagingType) : "",
      shelfLifeDays: isSet(object.shelfLifeDays) ? globalThis.Number(object.shelfLifeDays) : 0,
      isActive: isSet(object.isActive) ? globalThis.Boolean(object.isActive) : false,
    };
  },

  toJSON(message: ProductVariantDetail): unknown {
    const obj: any = {};
    if (message.skuCode !== "") {
      obj.skuCode = message.skuCode;
    }
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.variantName !== "") {
      obj.variantName = message.variantName;
    }
    if (message.unitPrice !== undefined) {
      obj.unitPrice = Money.toJSON(message.unitPrice);
    }
    if (message.netWeight !== undefined) {
      obj.netWeight = Weight.toJSON(message.netWeight);
    }
    if (message.ocopRating !== "") {
      obj.ocopRating = message.ocopRating;
    }
    if (message.packagingType !== "") {
      obj.packagingType = message.packagingType;
    }
    if (message.shelfLifeDays !== 0) {
      obj.shelfLifeDays = Math.round(message.shelfLifeDays);
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProductVariantDetail>, I>>(base?: I): ProductVariantDetail {
    return ProductVariantDetail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProductVariantDetail>, I>>(object: I): ProductVariantDetail {
    const message = createBaseProductVariantDetail();
    message.skuCode = object.skuCode ?? "";
    message.productId = object.productId ?? "";
    message.variantName = object.variantName ?? "";
    message.unitPrice = (object.unitPrice !== undefined && object.unitPrice !== null)
      ? Money.fromPartial(object.unitPrice)
      : undefined;
    message.netWeight = (object.netWeight !== undefined && object.netWeight !== null)
      ? Weight.fromPartial(object.netWeight)
      : undefined;
    message.ocopRating = object.ocopRating ?? "";
    message.packagingType = object.packagingType ?? "";
    message.shelfLifeDays = object.shelfLifeDays ?? 0;
    message.isActive = object.isActive ?? false;
    return message;
  },
};

function createBaseGetProductVariantResponse(): GetProductVariantResponse {
  return { variant: undefined };
}

export const GetProductVariantResponse = {
  encode(message: GetProductVariantResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.variant !== undefined) {
      ProductVariantDetail.encode(message.variant, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetProductVariantResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductVariantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.variant = ProductVariantDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductVariantResponse {
    return { variant: isSet(object.variant) ? ProductVariantDetail.fromJSON(object.variant) : undefined };
  },

  toJSON(message: GetProductVariantResponse): unknown {
    const obj: any = {};
    if (message.variant !== undefined) {
      obj.variant = ProductVariantDetail.toJSON(message.variant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductVariantResponse>, I>>(base?: I): GetProductVariantResponse {
    return GetProductVariantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductVariantResponse>, I>>(object: I): GetProductVariantResponse {
    const message = createBaseGetProductVariantResponse();
    message.variant = (object.variant !== undefined && object.variant !== null)
      ? ProductVariantDetail.fromPartial(object.variant)
      : undefined;
    return message;
  },
};

function createBaseListProductVariantsRequest(): ListProductVariantsRequest {
  return { pagination: undefined, categoryId: undefined, ocopRating: undefined, activeOnly: undefined };
}

export const ListProductVariantsRequest = {
  encode(message: ListProductVariantsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pagination !== undefined) {
      PaginationRequest.encode(message.pagination, writer.uint32(10).fork()).ldelim();
    }
    if (message.categoryId !== undefined) {
      writer.uint32(18).string(message.categoryId);
    }
    if (message.ocopRating !== undefined) {
      writer.uint32(26).string(message.ocopRating);
    }
    if (message.activeOnly !== undefined) {
      writer.uint32(32).bool(message.activeOnly);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListProductVariantsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProductVariantsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PaginationRequest.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.categoryId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.ocopRating = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.activeOnly = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProductVariantsRequest {
    return {
      pagination: isSet(object.pagination) ? PaginationRequest.fromJSON(object.pagination) : undefined,
      categoryId: isSet(object.categoryId) ? globalThis.String(object.categoryId) : undefined,
      ocopRating: isSet(object.ocopRating) ? globalThis.String(object.ocopRating) : undefined,
      activeOnly: isSet(object.activeOnly) ? globalThis.Boolean(object.activeOnly) : undefined,
    };
  },

  toJSON(message: ListProductVariantsRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PaginationRequest.toJSON(message.pagination);
    }
    if (message.categoryId !== undefined) {
      obj.categoryId = message.categoryId;
    }
    if (message.ocopRating !== undefined) {
      obj.ocopRating = message.ocopRating;
    }
    if (message.activeOnly !== undefined) {
      obj.activeOnly = message.activeOnly;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProductVariantsRequest>, I>>(base?: I): ListProductVariantsRequest {
    return ListProductVariantsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProductVariantsRequest>, I>>(object: I): ListProductVariantsRequest {
    const message = createBaseListProductVariantsRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationRequest.fromPartial(object.pagination)
      : undefined;
    message.categoryId = object.categoryId ?? undefined;
    message.ocopRating = object.ocopRating ?? undefined;
    message.activeOnly = object.activeOnly ?? undefined;
    return message;
  },
};

function createBaseListProductVariantsResponse(): ListProductVariantsResponse {
  return { variants: [], pagination: undefined };
}

export const ListProductVariantsResponse = {
  encode(message: ListProductVariantsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.variants) {
      ProductVariantDetail.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.pagination !== undefined) {
      PaginationResponse.encode(message.pagination, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListProductVariantsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProductVariantsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.variants.push(ProductVariantDetail.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginationResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListProductVariantsResponse {
    return {
      variants: globalThis.Array.isArray(object?.variants)
        ? object.variants.map((e: any) => ProductVariantDetail.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PaginationResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: ListProductVariantsResponse): unknown {
    const obj: any = {};
    if (message.variants?.length) {
      obj.variants = message.variants.map((e) => ProductVariantDetail.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginationResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListProductVariantsResponse>, I>>(base?: I): ListProductVariantsResponse {
    return ListProductVariantsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListProductVariantsResponse>, I>>(object: I): ListProductVariantsResponse {
    const message = createBaseListProductVariantsResponse();
    message.variants = object.variants?.map((e) => ProductVariantDetail.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

export type CatalogServiceService = typeof CatalogServiceService;
export const CatalogServiceService = {
  /** Thẩm định tính hợp lệ của mã SKU và đối chiếu giá bán client gửi lên (Critical Path < 15ms) */
  validatePriceAndSku: {
    path: "/omamx.catalog.v1.CatalogService/ValidatePriceAndSKU",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidatePriceAndSKURequest) =>
      Buffer.from(ValidatePriceAndSKURequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ValidatePriceAndSKURequest.decode(value),
    responseSerialize: (value: ValidatePriceAndSKUResponse) =>
      Buffer.from(ValidatePriceAndSKUResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ValidatePriceAndSKUResponse.decode(value),
  },
  /** Truy vấn thông tin chi tiết của một biến thể kẹo mè xửng theo mã SKU */
  getProductVariant: {
    path: "/omamx.catalog.v1.CatalogService/GetProductVariant",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetProductVariantRequest) => Buffer.from(GetProductVariantRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetProductVariantRequest.decode(value),
    responseSerialize: (value: GetProductVariantResponse) =>
      Buffer.from(GetProductVariantResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetProductVariantResponse.decode(value),
  },
  /** Truy vấn danh sách biến thể sản phẩm theo bộ lọc (Có phân trang) */
  listProductVariants: {
    path: "/omamx.catalog.v1.CatalogService/ListProductVariants",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListProductVariantsRequest) =>
      Buffer.from(ListProductVariantsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListProductVariantsRequest.decode(value),
    responseSerialize: (value: ListProductVariantsResponse) =>
      Buffer.from(ListProductVariantsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ListProductVariantsResponse.decode(value),
  },
} as const;

export interface CatalogServiceServer extends UntypedServiceImplementation {
  /** Thẩm định tính hợp lệ của mã SKU và đối chiếu giá bán client gửi lên (Critical Path < 15ms) */
  validatePriceAndSku: handleUnaryCall<ValidatePriceAndSKURequest, ValidatePriceAndSKUResponse>;
  /** Truy vấn thông tin chi tiết của một biến thể kẹo mè xửng theo mã SKU */
  getProductVariant: handleUnaryCall<GetProductVariantRequest, GetProductVariantResponse>;
  /** Truy vấn danh sách biến thể sản phẩm theo bộ lọc (Có phân trang) */
  listProductVariants: handleUnaryCall<ListProductVariantsRequest, ListProductVariantsResponse>;
}

export interface CatalogServiceClient extends Client {
  /** Thẩm định tính hợp lệ của mã SKU và đối chiếu giá bán client gửi lên (Critical Path < 15ms) */
  validatePriceAndSku(
    request: ValidatePriceAndSKURequest,
    callback: (error: ServiceError | null, response: ValidatePriceAndSKUResponse) => void,
  ): ClientUnaryCall;
  validatePriceAndSku(
    request: ValidatePriceAndSKURequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ValidatePriceAndSKUResponse) => void,
  ): ClientUnaryCall;
  validatePriceAndSku(
    request: ValidatePriceAndSKURequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ValidatePriceAndSKUResponse) => void,
  ): ClientUnaryCall;
  /** Truy vấn thông tin chi tiết của một biến thể kẹo mè xửng theo mã SKU */
  getProductVariant(
    request: GetProductVariantRequest,
    callback: (error: ServiceError | null, response: GetProductVariantResponse) => void,
  ): ClientUnaryCall;
  getProductVariant(
    request: GetProductVariantRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetProductVariantResponse) => void,
  ): ClientUnaryCall;
  getProductVariant(
    request: GetProductVariantRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetProductVariantResponse) => void,
  ): ClientUnaryCall;
  /** Truy vấn danh sách biến thể sản phẩm theo bộ lọc (Có phân trang) */
  listProductVariants(
    request: ListProductVariantsRequest,
    callback: (error: ServiceError | null, response: ListProductVariantsResponse) => void,
  ): ClientUnaryCall;
  listProductVariants(
    request: ListProductVariantsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListProductVariantsResponse) => void,
  ): ClientUnaryCall;
  listProductVariants(
    request: ListProductVariantsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListProductVariantsResponse) => void,
  ): ClientUnaryCall;
}

export const CatalogServiceClient = makeGenericClientConstructor(
  CatalogServiceService,
  "omamx.catalog.v1.CatalogService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CatalogServiceClient;
  service: typeof CatalogServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
