// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: catalog/v1/catalog.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CatalogService_ValidatePriceAndSKU_FullMethodName = "/omamx.catalog.v1.CatalogService/ValidatePriceAndSKU"
	CatalogService_GetProductVariant_FullMethodName   = "/omamx.catalog.v1.CatalogService/GetProductVariant"
	CatalogService_ListProductVariants_FullMethodName = "/omamx.catalog.v1.CatalogService/ListProductVariants"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// Thẩm định tính hợp lệ của mã SKU và đối chiếu giá bán client gửi lên (Critical Path < 15ms)
	ValidatePriceAndSKU(ctx context.Context, in *ValidatePriceAndSKURequest, opts ...grpc.CallOption) (*ValidatePriceAndSKUResponse, error)
	// Truy vấn thông tin chi tiết của một biến thể kẹo mè xửng theo mã SKU
	GetProductVariant(ctx context.Context, in *GetProductVariantRequest, opts ...grpc.CallOption) (*GetProductVariantResponse, error)
	// Truy vấn danh sách biến thể sản phẩm theo bộ lọc (Có phân trang)
	ListProductVariants(ctx context.Context, in *ListProductVariantsRequest, opts ...grpc.CallOption) (*ListProductVariantsResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ValidatePriceAndSKU(ctx context.Context, in *ValidatePriceAndSKURequest, opts ...grpc.CallOption) (*ValidatePriceAndSKUResponse, error) {
	out := new(ValidatePriceAndSKUResponse)
	err := c.cc.Invoke(ctx, CatalogService_ValidatePriceAndSKU_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProductVariant(ctx context.Context, in *GetProductVariantRequest, opts ...grpc.CallOption) (*GetProductVariantResponse, error) {
	out := new(GetProductVariantResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetProductVariant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListProductVariants(ctx context.Context, in *ListProductVariantsRequest, opts ...grpc.CallOption) (*ListProductVariantsResponse, error) {
	out := new(ListProductVariantsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListProductVariants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility
type CatalogServiceServer interface {
	// Thẩm định tính hợp lệ của mã SKU và đối chiếu giá bán client gửi lên (Critical Path < 15ms)
	ValidatePriceAndSKU(context.Context, *ValidatePriceAndSKURequest) (*ValidatePriceAndSKUResponse, error)
	// Truy vấn thông tin chi tiết của một biến thể kẹo mè xửng theo mã SKU
	GetProductVariant(context.Context, *GetProductVariantRequest) (*GetProductVariantResponse, error)
	// Truy vấn danh sách biến thể sản phẩm theo bộ lọc (Có phân trang)
	ListProductVariants(context.Context, *ListProductVariantsRequest) (*ListProductVariantsResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (UnimplementedCatalogServiceServer) ValidatePriceAndSKU(context.Context, *ValidatePriceAndSKURequest) (*ValidatePriceAndSKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatePriceAndSKU not implemented")
}
func (UnimplementedCatalogServiceServer) GetProductVariant(context.Context, *GetProductVariantRequest) (*GetProductVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductVariant not implemented")
}
func (UnimplementedCatalogServiceServer) ListProductVariants(context.Context, *ListProductVariantsRequest) (*ListProductVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductVariants not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ValidatePriceAndSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePriceAndSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ValidatePriceAndSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ValidatePriceAndSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ValidatePriceAndSKU(ctx, req.(*ValidatePriceAndSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProductVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProductVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProductVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProductVariant(ctx, req.(*GetProductVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListProductVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListProductVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListProductVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListProductVariants(ctx, req.(*ListProductVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omamx.catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatePriceAndSKU",
			Handler:    _CatalogService_ValidatePriceAndSKU_Handler,
		},
		{
			MethodName: "GetProductVariant",
			Handler:    _CatalogService_GetProductVariant_Handler,
		},
		{
			MethodName: "ListProductVariants",
			Handler:    _CatalogService_ListProductVariants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/catalog.proto",
}
