"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useAdminSession } from "@/components/auth/admin-session-provider";
import type { BatchExpiryState, InventoryRiskState, InventorySkuDetail, InventorySkuList, InventorySkuSummary } from "@/lib/inventory/types";
import { AdminInventoryApiError } from "@/lib/inventory/types";
import { adminInventoryService } from "@/services/admin-inventory-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
const DATE = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" });
const QUANTITY = new Intl.NumberFormat("vi-VN");

function RiskStatus({ item }: { item: Pick<InventorySkuSummary, "riskState" | "riskLabel"> }) { return <span className={`admin-status inventory-risk-${item.riskState.toLowerCase()}`}>{item.riskLabel}</span>; }
function BatchStatus({ state, label }: { state: BatchExpiryState; label: string }) { return <span className={`admin-status batch-expiry-${state.toLowerCase()}`}>{label}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function InventoryWorkspace() {
  const { hasPermission } = useAdminSession();
  const canViewBatch = hasPermission("BATCH_VIEW");
  const [data, setData] = useState<InventorySkuList | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [risk, setRisk] = useState<"ALL" | InventoryRiskState>("ALL");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("ALL");
  const [availability, setAvailability] = useState("ALL");
  const [menuId, setMenuId] = useState("");
  const [selected, setSelected] = useState<InventorySkuSummary | null>(null);
  const [detail, setDetail] = useState<InventorySkuDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminInventoryService.skus()); } catch (cause) { setLoadError(cause instanceof AdminInventoryApiError ? cause.message : "Không thể tải số dư tồn kho."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase("vi");
    return data?.items.filter((item) => (risk === "ALL" || item.riskState === risk) && (category === "ALL" || item.categoryId === category) && (availability === "ALL" || (availability === "AVAILABLE" ? item.available > 0 : item.available === 0)) && (!needle || [item.skuCode, item.skuLabel, item.productName, item.categoryName].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? [];
  }, [availability, category, data, query, risk]);
  async function openDetail(item: InventorySkuSummary) { setMenuId(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const result = await adminInventoryService.sku(item.skuId); setDetail({ ...result, skuId: item.skuId, skuCode: item.skuCode, skuLabel: item.skuLabel, productId: item.productId, productName: item.productName, scopeLabel: item.scopeLabel }); } catch (cause) { setDetailError(cause instanceof AdminInventoryApiError ? cause.message : "Không thể tải chi tiết Batch/Lot."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải tồn kho</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Vận hành <span>›</span> Inventory</nav><h1>Quản lý Tồn kho &amp; Batch</h1><p>Tra cứu số dư theo SKU, phân rã Batch/Lot, tình trạng HSD và lịch sử biến động theo Epic 09.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Tồn vật lý</span><strong>{QUANTITY.format(data.items.reduce((sum, item) => sum + item.onHand, 0))}</strong><small>Tổng on hand trong scope hiện tại</small></article><article><span>Đang giữ</span><strong>{QUANTITY.format(data.items.reduce((sum, item) => sum + item.reserved, 0))}</strong><small>Không còn khả dụng cho reservation mới</small></article><article><span>Khả dụng</span><strong>{QUANTITY.format(data.items.reduce((sum, item) => sum + item.available, 0))}</strong><small>Giá trị do Inventory API cung cấp</small></article><article><span>Batch cận HSD</span><strong>{QUANTITY.format(data.items.reduce((sum, item) => sum + item.expiringBatchCount, 0))}</strong><small>Không bao gồm Batch đã hết hạn</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc rủi ro HSD">{data.riskCounts.map((item) => <button className={risk === item.riskState ? "active" : ""} type="button" role="tab" aria-selected={risk === item.riskState} onClick={() => setRisk(item.riskState)} key={item.riskState}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã SKU, Product hoặc quy cách…" /></label><label><span className="sr-only">Danh mục</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="ALL">Tất cả danh mục</option>{data.categories.map((item) => <option value={item.categoryId} key={item.categoryId}>{item.categoryName}</option>)}</select></label><label><span className="sr-only">Khả dụng</span><select value={availability} onChange={(event) => setAvailability(event.target.value)}><option value="ALL">Mọi mức khả dụng</option><option value="AVAILABLE">Còn khả dụng</option><option value="UNAVAILABLE">Không có khả dụng</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setQuery(""); setCategory("ALL"); setAvailability("ALL"); setRisk("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> SKU</span><span>Tính lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-inventory-table"><thead><tr><th>SKU / Product</th><th>Vật lý</th><th>Đang giữ</th><th>Không đủ điều kiện</th><th>Khả dụng</th><th>Batch</th><th>Rủi ro HSD</th><th>Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.skuId}><td><strong>{item.skuLabel}</strong><small>{item.skuCode} · {item.productName}</small></td><td><strong>{QUANTITY.format(item.onHand)}</strong></td><td>{QUANTITY.format(item.reserved)}</td><td>{QUANTITY.format(item.nonSellable)}</td><td><strong className={item.available > 0 ? "inventory-positive" : "inventory-zero"}>{QUANTITY.format(item.available)}</strong></td><td><strong>{item.batchCount}</strong><small>{item.expiringBatchCount} cận HSD · {item.expiredBatchCount} hết hạn</small></td><td><RiskStatus item={item} /></td><td>{DATE_TIME.format(new Date(item.updatedAt))}</td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.skuCode}`} onClick={() => setMenuId((current) => current === item.skuId ? "" : item.skuId)}>•••</button>{menuId === item.skuId ? <div className="admin-row-menu">{canViewBatch ? <button type="button" onClick={() => void openDetail(item)}>Xem Batch/Lot và biến động</button> : <span>Không có quyền xem Batch/Lot</span>}</div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có SKU phù hợp</h3><p>Hãy thay đổi rủi ro HSD, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Inventory · ${selected.skuCode}`} subtitle={`${selected.productName} · ${selected.skuLabel}`} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải Batch/Lot và biến động…</div> : detail ? <InventoryDetailContent detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function InventoryDetailContent({ detail }: { detail: InventorySkuDetail }) {
  return <div className="admin-inventory-detail"><div className="admin-balance-grid"><article><span>Vật lý</span><strong>{QUANTITY.format(detail.balance.onHand)}</strong></article><article><span>Đang giữ</span><strong>{QUANTITY.format(detail.balance.reserved)}</strong></article><article><span>Không đủ điều kiện</span><strong>{QUANTITY.format(detail.balance.nonSellable)}</strong></article><article><span>Khả dụng</span><strong>{QUANTITY.format(detail.balance.available)}</strong></article></div><div className="admin-detail-summary"><span>{detail.scopeLabel}</span><span>{detail.batches.length} Batch/Lot</span><span>Revision {detail.revision}</span></div><section><header className="admin-section-heading"><div><h3>Batch/Lot của SKU</h3><p>Ngày bên dưới là dữ liệu Batch thực tế, không phải chính sách shelf-life của catalog.</p></div><strong>{detail.skuCode}</strong></header><div className="admin-batch-list">{detail.batches.map((batch) => <article key={batch.batchId}><header><div><strong>{batch.batchCode}</strong><small>{batch.sourceReference}</small></div><BatchStatus state={batch.expiryState} label={batch.expiryLabel} /></header><dl><div><dt>Ngày sản xuất</dt><dd>{DATE.format(new Date(batch.manufacturingDate))}</dd></div><div><dt>Hạn sử dụng</dt><dd>{DATE.format(new Date(batch.expiresAt))}</dd></div><div><dt>Vật lý</dt><dd>{QUANTITY.format(batch.balance.onHand)}</dd></div><div><dt>Đang giữ</dt><dd>{QUANTITY.format(batch.balance.reserved)}</dd></div><div><dt>Không đủ điều kiện</dt><dd>{QUANTITY.format(batch.balance.nonSellable)}</dd></div><div><dt>Khả dụng</dt><dd>{QUANTITY.format(batch.balance.available)}</dd></div></dl></article>)}</div></section><section><header className="admin-section-heading"><div><h3>Lịch sử biến động được phép xem</h3><p>Số dư là kết quả của biến động; màn hình không cho sửa trực tiếp.</p></div></header><div className="admin-table-wrap"><table className="admin-permission-table admin-movement-table"><thead><tr><th>Thời điểm</th><th>Batch</th><th>Loại</th><th>Số lượng</th><th>Actor/Nguồn</th><th>Tham chiếu</th></tr></thead><tbody>{detail.batches.flatMap((batch) => batch.movements.map((movement) => <tr key={movement.movementId}><td>{DATE_TIME.format(new Date(movement.occurredAt))}</td><td>{batch.batchCode}</td><td>{movement.typeLabel}</td><td><strong className={movement.quantity >= 0 ? "movement-positive" : "movement-negative"}>{movement.quantity > 0 ? "+" : ""}{QUANTITY.format(movement.quantity)}</strong></td><td>{movement.actorLabel}</td><td>{movement.reference}</td></tr>))}</tbody></table></div></section><footer>Không có thao tác nhập, xuất, điều chỉnh hoặc hiệu chỉnh Batch trong popup này. Các mutation chờ chính sách đa kho, công thức số dư, HSD và ngưỡng phê duyệt được chốt.</footer></div>;
}
