"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { AdminProductDetail, AdminProductList, AdminProductSummary, ProductSaleStatus } from "@/lib/catalog/types";
import { AdminCatalogApiError } from "@/lib/catalog/types";
import { adminCatalogService } from "@/services/admin-catalog-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
const MONEY = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });

function ProductStatus({ product }: { product: Pick<AdminProductSummary, "saleStatus" | "saleStatusLabel"> }) { return <span className={`admin-status product-${product.saleStatus.toLowerCase()}`}>{product.saleStatusLabel}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function ProductCatalogWorkspace() {
  const [data, setData] = useState<AdminProductList | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [status, setStatus] = useState<"ALL" | ProductSaleStatus>("ALL");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("ALL");
  const [foodState, setFoodState] = useState("ALL");
  const [menuId, setMenuId] = useState("");
  const [selected, setSelected] = useState<AdminProductSummary | null>(null);
  const [detail, setDetail] = useState<AdminProductDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminCatalogService.products()); } catch (cause) { setLoadError(cause instanceof AdminCatalogApiError ? cause.message : "Không thể tải danh mục sản phẩm."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase("vi");
    return data?.items.filter((item) => (status === "ALL" || item.saleStatus === status) && (category === "ALL" || item.categoryId === category) && (foodState === "ALL" || item.foodInformationComplete === (foodState === "COMPLETE")) && (!needle || [item.productId, item.name, item.categoryName].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? [];
  }, [category, data, foodState, query, status]);
  async function openDetail(item: AdminProductSummary) { setMenuId(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const result = await adminCatalogService.product(item.productId); setDetail({ ...result, ...item, foodInformation: item.foodInformationComplete ? result.foodInformation : null }); } catch (cause) { setDetailError(cause instanceof AdminCatalogApiError ? cause.message : "Không thể tải chi tiết sản phẩm."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải danh mục sản phẩm</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Danh mục <span>›</span> Sản phẩm &amp; SKU</nav><h1>Quản lý Sản phẩm &amp; SKU</h1><p>Tra cứu dữ liệu catalog, SKU, giá cơ bản, thông tin thực phẩm và trạng thái bán theo Epic 04.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Tổng Product</span><strong>{data.items.length}</strong><small>Trong catalog nội bộ hiện tại</small></article><article><span>Đang bán</span><strong>{data.items.filter((item) => item.saleStatus === "ON_SALE").length}</strong><small>Vẫn phụ thuộc tồn kho và Batch hợp lệ</small></article><article><span>Tổng SKU</span><strong>{data.items.reduce((sum, item) => sum + item.skuCount, 0)}</strong><small>Giá và quy cách quản lý theo SKU</small></article><article><span>Thiếu thông tin thực phẩm</span><strong>{data.items.filter((item) => !item.foodInformationComplete).length}</strong><small>Chưa đủ dữ liệu catalog để công khai</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc trạng thái bán Product">{data.statusCounts.map((item) => <button className={status === item.status ? "active" : ""} type="button" role="tab" aria-selected={status === item.status} onClick={() => setStatus(item.status)} key={item.status}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tên, mã Product hoặc danh mục…" /></label><label><span className="sr-only">Danh mục</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="ALL">Tất cả danh mục</option>{data.categories.map((item) => <option value={item.categoryId} key={item.categoryId}>{item.categoryName}</option>)}</select></label><label><span className="sr-only">Thông tin thực phẩm</span><select value={foodState} onChange={(event) => setFoodState(event.target.value)}><option value="ALL">Mọi trạng thái dữ liệu</option><option value="COMPLETE">Đủ thông tin thực phẩm</option><option value="INCOMPLETE">Thiếu thông tin thực phẩm</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setQuery(""); setCategory("ALL"); setFoodState("ALL"); setStatus("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> Product</span><span>Tính lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-product-table"><thead><tr><th>Product</th><th>Danh mục</th><th>Trạng thái bán</th><th>SKU</th><th>Giá cơ bản từ</th><th>Thông tin thực phẩm</th><th>Cập nhật</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.productId}><td><strong>{item.name}</strong><small>{item.productId}</small></td><td>{item.categoryName}</td><td><ProductStatus product={item} /></td><td><strong>{item.onSaleSkuCount}/{item.skuCount}</strong><small>SKU đang bán</small></td><td>{item.basePriceFromVnd === null ? "—" : MONEY.format(item.basePriceFromVnd)}</td><td><span className={`admin-data-state ${item.foodInformationComplete ? "complete" : "incomplete"}`}>{item.foodInformationComplete ? "Đầy đủ" : "Cần bổ sung"}</span></td><td>{DATE_TIME.format(new Date(item.updatedAt))}</td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.name}`} onClick={() => setMenuId((current) => current === item.productId ? "" : item.productId)}>•••</button>{menuId === item.productId ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết Product &amp; SKU</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có Product phù hợp</h3><p>Hãy thay đổi trạng thái, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Product · ${selected.productId}`} subtitle={selected.name} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải Product và SKU…</div> : detail ? <ProductDetailContent detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function ProductDetailContent({ detail }: { detail: AdminProductDetail }) {
  return <div className="admin-product-detail"><div className="admin-detail-summary"><ProductStatus product={detail} /><span>{detail.categoryName}</span><span>Revision {detail.revision}</span></div><div className="admin-detail-grid"><section><h3>Thông tin Product</h3><dl><div><dt>Tên sản phẩm</dt><dd>{detail.name}</dd></div><div><dt>Mô tả ngắn</dt><dd>{detail.shortDescription}</dd></div><div><dt>Mô tả catalog</dt><dd>{detail.longDescription}</dd></div><div><dt>Ảnh đại diện</dt><dd>{detail.coverImageUrl ? "Đã có URL ảnh" : "Chưa có"}</dd></div></dl></section><section><h3>Thông tin thực phẩm</h3>{detail.foodInformation ? <dl><div><dt>Thành phần</dt><dd>{detail.foodInformation.ingredients}</dd></div><div><dt>Dị ứng</dt><dd>{detail.foodInformation.allergenStatement || "Không khai báo"}</dd></div><div><dt>Bảo quản</dt><dd>{detail.foodInformation.storageInstructions}</dd></div><div><dt>Ngày sản xuất</dt><dd>{detail.foodInformation.manufacturingDatePolicy}</dd></div><div><dt>Hạn sử dụng</dt><dd>{detail.foodInformation.shelfLifeDescription}</dd></div></dl> : <div className="admin-inline-error">Thông tin thực phẩm catalog chưa đầy đủ.</div>}</section></div><section><header className="admin-section-heading"><div><h3>Variant / SKU</h3><p>Giá, khối lượng và quy cách được quản lý độc lập theo SKU.</p></div><strong>{detail.skus.length} SKU</strong></header><div className="admin-table-wrap"><table className="admin-permission-table admin-sku-table"><thead><tr><th>SKU</th><th>Thuộc tính</th><th>Quy cách</th><th>Giá cơ bản</th><th>Trạng thái bán</th><th>Cập nhật</th></tr></thead><tbody>{detail.skus.map((sku) => <tr key={sku.skuId}><td><strong>{sku.label}</strong><small>{sku.skuCode}</small></td><td>{sku.weightGrams ? `${sku.weightGrams} g` : "—"}{sku.flavor ? ` · ${sku.flavor}` : ""}</td><td>{sku.packageType}</td><td>{MONEY.format(sku.basePriceVnd)}</td><td><span className={`admin-status product-${sku.saleStatus.toLowerCase()}`}>{sku.saleStatusLabel}</span></td><td>{DATE_TIME.format(new Date(sku.updatedAt))}</td></tr>)}</tbody></table></div></section><footer>Giá trên đây là giá cơ bản của SKU. Giá đa kênh thuộc giai đoạn 2; tồn kho, Batch/Lot và ngày sản xuất/hạn dùng thực tế thuộc Epic 09.</footer></div>;
}
