// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               unknown
// source: shipping/v1/shipping.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ErrorDetail } from "../../common/v1/errors";
import { Address, Money, Weight } from "../../common/v1/types";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "omamx.shipping.v1";

/** Trạng thái vận chuyển */
export enum ShipmentStatus {
  SHIPMENT_STATUS_UNSPECIFIED = 0,
  /** SHIPMENT_STATUS_READY_FOR_PICKUP - Đang chờ bưu tá đến lấy tại kho Hương Thủy */
  SHIPMENT_STATUS_READY_FOR_PICKUP = 1,
  /** SHIPMENT_STATUS_PICKED_UP - Bưu tá đã lấy kiện hàng rời kho */
  SHIPMENT_STATUS_PICKED_UP = 2,
  /** SHIPMENT_STATUS_IN_TRANSIT - Đang trung chuyển liên tỉnh */
  SHIPMENT_STATUS_IN_TRANSIT = 3,
  /** SHIPMENT_STATUS_OUT_FOR_DELIVERY - Shipper đang đi phát hàng */
  SHIPMENT_STATUS_OUT_FOR_DELIVERY = 4,
  /** SHIPMENT_STATUS_DELIVERED - Giao hàng thành công */
  SHIPMENT_STATUS_DELIVERED = 5,
  /** SHIPMENT_STATUS_DELIVERY_FAILED - Giao không thành công (Khách bận/Sai địa chỉ) */
  SHIPMENT_STATUS_DELIVERY_FAILED = 6,
  /** SHIPMENT_STATUS_RETURNING - Đang chuyển hoàn về Huế */
  SHIPMENT_STATUS_RETURNING = 7,
  /** SHIPMENT_STATUS_RETURNED - Đã hoàn nhập kho */
  SHIPMENT_STATUS_RETURNED = 8,
  UNRECOGNIZED = -1,
}

export function shipmentStatusFromJSON(object: any): ShipmentStatus {
  switch (object) {
    case 0:
    case "SHIPMENT_STATUS_UNSPECIFIED":
      return ShipmentStatus.SHIPMENT_STATUS_UNSPECIFIED;
    case 1:
    case "SHIPMENT_STATUS_READY_FOR_PICKUP":
      return ShipmentStatus.SHIPMENT_STATUS_READY_FOR_PICKUP;
    case 2:
    case "SHIPMENT_STATUS_PICKED_UP":
      return ShipmentStatus.SHIPMENT_STATUS_PICKED_UP;
    case 3:
    case "SHIPMENT_STATUS_IN_TRANSIT":
      return ShipmentStatus.SHIPMENT_STATUS_IN_TRANSIT;
    case 4:
    case "SHIPMENT_STATUS_OUT_FOR_DELIVERY":
      return ShipmentStatus.SHIPMENT_STATUS_OUT_FOR_DELIVERY;
    case 5:
    case "SHIPMENT_STATUS_DELIVERED":
      return ShipmentStatus.SHIPMENT_STATUS_DELIVERED;
    case 6:
    case "SHIPMENT_STATUS_DELIVERY_FAILED":
      return ShipmentStatus.SHIPMENT_STATUS_DELIVERY_FAILED;
    case 7:
    case "SHIPMENT_STATUS_RETURNING":
      return ShipmentStatus.SHIPMENT_STATUS_RETURNING;
    case 8:
    case "SHIPMENT_STATUS_RETURNED":
      return ShipmentStatus.SHIPMENT_STATUS_RETURNED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ShipmentStatus.UNRECOGNIZED;
  }
}

export function shipmentStatusToJSON(object: ShipmentStatus): string {
  switch (object) {
    case ShipmentStatus.SHIPMENT_STATUS_UNSPECIFIED:
      return "SHIPMENT_STATUS_UNSPECIFIED";
    case ShipmentStatus.SHIPMENT_STATUS_READY_FOR_PICKUP:
      return "SHIPMENT_STATUS_READY_FOR_PICKUP";
    case ShipmentStatus.SHIPMENT_STATUS_PICKED_UP:
      return "SHIPMENT_STATUS_PICKED_UP";
    case ShipmentStatus.SHIPMENT_STATUS_IN_TRANSIT:
      return "SHIPMENT_STATUS_IN_TRANSIT";
    case ShipmentStatus.SHIPMENT_STATUS_OUT_FOR_DELIVERY:
      return "SHIPMENT_STATUS_OUT_FOR_DELIVERY";
    case ShipmentStatus.SHIPMENT_STATUS_DELIVERED:
      return "SHIPMENT_STATUS_DELIVERED";
    case ShipmentStatus.SHIPMENT_STATUS_DELIVERY_FAILED:
      return "SHIPMENT_STATUS_DELIVERY_FAILED";
    case ShipmentStatus.SHIPMENT_STATUS_RETURNING:
      return "SHIPMENT_STATUS_RETURNING";
    case ShipmentStatus.SHIPMENT_STATUS_RETURNED:
      return "SHIPMENT_STATUS_RETURNED";
    case ShipmentStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Yêu cầu tính phí vận chuyển */
export interface CalculateShippingFeeRequest {
  /** Khóa chống lặp */
  idempotencyKey: string;
  /** Địa chỉ nơi giao hàng của khách */
  destinationAddress?:
    | Address
    | undefined;
  /** Tổng khối lượng ước tính của các hộp kẹo trong đơn */
  totalWeight?:
    | Weight
    | undefined;
  /** Đối tác vận chuyển ưu tiên (Optional: "GHN", "VIETTEL_POST", để trống hệ thống tự chọn tối ưu) */
  preferredCarrier?:
    | string
    | undefined;
  /** Đơn hàng có quà tặng dễ vỡ cần đóng bọc xốp bóng khí cao cấp (Mè xửng giòn O Mạ) */
  isFragile: boolean;
}

/** Phản hồi tính phí vận chuyển */
export interface CalculateShippingFeeResponse {
  /** Cước phí vận chuyển chính xác (Đã bao gồm VAT và phụ phí bảo hiểm hàng dễ vỡ OCOP) */
  shippingFee?:
    | Money
    | undefined;
  /** Tên đơn vị vận chuyển được chọn (Ví dụ: "GIAO_HANG_NHANH", "VIETTEL_POST") */
  carrier: string;
  /** Tên gói dịch vụ giao vận (Ví dụ: "Giao Hàng Tiêu Chuẩn Huế - Hà Nội 48h") */
  serviceName: string;
  /** Số ngày dự kiến giao đến nơi (Ví dụ: 2 ngày) */
  estimatedDeliveryDays: number;
  /** Lỗi nếu địa chỉ không được hỗ trợ giao vận */
  error?: ErrorDetail | undefined;
}

/** Yêu cầu bàn giao bưu kiện sang 3PL */
export interface CreateShipmentRequest {
  idempotencyKey: string;
  orderId: string;
  destinationAddress?: Address | undefined;
  parcelWeight?: Weight | undefined;
  carrier: string;
  /** Mã số tem Seal O Mạ đã dán niêm phong lên hộp */
  sealCode: string;
  /** Ghi chú cho bưu tá (Ví dụ: "Đặc sản mè xửng giòn Huế, xin nhẹ tay, cho xem hàng") */
  shippingNotes?: string | undefined;
}

/** Phản hồi tạo bưu kiện 3PL */
export interface CreateShipmentResponse {
  /** Mã vận đơn của đối tác giao hàng (Tracking Number, ví dụ: "GHN202610150998") */
  trackingCode: string;
  /** Mã định danh đơn hàng trên hệ thống của hãng vận chuyển */
  carrierOrderId: string;
  /** Nhãn in phiếu giao hàng (Dạng URL file PDF in nhiệt kích thước A6) */
  shippingLabelUrl?:
    | string
    | undefined;
  /** Thời gian dự kiến bưu tá đến kho Huế lấy hàng */
  estimatedPickupTime?:
    | Date
    | undefined;
  /** Thời gian dự kiến giao đến tay người nhận */
  estimatedDeliveryTime?: Date | undefined;
}

/** Yêu cầu tra cứu hành trình */
export interface TrackShipmentRequest {
  trackingCode: string;
}

/** Điểm mốc lịch sử hành trình giao hàng */
export interface TrackingCheckpoint {
  timestamp?:
    | Date
    | undefined;
  /** Ví dụ: "Bưu cục Trung Chuyển Huế", "Kho Mega Long Biên" */
  location: string;
  /** Ví dụ: "Kiện hàng đã xuất bưu cục" */
  description: string;
}

/** Phản hồi tra cứu hành trình */
export interface TrackShipmentResponse {
  trackingCode: string;
  carrier: string;
  currentStatus: ShipmentStatus;
  checkpoints: TrackingCheckpoint[];
}

function createBaseCalculateShippingFeeRequest(): CalculateShippingFeeRequest {
  return {
    idempotencyKey: "",
    destinationAddress: undefined,
    totalWeight: undefined,
    preferredCarrier: undefined,
    isFragile: false,
  };
}

export const CalculateShippingFeeRequest = {
  encode(message: CalculateShippingFeeRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.destinationAddress !== undefined) {
      Address.encode(message.destinationAddress, writer.uint32(18).fork()).ldelim();
    }
    if (message.totalWeight !== undefined) {
      Weight.encode(message.totalWeight, writer.uint32(26).fork()).ldelim();
    }
    if (message.preferredCarrier !== undefined) {
      writer.uint32(34).string(message.preferredCarrier);
    }
    if (message.isFragile !== false) {
      writer.uint32(40).bool(message.isFragile);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CalculateShippingFeeRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateShippingFeeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.destinationAddress = Address.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.totalWeight = Weight.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.preferredCarrier = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.isFragile = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateShippingFeeRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      destinationAddress: isSet(object.destinationAddress) ? Address.fromJSON(object.destinationAddress) : undefined,
      totalWeight: isSet(object.totalWeight) ? Weight.fromJSON(object.totalWeight) : undefined,
      preferredCarrier: isSet(object.preferredCarrier) ? globalThis.String(object.preferredCarrier) : undefined,
      isFragile: isSet(object.isFragile) ? globalThis.Boolean(object.isFragile) : false,
    };
  },

  toJSON(message: CalculateShippingFeeRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.destinationAddress !== undefined) {
      obj.destinationAddress = Address.toJSON(message.destinationAddress);
    }
    if (message.totalWeight !== undefined) {
      obj.totalWeight = Weight.toJSON(message.totalWeight);
    }
    if (message.preferredCarrier !== undefined) {
      obj.preferredCarrier = message.preferredCarrier;
    }
    if (message.isFragile !== false) {
      obj.isFragile = message.isFragile;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateShippingFeeRequest>, I>>(base?: I): CalculateShippingFeeRequest {
    return CalculateShippingFeeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateShippingFeeRequest>, I>>(object: I): CalculateShippingFeeRequest {
    const message = createBaseCalculateShippingFeeRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.destinationAddress = (object.destinationAddress !== undefined && object.destinationAddress !== null)
      ? Address.fromPartial(object.destinationAddress)
      : undefined;
    message.totalWeight = (object.totalWeight !== undefined && object.totalWeight !== null)
      ? Weight.fromPartial(object.totalWeight)
      : undefined;
    message.preferredCarrier = object.preferredCarrier ?? undefined;
    message.isFragile = object.isFragile ?? false;
    return message;
  },
};

function createBaseCalculateShippingFeeResponse(): CalculateShippingFeeResponse {
  return { shippingFee: undefined, carrier: "", serviceName: "", estimatedDeliveryDays: 0, error: undefined };
}

export const CalculateShippingFeeResponse = {
  encode(message: CalculateShippingFeeResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.shippingFee !== undefined) {
      Money.encode(message.shippingFee, writer.uint32(10).fork()).ldelim();
    }
    if (message.carrier !== "") {
      writer.uint32(18).string(message.carrier);
    }
    if (message.serviceName !== "") {
      writer.uint32(26).string(message.serviceName);
    }
    if (message.estimatedDeliveryDays !== 0) {
      writer.uint32(32).int32(message.estimatedDeliveryDays);
    }
    if (message.error !== undefined) {
      ErrorDetail.encode(message.error, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CalculateShippingFeeResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateShippingFeeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.shippingFee = Money.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.carrier = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.estimatedDeliveryDays = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.error = ErrorDetail.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CalculateShippingFeeResponse {
    return {
      shippingFee: isSet(object.shippingFee) ? Money.fromJSON(object.shippingFee) : undefined,
      carrier: isSet(object.carrier) ? globalThis.String(object.carrier) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      estimatedDeliveryDays: isSet(object.estimatedDeliveryDays) ? globalThis.Number(object.estimatedDeliveryDays) : 0,
      error: isSet(object.error) ? ErrorDetail.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: CalculateShippingFeeResponse): unknown {
    const obj: any = {};
    if (message.shippingFee !== undefined) {
      obj.shippingFee = Money.toJSON(message.shippingFee);
    }
    if (message.carrier !== "") {
      obj.carrier = message.carrier;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.estimatedDeliveryDays !== 0) {
      obj.estimatedDeliveryDays = Math.round(message.estimatedDeliveryDays);
    }
    if (message.error !== undefined) {
      obj.error = ErrorDetail.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalculateShippingFeeResponse>, I>>(base?: I): CalculateShippingFeeResponse {
    return CalculateShippingFeeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalculateShippingFeeResponse>, I>>(object: I): CalculateShippingFeeResponse {
    const message = createBaseCalculateShippingFeeResponse();
    message.shippingFee = (object.shippingFee !== undefined && object.shippingFee !== null)
      ? Money.fromPartial(object.shippingFee)
      : undefined;
    message.carrier = object.carrier ?? "";
    message.serviceName = object.serviceName ?? "";
    message.estimatedDeliveryDays = object.estimatedDeliveryDays ?? 0;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorDetail.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseCreateShipmentRequest(): CreateShipmentRequest {
  return {
    idempotencyKey: "",
    orderId: "",
    destinationAddress: undefined,
    parcelWeight: undefined,
    carrier: "",
    sealCode: "",
    shippingNotes: undefined,
  };
}

export const CreateShipmentRequest = {
  encode(message: CreateShipmentRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.destinationAddress !== undefined) {
      Address.encode(message.destinationAddress, writer.uint32(26).fork()).ldelim();
    }
    if (message.parcelWeight !== undefined) {
      Weight.encode(message.parcelWeight, writer.uint32(34).fork()).ldelim();
    }
    if (message.carrier !== "") {
      writer.uint32(42).string(message.carrier);
    }
    if (message.sealCode !== "") {
      writer.uint32(50).string(message.sealCode);
    }
    if (message.shippingNotes !== undefined) {
      writer.uint32(58).string(message.shippingNotes);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateShipmentRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShipmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.destinationAddress = Address.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.parcelWeight = Weight.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.carrier = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.sealCode = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.shippingNotes = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateShipmentRequest {
    return {
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      destinationAddress: isSet(object.destinationAddress) ? Address.fromJSON(object.destinationAddress) : undefined,
      parcelWeight: isSet(object.parcelWeight) ? Weight.fromJSON(object.parcelWeight) : undefined,
      carrier: isSet(object.carrier) ? globalThis.String(object.carrier) : "",
      sealCode: isSet(object.sealCode) ? globalThis.String(object.sealCode) : "",
      shippingNotes: isSet(object.shippingNotes) ? globalThis.String(object.shippingNotes) : undefined,
    };
  },

  toJSON(message: CreateShipmentRequest): unknown {
    const obj: any = {};
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.destinationAddress !== undefined) {
      obj.destinationAddress = Address.toJSON(message.destinationAddress);
    }
    if (message.parcelWeight !== undefined) {
      obj.parcelWeight = Weight.toJSON(message.parcelWeight);
    }
    if (message.carrier !== "") {
      obj.carrier = message.carrier;
    }
    if (message.sealCode !== "") {
      obj.sealCode = message.sealCode;
    }
    if (message.shippingNotes !== undefined) {
      obj.shippingNotes = message.shippingNotes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateShipmentRequest>, I>>(base?: I): CreateShipmentRequest {
    return CreateShipmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateShipmentRequest>, I>>(object: I): CreateShipmentRequest {
    const message = createBaseCreateShipmentRequest();
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.orderId = object.orderId ?? "";
    message.destinationAddress = (object.destinationAddress !== undefined && object.destinationAddress !== null)
      ? Address.fromPartial(object.destinationAddress)
      : undefined;
    message.parcelWeight = (object.parcelWeight !== undefined && object.parcelWeight !== null)
      ? Weight.fromPartial(object.parcelWeight)
      : undefined;
    message.carrier = object.carrier ?? "";
    message.sealCode = object.sealCode ?? "";
    message.shippingNotes = object.shippingNotes ?? undefined;
    return message;
  },
};

function createBaseCreateShipmentResponse(): CreateShipmentResponse {
  return {
    trackingCode: "",
    carrierOrderId: "",
    shippingLabelUrl: undefined,
    estimatedPickupTime: undefined,
    estimatedDeliveryTime: undefined,
  };
}

export const CreateShipmentResponse = {
  encode(message: CreateShipmentResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.trackingCode !== "") {
      writer.uint32(10).string(message.trackingCode);
    }
    if (message.carrierOrderId !== "") {
      writer.uint32(18).string(message.carrierOrderId);
    }
    if (message.shippingLabelUrl !== undefined) {
      writer.uint32(26).string(message.shippingLabelUrl);
    }
    if (message.estimatedPickupTime !== undefined) {
      Timestamp.encode(toTimestamp(message.estimatedPickupTime), writer.uint32(34).fork()).ldelim();
    }
    if (message.estimatedDeliveryTime !== undefined) {
      Timestamp.encode(toTimestamp(message.estimatedDeliveryTime), writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateShipmentResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShipmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.trackingCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.carrierOrderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.shippingLabelUrl = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.estimatedPickupTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.estimatedDeliveryTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateShipmentResponse {
    return {
      trackingCode: isSet(object.trackingCode) ? globalThis.String(object.trackingCode) : "",
      carrierOrderId: isSet(object.carrierOrderId) ? globalThis.String(object.carrierOrderId) : "",
      shippingLabelUrl: isSet(object.shippingLabelUrl) ? globalThis.String(object.shippingLabelUrl) : undefined,
      estimatedPickupTime: isSet(object.estimatedPickupTime)
        ? fromJsonTimestamp(object.estimatedPickupTime)
        : undefined,
      estimatedDeliveryTime: isSet(object.estimatedDeliveryTime)
        ? fromJsonTimestamp(object.estimatedDeliveryTime)
        : undefined,
    };
  },

  toJSON(message: CreateShipmentResponse): unknown {
    const obj: any = {};
    if (message.trackingCode !== "") {
      obj.trackingCode = message.trackingCode;
    }
    if (message.carrierOrderId !== "") {
      obj.carrierOrderId = message.carrierOrderId;
    }
    if (message.shippingLabelUrl !== undefined) {
      obj.shippingLabelUrl = message.shippingLabelUrl;
    }
    if (message.estimatedPickupTime !== undefined) {
      obj.estimatedPickupTime = message.estimatedPickupTime.toISOString();
    }
    if (message.estimatedDeliveryTime !== undefined) {
      obj.estimatedDeliveryTime = message.estimatedDeliveryTime.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateShipmentResponse>, I>>(base?: I): CreateShipmentResponse {
    return CreateShipmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateShipmentResponse>, I>>(object: I): CreateShipmentResponse {
    const message = createBaseCreateShipmentResponse();
    message.trackingCode = object.trackingCode ?? "";
    message.carrierOrderId = object.carrierOrderId ?? "";
    message.shippingLabelUrl = object.shippingLabelUrl ?? undefined;
    message.estimatedPickupTime = object.estimatedPickupTime ?? undefined;
    message.estimatedDeliveryTime = object.estimatedDeliveryTime ?? undefined;
    return message;
  },
};

function createBaseTrackShipmentRequest(): TrackShipmentRequest {
  return { trackingCode: "" };
}

export const TrackShipmentRequest = {
  encode(message: TrackShipmentRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.trackingCode !== "") {
      writer.uint32(10).string(message.trackingCode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrackShipmentRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrackShipmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.trackingCode = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrackShipmentRequest {
    return { trackingCode: isSet(object.trackingCode) ? globalThis.String(object.trackingCode) : "" };
  },

  toJSON(message: TrackShipmentRequest): unknown {
    const obj: any = {};
    if (message.trackingCode !== "") {
      obj.trackingCode = message.trackingCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackShipmentRequest>, I>>(base?: I): TrackShipmentRequest {
    return TrackShipmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackShipmentRequest>, I>>(object: I): TrackShipmentRequest {
    const message = createBaseTrackShipmentRequest();
    message.trackingCode = object.trackingCode ?? "";
    return message;
  },
};

function createBaseTrackingCheckpoint(): TrackingCheckpoint {
  return { timestamp: undefined, location: "", description: "" };
}

export const TrackingCheckpoint = {
  encode(message: TrackingCheckpoint, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.timestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.timestamp), writer.uint32(10).fork()).ldelim();
    }
    if (message.location !== "") {
      writer.uint32(18).string(message.location);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrackingCheckpoint {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrackingCheckpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.timestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.location = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrackingCheckpoint {
    return {
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: TrackingCheckpoint): unknown {
    const obj: any = {};
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp.toISOString();
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackingCheckpoint>, I>>(base?: I): TrackingCheckpoint {
    return TrackingCheckpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackingCheckpoint>, I>>(object: I): TrackingCheckpoint {
    const message = createBaseTrackingCheckpoint();
    message.timestamp = object.timestamp ?? undefined;
    message.location = object.location ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseTrackShipmentResponse(): TrackShipmentResponse {
  return { trackingCode: "", carrier: "", currentStatus: 0, checkpoints: [] };
}

export const TrackShipmentResponse = {
  encode(message: TrackShipmentResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.trackingCode !== "") {
      writer.uint32(10).string(message.trackingCode);
    }
    if (message.carrier !== "") {
      writer.uint32(18).string(message.carrier);
    }
    if (message.currentStatus !== 0) {
      writer.uint32(24).int32(message.currentStatus);
    }
    for (const v of message.checkpoints) {
      TrackingCheckpoint.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrackShipmentResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrackShipmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.trackingCode = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.carrier = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.currentStatus = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.checkpoints.push(TrackingCheckpoint.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrackShipmentResponse {
    return {
      trackingCode: isSet(object.trackingCode) ? globalThis.String(object.trackingCode) : "",
      carrier: isSet(object.carrier) ? globalThis.String(object.carrier) : "",
      currentStatus: isSet(object.currentStatus) ? shipmentStatusFromJSON(object.currentStatus) : 0,
      checkpoints: globalThis.Array.isArray(object?.checkpoints)
        ? object.checkpoints.map((e: any) => TrackingCheckpoint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TrackShipmentResponse): unknown {
    const obj: any = {};
    if (message.trackingCode !== "") {
      obj.trackingCode = message.trackingCode;
    }
    if (message.carrier !== "") {
      obj.carrier = message.carrier;
    }
    if (message.currentStatus !== 0) {
      obj.currentStatus = shipmentStatusToJSON(message.currentStatus);
    }
    if (message.checkpoints?.length) {
      obj.checkpoints = message.checkpoints.map((e) => TrackingCheckpoint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrackShipmentResponse>, I>>(base?: I): TrackShipmentResponse {
    return TrackShipmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrackShipmentResponse>, I>>(object: I): TrackShipmentResponse {
    const message = createBaseTrackShipmentResponse();
    message.trackingCode = object.trackingCode ?? "";
    message.carrier = object.carrier ?? "";
    message.currentStatus = object.currentStatus ?? 0;
    message.checkpoints = object.checkpoints?.map((e) => TrackingCheckpoint.fromPartial(e)) || [];
    return message;
  },
};

export type ShippingServiceService = typeof ShippingServiceService;
export const ShippingServiceService = {
  /** Tính toán phí vận chuyển chính xác theo địa chỉ và khối lượng kiện hàng (Critical Path < 30ms) */
  calculateShippingFee: {
    path: "/omamx.shipping.v1.ShippingService/CalculateShippingFee",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CalculateShippingFeeRequest) =>
      Buffer.from(CalculateShippingFeeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CalculateShippingFeeRequest.decode(value),
    responseSerialize: (value: CalculateShippingFeeResponse) =>
      Buffer.from(CalculateShippingFeeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CalculateShippingFeeResponse.decode(value),
  },
  /** Tạo phiếu gửi hàng sang đơn vị 3PL (GHN/ViettelPost) sau khi kẹo đã niêm phong xong */
  createShipment: {
    path: "/omamx.shipping.v1.ShippingService/CreateShipment",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateShipmentRequest) => Buffer.from(CreateShipmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateShipmentRequest.decode(value),
    responseSerialize: (value: CreateShipmentResponse) => Buffer.from(CreateShipmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CreateShipmentResponse.decode(value),
  },
  /** Tra cứu hành trình vận chuyển thời gian thực của bưu kiện */
  trackShipment: {
    path: "/omamx.shipping.v1.ShippingService/TrackShipment",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: TrackShipmentRequest) => Buffer.from(TrackShipmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => TrackShipmentRequest.decode(value),
    responseSerialize: (value: TrackShipmentResponse) => Buffer.from(TrackShipmentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => TrackShipmentResponse.decode(value),
  },
} as const;

export interface ShippingServiceServer extends UntypedServiceImplementation {
  /** Tính toán phí vận chuyển chính xác theo địa chỉ và khối lượng kiện hàng (Critical Path < 30ms) */
  calculateShippingFee: handleUnaryCall<CalculateShippingFeeRequest, CalculateShippingFeeResponse>;
  /** Tạo phiếu gửi hàng sang đơn vị 3PL (GHN/ViettelPost) sau khi kẹo đã niêm phong xong */
  createShipment: handleUnaryCall<CreateShipmentRequest, CreateShipmentResponse>;
  /** Tra cứu hành trình vận chuyển thời gian thực của bưu kiện */
  trackShipment: handleUnaryCall<TrackShipmentRequest, TrackShipmentResponse>;
}

export interface ShippingServiceClient extends Client {
  /** Tính toán phí vận chuyển chính xác theo địa chỉ và khối lượng kiện hàng (Critical Path < 30ms) */
  calculateShippingFee(
    request: CalculateShippingFeeRequest,
    callback: (error: ServiceError | null, response: CalculateShippingFeeResponse) => void,
  ): ClientUnaryCall;
  calculateShippingFee(
    request: CalculateShippingFeeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CalculateShippingFeeResponse) => void,
  ): ClientUnaryCall;
  calculateShippingFee(
    request: CalculateShippingFeeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CalculateShippingFeeResponse) => void,
  ): ClientUnaryCall;
  /** Tạo phiếu gửi hàng sang đơn vị 3PL (GHN/ViettelPost) sau khi kẹo đã niêm phong xong */
  createShipment(
    request: CreateShipmentRequest,
    callback: (error: ServiceError | null, response: CreateShipmentResponse) => void,
  ): ClientUnaryCall;
  createShipment(
    request: CreateShipmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateShipmentResponse) => void,
  ): ClientUnaryCall;
  createShipment(
    request: CreateShipmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateShipmentResponse) => void,
  ): ClientUnaryCall;
  /** Tra cứu hành trình vận chuyển thời gian thực của bưu kiện */
  trackShipment(
    request: TrackShipmentRequest,
    callback: (error: ServiceError | null, response: TrackShipmentResponse) => void,
  ): ClientUnaryCall;
  trackShipment(
    request: TrackShipmentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TrackShipmentResponse) => void,
  ): ClientUnaryCall;
  trackShipment(
    request: TrackShipmentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TrackShipmentResponse) => void,
  ): ClientUnaryCall;
}

export const ShippingServiceClient = makeGenericClientConstructor(
  ShippingServiceService,
  "omamx.shipping.v1.ShippingService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ShippingServiceClient;
  service: typeof ShippingServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
