"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupportTicketDetail, SupportTicketList, SupportTicketSummary, TicketPriority, TicketSlaState, TicketStatus } from "@/lib/support/types";
import { AdminSupportApiError } from "@/lib/support/types";
import { adminSupportService } from "@/services/admin-support-service";

const DATE_TIME = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
function Status({ code, label, prefix = "ticket" }: { code: string; label: string; prefix?: string }) { return <span className={`admin-status ${prefix}-${code.toLowerCase()}`}>{label}</span>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) { return <div className="admin-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-modal wide" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><button type="button" onClick={onClose} aria-label="Đóng popup">×</button></header>{children}</section></div>; }

export function SupportTicketWorkspace() {
  const [data, setData] = useState<SupportTicketList | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [status, setStatus] = useState<"ALL" | TicketStatus>("ALL"); const [query, setQuery] = useState(""); const [priority, setPriority] = useState<"ALL" | TicketPriority>("ALL"); const [channel, setChannel] = useState("ALL"); const [sla, setSla] = useState<"ALL" | TicketSlaState>("ALL");
  const [menuId, setMenuId] = useState(""); const [selected, setSelected] = useState<SupportTicketSummary | null>(null); const [detail, setDetail] = useState<SupportTicketDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState("");
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { setData(await adminSupportService.tickets()); } catch (cause) { setLoadError(cause instanceof AdminSupportApiError ? cause.message : "Không thể tải hàng đợi Ticket."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("vi"); return data?.items.filter((item) => (status === "ALL" || item.status === status) && (priority === "ALL" || item.priority === priority) && (channel === "ALL" || item.channelCode === channel) && (sla === "ALL" || item.firstResponseSla.state === sla || item.resolutionSla.state === sla) && (!needle || [item.ticketNumber, item.title, item.customerLabel, item.subjectLabel].some((value) => value.toLocaleLowerCase("vi").includes(needle)))) ?? []; }, [channel, data, priority, query, sla, status]);
  const active = data?.items.filter((item) => !["RESOLVED", "CLOSED"].includes(item.status)).length ?? 0; const unassigned = data?.items.filter((item) => !item.assigneeLabel && !["RESOLVED", "CLOSED"].includes(item.status)).length ?? 0; const risk = data?.items.filter((item) => [item.firstResponseSla.state, item.resolutionSla.state].some((value) => ["AT_RISK", "OVERDUE"].includes(value))).length ?? 0; const waiting = data?.items.filter((item) => item.status === "WAITING_CUSTOMER").length ?? 0;
  async function openDetail(item: SupportTicketSummary) { setMenuId(""); setSelected(item); setDetail(null); setDetailError(""); setDetailLoading(true); try { const loaded = await adminSupportService.ticket(item.ticketId); setDetail({ ...loaded, ...item, customer: loaded.customer, messages: loaded.messages, conversationMasked: loaded.conversationMasked, context: loaded.context, contextMasked: loaded.contextMasked, history: loaded.history, createdAt: loaded.createdAt }); } catch (cause) { setDetailError(cause instanceof AdminSupportApiError ? cause.message : "Không thể tải chi tiết Ticket."); } finally { setDetailLoading(false); } }
  if (loading) return <div className="admin-page"><div className="admin-page-skeleton"><div /><div /><div /></div></div>;
  if (!data) return <div className="admin-page"><section className="admin-error-state"><span>!</span><h1>Chưa thể tải Ticket</h1><p>{loadError}</p><button className="admin-primary-button" onClick={() => void load()}>Thử lại</button></section></div>;
  return <div className="admin-page"><header className="admin-page-header"><div><nav>Admin <span>›</span> Hậu mãi <span>›</span> Ticket hỗ trợ</nav><h1>Quản lý Ticket hỗ trợ</h1><p>Hàng đợi, hội thoại và ngữ cảnh giao dịch chỉ đọc theo Epic 16 — Giai đoạn 2.</p></div><div className="admin-page-actions"><button className="admin-secondary-button" type="button" onClick={() => void load()}>↻ Làm mới</button></div></header>
    <section className="admin-summary-grid"><article><span>Ticket đang mở</span><strong>{active}</strong><small>Chưa ở trạng thái Resolved hoặc Closed</small></article><article><span>Chưa phân công</span><strong>{unassigned}</strong><small>Ticket mở chưa có nhân viên phụ trách</small></article><article><span>SLA cần chú ý</span><strong>{risk}</strong><small>Có mốc phản hồi hoặc giải quyết gần/quá hạn</small></article><article><span>Chờ khách hàng</span><strong>{waiting}</strong><small>Quy tắc dừng SLA do upstream quyết định</small></article></section>
    <section className="admin-list-card"><div className="admin-status-tabs" role="tablist" aria-label="Lọc trạng thái Ticket">{data.statusCounts.map((item) => <button className={status === item.status ? "active" : ""} type="button" role="tab" aria-selected={status === item.status} onClick={() => setStatus(item.status)} key={item.status}>{item.label}<b>{item.count}</b></button>)}</div><div className="admin-list-toolbar support-toolbar"><label className="admin-table-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm Ticket, khách hàng, tiêu đề hoặc chủ đề…" /></label><label><span className="sr-only">Ưu tiên</span><select value={priority} onChange={(event) => setPriority(event.target.value as "ALL" | TicketPriority)}><option value="ALL">Mọi mức ưu tiên</option><option value="NORMAL">Bình thường</option><option value="IMPORTANT">Quan trọng</option><option value="URGENT">Khẩn cấp</option></select></label><label><span className="sr-only">Kênh</span><select value={channel} onChange={(event) => setChannel(event.target.value)}><option value="ALL">Mọi kênh</option>{data.channels.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label><label><span className="sr-only">SLA</span><select value={sla} onChange={(event) => setSla(event.target.value as "ALL" | TicketSlaState)}><option value="ALL">Mọi tình trạng SLA</option><option value="ON_TRACK">Đúng hạn</option><option value="AT_RISK">Gần quá hạn</option><option value="OVERDUE">Quá hạn</option><option value="PAUSED">Đang tạm dừng</option><option value="COMPLETE">Đã hoàn tất</option></select></label><button className="admin-filter-reset" type="button" onClick={() => { setStatus("ALL"); setQuery(""); setPriority("ALL"); setChannel("ALL"); setSla("ALL"); }}>Đặt lại</button></div><div className="admin-table-meta"><span>Hiển thị <strong>{filtered.length}</strong> Ticket</span><span>Cập nhật lúc {DATE_TIME.format(new Date(data.calculatedAt))}</span></div>
      <div className="admin-table-wrap"><table className="admin-table admin-support-table"><thead><tr><th>Ticket / Khách hàng</th><th>Chủ đề</th><th>Kênh</th><th>Trạng thái</th><th>Ưu tiên</th><th>Phản hồi đầu</th><th>Giải quyết</th><th>Phụ trách / Tin mới</th><th aria-label="Tùy chọn" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.ticketId}><td><strong>{item.ticketNumber}</strong><small>{item.customerLabel} · {item.customerMode === "GUEST" ? "Guest" : "Đã đăng ký"}</small></td><td><strong>{item.subjectLabel}</strong><small>{item.title}</small></td><td><strong>{item.channelLabel}</strong><small>{item.linkedReferenceCount} liên kết nghiệp vụ</small></td><td><Status code={item.status} label={item.statusLabel} /></td><td><Status code={item.priority} label={item.priorityLabel} prefix="ticket-priority" /></td><td><Status code={item.firstResponseSla.state} label={item.firstResponseSla.stateLabel} prefix="ticket-sla" /></td><td><Status code={item.resolutionSla.state} label={item.resolutionSla.stateLabel} prefix="ticket-sla" /></td><td><strong>{item.assigneeLabel ?? "Chưa phân công"}</strong><small>{item.unreadCount ? `${item.unreadCount} tin chưa đọc` : `Cập nhật ${DATE_TIME.format(new Date(item.updatedAt))}`}</small></td><td className="admin-action-cell"><button type="button" aria-label={`Tùy chọn ${item.ticketNumber}`} onClick={() => setMenuId((current) => current === item.ticketId ? "" : item.ticketId)}>•••</button>{menuId === item.ticketId ? <div className="admin-row-menu"><button type="button" onClick={() => void openDetail(item)}>Xem chi tiết</button></div> : null}</td></tr>)}</tbody></table>{!filtered.length ? <div className="admin-empty"><span>⌕</span><h3>Không có Ticket phù hợp</h3><p>Hãy thay đổi trạng thái, từ khóa hoặc bộ lọc hiện tại.</p></div> : null}</div><footer className="admin-pagination"><span>Trang 1 / 1</span><div><button disabled>‹</button><button className="active">1</button><button disabled>›</button></div></footer></section>
    {selected ? <Modal title={`Ticket · ${selected.ticketNumber}`} subtitle={`${selected.queueLabel} · Revision ${selected.revision}`} onClose={() => setSelected(null)}>{detailLoading ? <div className="admin-modal-loading">Đang tải hội thoại và ngữ cảnh…</div> : detail ? <TicketDetail detail={detail} /> : <div className="admin-inline-error">{detailError}</div>}</Modal> : null}
  </div>;
}

function TicketDetail({ detail }: { detail: SupportTicketDetail }) { return <div className="admin-support-detail"><div className="admin-detail-summary"><Status code={detail.status} label={detail.statusLabel} /><Status code={detail.priority} label={detail.priorityLabel} prefix="ticket-priority" /><span>{detail.channelLabel}</span><span>{detail.assigneeLabel ?? "Chưa phân công"}</span></div>
  <div className="admin-detail-grid"><section><h3>Khách hàng và Ticket</h3><dl><div><dt>Khách hàng</dt><dd>{detail.customer.displayName}</dd></div><div><dt>Liên hệ</dt><dd>{detail.customer.contactDisplay}</dd></div><div><dt>Hồ sơ</dt><dd>{detail.customer.profileLabel}</dd></div><div><dt>Chủ đề</dt><dd>{detail.subjectLabel}</dd></div><div><dt>Tạo lúc</dt><dd>{DATE_TIME.format(new Date(detail.createdAt))}</dd></div></dl></section><section><h3>SLA từ upstream</h3><dl><div><dt>Phản hồi đầu</dt><dd>{detail.firstResponseSla.stateLabel}</dd></div><div><dt>Hạn phản hồi</dt><dd>{detail.firstResponseSla.dueAt ? DATE_TIME.format(new Date(detail.firstResponseSla.dueAt)) : "Đã hoàn tất/không có"}</dd></div><div><dt>Giải quyết</dt><dd>{detail.resolutionSla.stateLabel}</dd></div><div><dt>Hạn giải quyết</dt><dd>{detail.resolutionSla.dueAt ? DATE_TIME.format(new Date(detail.resolutionSla.dueAt)) : "Đã hoàn tất/không có"}</dd></div><div><dt>Hàng đợi</dt><dd>{detail.queueLabel}</dd></div></dl></section></div>
  <section><h3>Ngữ cảnh giao dịch</h3>{detail.contextMasked ? <div className="support-permission-note">Ngữ cảnh đã được che vì thiếu `TICKET_CONTEXT_VIEW`.</div> : detail.context ? <div className="support-context-grid"><article><span>Order</span><strong>{detail.context.order?.reference ?? "Không liên kết"}</strong><small>{detail.context.order?.statusLabel ?? "—"}</small></article><article><span>Payment</span><strong>{detail.context.payment?.statusLabel ?? "Không có"}</strong><small>Dữ liệu nguồn, không chỉnh sửa từ Ticket</small></article><article><span>Shipment</span><strong>{detail.context.shipment?.statusLabel ?? "Không có"}</strong><small>Dữ liệu nguồn, không chỉnh sửa từ Ticket</small></article><article><span>Return Case</span><strong>{detail.context.returnCase?.reference ?? "Không liên kết"}</strong><small>{detail.context.returnCase?.statusLabel ?? "—"}</small></article></div> : <div className="support-permission-note">Ticket không có ngữ cảnh giao dịch liên kết.</div>}</section>
  <section><h3>Hội thoại và ghi chú</h3>{detail.conversationMasked ? <div className="support-permission-note">Timeline đã được che vì thiếu `TICKET_CONVERSATION_VIEW`.</div> : <div className="support-message-list">{detail.messages.map((item) => <article className={item.kind === "INTERNAL_NOTE" ? "internal" : item.senderRole === "CUSTOMER" ? "customer" : "agent"} key={item.messageId}><header><strong>{item.senderLabel}</strong><span>{item.kind === "INTERNAL_NOTE" ? "Ghi chú nội bộ" : item.channelLabel}</span><small>{DATE_TIME.format(new Date(item.sentAt))}</small></header><p>{item.content}</p><footer>{item.deliveryStateLabel}</footer></article>)}</div>}</section>
  <section><h3>Lịch sử xử lý</h3><ol className="admin-order-timeline">{detail.history.map((item) => <li key={item.eventId}><span /><div><strong>{item.label}</strong><small>{DATE_TIME.format(new Date(item.occurredAt))} · {item.actorLabel}</small>{item.detail ? <p>{item.detail}</p> : null}</div></li>)}</ol></section>
  <footer>Ticket chỉ sở hữu hội thoại và SLA; Order, Payment, Shipment và Return Case vẫn thuộc các Epic nguồn. Popup hiện không gửi phản hồi hoặc thay đổi dữ liệu nghiệp vụ.</footer></div>; }
